### ISSUE TITLE
Undo removes last entity placed instead of undoing the last operation

### ISSUE THREAD

**Issue by ChristopherKing42** [LibreCAD/LibreCAD#1002]
### Expected behavior
When hitting undo, the last operation should be undone. (The whole operation, not just part of it.)
### Observed behavior
When hitting undo, the last entity placed is removed. (Or if an entity was removed it is placed again.)
### Steps to reproduce or sample file
Draw a couple of lines, and then rotate them. When you undo, it will not revert to the previous state, but will instead delete just one of the lines.
### Operating System and LibreCAD version info
Version: 2.2.0-alpha
Compiler: GNU GCC 7.3.0
Compiled on: Jun 18 2018
Qt Version: 5.9.5
Boost Version: 1.65.1
System: Ubuntu 18.04.1 LTS

**Comment by Rex-On-GitHub** [comment]
I can somewhat reproduce this, though my first undo seemingly does nothing, and then the next undo deletes the last line.

Version: 2.2.0-rc1-36-g439d75d
Compiler: GNU GCC 5.4.0
Compiled on: Aug  7 2018
Qt Version: 5.5.1
Boost Version: 1.58.0
System: Linux Mint 18.3
