### ISSUE TITLE
Crash by doing mv with delete, undo, mv with delete.

### ISSUE THREAD

**Issue by Daniel-Trevitz** [LibreCAD/LibreCAD#1004]
### Expected behavior
No crash

### Observed behavior
Crashes

### Steps to reproduce or sample file
Create a line. Dimension the line.
move the dimension with the mv command. delete the origonal with the mv.
undo the mv
move the dimension with the mv command. delete the origonal with the mv.
crashes

### Operating System and LibreCAD version info
Linux Daniel6430 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux
personal branch - see Daniel-Trevitz:copy-paste-fix-2

**Comment by Daniel-Trevitz** [comment]
Crash occurs in void RS_Modification::deselectOriginals(bool remove) 
if (e->isSelected()) {  <-- crashes here
    selected = true;
}

e is previously deleted by bool RS_EntityContainer::removeEntity(RS_Entity*),

**Comment by lordofbikes** [comment]
This was possibly fixed with 2d8e025, but at least with ed90a19
