### ISSUE TITLE
PDF Dimension Numbers are blurry unless made to be really big.

### ISSUE THREAD

**Issue by retiform** [LibreCAD/LibreCAD#1012]
### Expected behavior: 
 Readable Dimensions on a PDF export

### Observed behavior: 
 Numbers are too thick on the PDF; like a bubble font, but so thick it is unreadable.

### Steps to reproduce or sample file: 
make PDF text height 4 on A4 with defualts

### Operating System and LibreCAD version info
Solus, LibreCAD 2.1.3

**Comment by lordofbikes** [comment]
Too less information, possibly a matter of correct scale?
Works for me with valid parameters.
