### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by chenshuxian1997** [LibreCAD/LibreCAD#1013]
I am an user who regard Chinese as my mother language. Some days before i received a file from my friend which was down by autocad.  The words in the file were shown as squares. I know this may because that the word is not supported. However, i just cannot find where to change existing characters. The information that i can find is Chinese is supported. So, what can i do?

A worry child

**Comment by lordofbikes** [comment]
Search and ask in the forum, the chances are much better to find other Chinese users who can help.
http://forum.librecad.org/template/NamlServlet.jtp?macro=search_page&node=4499512&query=chinese
http://forum.librecad.org/template/NamlServlet.jtp?macro=search_page&node=4499512&query=wenquanyi&n=4499512

This could also be a matter of draft mode:
http://forum.librecad.org/only-empty-boxes-frames-are-shown-for-image-text-no-line-thickness-td5706737.html
