### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [LibreCAD/LibreCAD#1017]
i've downloaded Version '2.1.3' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by fa201** [comment]
Is this issue still valid ?
