### ISSUE TITLE
close function for polylines - keyboard short cut / button / explanation

### ISSUE THREAD

**Issue by WolfgangFahl** [LibreCAD/LibreCAD#1036]
### Expected behavior
When drawing a polyline with the mouse it should be obvious / intuitive how to close the polyline.
E.g. a right mouse click could do this.

### Observed behavior
ESC works to finish a polyline with not closing.
There is no close button no keyboard shortcut explained in the wiki

### Steps to reproduce or sample file
https://wiki.librecad.org/index.php?title=Starting_to_draw

**Comment by WolfgangFahl** [comment]
see http://forum.librecad.org/how-to-create-closed-polygons-td5707144.html that this has been asked before. I couldn't find the anwer.

**Comment by lordofbikes** [comment]
The close polyline button is in the tool option bar which is active while drawing a polyline.
![grafik](https://user-images.githubusercontent.com/386273/48120676-1b2f4800-e273-11e8-8d5c-472f24ea9866.png)

The tool option bar is dynamically and vary with the used tool, but not all tools have options.

Right click has ESC functionality while drawing for all tools and cancel the active tool.

**Comment by WolfgangFahl** [comment]
What is the tool option bar and where is it under Mac OS X? It seems to also not be visible by default in the linux version - my ubuntu 16.04 LTS installed version 2.0.9.

**Comment by lordofbikes** [comment]
Possibly the tool option bar was disabled by accident. Activate it here:
![grafik](https://user-images.githubusercontent.com/386273/48176198-5bdc9f00-e30f-11e8-9629-61a1a668a5b4.png)

Then the tool options should be shown there:
![grafik](https://user-images.githubusercontent.com/386273/48176378-094fb280-e310-11e8-82fe-8fc5d672d15b.png)
