### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by WolfgangFahl** [LibreCAD/LibreCAD#1037]
### Expected behavior
https://librecad.org/cms/home/get-help.html
should redirect to the latest help info

### Observed behavior
https://librecad.org/cms/home/get-help.html
leads to a 404

### Steps to reproduce or sample file
`man librecad`

_In the mean time, to get help on LibreCAD, please visit  the  following
       link:_ http://librecad.org/cms/home/get-help.html

### Operating System and LibreCAD version info
Ubuntu 16.04 LTS LibreCAD version 2.0.9

**Comment by lordofbikes** [comment]
I fixed this with 6a0e9a9 in code base.
For old versions the web server now redirects to the new website.

Many thanks for reporting. :+1:
