### ISSUE TITLE
Commit for #1038 breaks dwg file

### ISSUE THREAD

**Issue by Daniel-Trevitz** [LibreCAD/LibreCAD#1045]
### Expected behavior
bool dxfRW::processHeader() returns true

### Observed behavior
bool dxfRW::processHeader() returns false

### Steps to reproduce or sample file
opening attached DXF
[House.zip](https://github.com/LibreCAD/LibreCAD/files/2572539/House.zip)

### Operating System and LibreCAD version info
master

**Comment by lordofbikes** [comment]
I reopened the original #1038

**Comment by lordofbikes** [comment]
Great! Many thanks for testing.
