### ISSUE TITLE
[ 2.2.0-rc1] Crashes on Windows 10

### ISSUE THREAD

**Issue by Nathan1852** [LibreCAD/LibreCAD#1076]
### Expected behavior
No Crashes

### Observed behavior
Crash

### Steps to reproduce or sample file
Don't know, it seems to crash on several actions, like moving etc.
I'd can upload the crash logs if I'd know where they are 

### Operating System and LibreCAD version info
Windows 10 1803
LibreCad  2.2.0-rc1

**Comment by shawncurry** [comment]
There's nothing to go on here.  I'll be doing quite a bit of testing on Win 10; I'll be sure to keep an eye out.

If you can come up with some steps to reproduce please reopen the ticket.
