### ISSUE TITLE
Vote for a new release.

### ISSUE THREAD

**Issue by Mannshoch** [LibreCAD/LibreCAD#1083]
Please focus for a new release.
Thanks

**Comment by veronyka** [comment]
Please work on new release, Draftsight is no longer free, you guys are the only one now.

**Comment by slokhorst** [comment]
Seems like there are no more open issues in the [2.2.0 Milestone](https://github.com/LibreCAD/LibreCAD/milestone/3). Is there anything else holding back the release?

**Comment by yves78** [comment]
Librecad is very useful for me : I use it often  for drawing parts before machining them, manually or with NC machine,  and I would really appreciate if the product could continue to be developped and maintained.

**Comment by jd666** [comment]
It is now 19 month since the 2.2.0 RC.. will there ever be a new release?

**Comment by AKmatiAK** [comment]
pls keep this great program alive :)

**Comment by lordofbikes** [comment]
It is not a matter of voting for a new release, so I'll close this now.
It's a matter of circumstances that 2.2.0 wasn't released in 2019.
We gonna combine forces with the new year to finally release the new version.
