### ISSUE TITLE
Grid off on file open prevent selection of entities in block editor

### ISSUE THREAD

**Issue by lordofbikes** [LibreCAD/LibreCAD#1094]
### Expected behavior
In block editor entities should be selected by click to modify.
 
### Observed behavior
As discussed in forum, select by click in block editor doesn't work when grid is off on file open.
See http://forum.librecad.org/Block-Editing-Issue-tp5716968.html

### Steps to reproduce or sample file
- create a file with a block.
- switch grid off
- save and close the file
- open the file again
- go to edit the block
- select by click doesn't work, but select by window works
- switch grid on, then select by click works again

### Operating System and LibreCAD version info
issue exists in current ```master``` HEAD
Ubuntu 18.04 LTS, but OS shouldn't matter

**Comment by dxli** [comment]
Solved by "free snap rework": 4174e1502d57dcd43dc9014da75f1cf5803d88e6

The snapping range is redefined to support when the grid is off. Previously, the snapping range is only reasonable when the grid is on.

The new free snapping scheme also redefined the snapping range for selecting/snapping an entity.
