### ISSUE TITLE
Add a preference to allow whitespace in command interface

### ISSUE THREAD

**Issue by shawncurry** [LibreCAD/LibreCAD#1098]
As an EU of the LibreCAD command interface, I prefer the old 2.1.3 method which allowed me to use white space in my commands.

### Expected behavior

I can use white space.

### Observed behavior

Typing a space causes immediate evaluation before I was ready.

### Steps to reproduce or sample file

Use LibreCAD 2.2 rc1

### Operating System and LibreCAD version info

Win10, built from master, using Qt5.12.3/MinGW7.3, also Visual Studio 2017

This behavior was added for Issue #764.  It appears to have been designed to mimic AutoCAD functionality.  This should probably have a preference; I think it will be confusing for new users who are inexperienced with AutoCAD,

**Comment by shawncurry** [comment]
This could be a check item in the quick options list:

![allowwhitespace](https://user-images.githubusercontent.com/50385855/57588487-f9917080-74e2-11e9-9bad-63d37d6c23fb.png)

The caption could probably use some work - suggestions welcome.

**Comment by vwren** [comment]
Sorry I'm late to the party.  Once I thought about it, I realized the message box could be improved.  I left a comment in the commit, if that's kosher.

**Comment by lordofbikes** [comment]
Discussion moved to #1099

**Comment by shawncurry** [comment]
This preference should be moved into the Application Preferences dialog.
