### ISSUE TITLE
Improve User Experience while working with multiple drawings

### ISSUE THREAD

**Issue by shawncurry** [LibreCAD/LibreCAD#1108]
As an End User who often works with multiple drawings open, I want to have my drawing window settings remembered, and to be able to save all my changes with one click.

### Expected behavior

The program remembers my preferences and provides a way to "Save All" changes.

### Observed behavior

It does not.

### Steps to reproduce or sample file

- Open multiple drawings
- Choose Drawings -> Tab mode
- Click Zoom Extents
- Close LibreCAD  <-- prompts to save each file
- Reopen LibreCAD  <-- returns to Sub-window mode, with windows maximized

### Operating System and LibreCAD version info

Win 10
Version: 2.2.0-rc1
Compiler: GNU GCC 4.9.1
Compiled on: Feb 16 2018
Qt Version: 5.4.1
Boost Version: 1.53.0

**Comment by shawncurry** [comment]
Let's face it - the Drawings menu is clunky.  When you switch between tab and sub-window, the menu choices change.  The "feel" of this menu could benefit from some checkable menu items, and possibly sub-menus.

The Save dialog that appears when you close the program, could possibly use a "Do this for the next <n> items" checkbox.  It also has a dated look.

A "Save All" button in the toolbar and File menu would also be handy.

**Comment by shawncurry** [comment]
The auto-save behavior should also be reviewed for this case. 

#1086 improve autosave for unnamed files

**Comment by shawncurry** [comment]
Actions

File -->
Close
Close All
Save unnamed1
Save unnamed1 As...
Save All

pseudo-code:
```
save() {
  if (dirty && showSaveAsIfNeeded(currentFileName; default="") == canceled)
    return false;
  return true;
}

saveAll() {
  foreach (document) {
    if (save() == false)
      return false;
  }
  return true;
}
```

etc

**Comment by shawncurry** [comment]
- Tab names should not include the path; only the file name
- Full path can be displayed in the hover hint

**Comment by shawncurry** [comment]
![newdrawingmenu](https://user-images.githubusercontent.com/50385855/59171505-33b95680-8b11-11e9-892c-8395d29cb534.png)
![newdrawingmenu2](https://user-images.githubusercontent.com/50385855/59171516-39af3780-8b11-11e9-82e8-d52223de616e.png)
![newfilemenu](https://user-images.githubusercontent.com/50385855/59171536-52b7e880-8b11-11e9-8f4a-67915529bcaa.png)
![newclosedialog](https://user-images.githubusercontent.com/50385855/59171522-42a00900-8b11-11e9-9fca-bf7165164b03.png)

**Comment by lordofbikes** [comment]
What I wonder is, how **rounded** looks like in Windows.
On Linux **rounded** tabs are rather rectangular
![image](https://user-images.githubusercontent.com/386273/59225220-70985280-8bd0-11e9-8d89-6078696b3e93.png)

**Comment by shawncurry** [comment]
Yes, the "Rounded" description seems misleading at best: (lol)
![roundedquoteunquote](https://user-images.githubusercontent.com/50385855/59237401-2b702280-8bc8-11e9-8f44-c3dfa1786811.png)

I prefer the "Triangular" version, which looks similar to the south-position tabs in several windows applications, like Excel.  The rectangular ones look "old" and ugly to me.
