### ISSUE TITLE
dwg sample wanted!!!

### ISSUE THREAD

**Issue by Huang88888888Fei** [LibreCAD/LibreCAD#1143]
### Expected behavior
I want to read a `dwg` file by using `libdxfrw.pro`. However, I don't know which function or class to choose. I need to change this `dwg` file to another coordinate system. Could you please write a piece of sample code for me, to visit the elements like points and lines in the `dwg` file? Thank you!

**Comment by lordofbikes** [comment]
There is already an example in the library repo:
https://github.com/LibreCAD/libdxfrw/tree/master/dwg2dxf
DWG support in libdxfrw is very rudimentary, it still often fails to read DWG files.
And there is no write support for DWG, only for DXF.
There are some more complete DWG libraries than libdxfrw out there, with write support too.
DWG is a proprietary format and has still a bunch of secrets. There is no public documentation available, all information is nonofficial and only from re-engineering.
