### ISSUE TITLE
Bug: Snap on entity during drawing a line and holding "shift" key

### ISSUE THREAD

**Issue by susnicek** [LibreCAD/LibreCAD#1145]
Dear developers,
I found the following bug in my Librecad:

### Expected behavior
Imagine I am going to draw a line by a mouse. When I am going to place a second point of the line and I am holding a "shift" key (wanting to draw only under 0°, 15,° 30°... angles) and concurrently the snap mode "snap on entity" is enabled - then I expect that I can snap on whatever edge, which the just drawn line is crossing.

### Observed behavior
The expected behavior simply does not work. Or sometimes it seems to be working, but an exact snapping on an entity is not achieved (can be found by zooming).

### Operating System and LibreCAD version info
Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
Librecad Version: 2.1.3
Compiler: GNU GCC 8.3.0
Compiled on: May 16 2019
Qt Version: 5.11.3
Boost Version: 1.67.0
System: Debian GNU/Linux bullseye/sid

**Comment by lordofbikes** [comment]
Solved with PR #1147, https://github.com/LibreCAD/LibreCAD/pull/1147/commits/9fb6ef7ad2301bf152e5505f172632e2c85f74ad.
Many thanks!
