### ISSUE TITLE
Custom Paper Size is not working

### ISSUE THREAD

**Issue by ekubovsky** [LibreCAD/LibreCAD#1158]
### Expected behavior

Custom paper size set via Current Drawing Preferences should be in effect, not reset or change on consequent Options dialog invocation, and should be in effect for Print Preview and PDF export.

### Observed behavior

Absolutely inconsistent behavior. Having units set to inches, and paper size set to custom value - neither drawing, nor Print Preview or PDF export maintain the values set. Subsequent Current Drawing Preferences dialog invocation changes the values time after time.

### Steps to reproduce or sample file

- Go to Options -> Current Drawing Preferences
- Select Units tab and set Main drawing unit to "Inch"
- Select Paper tab and set custom paper size to 17x11 inch
- Close Current Drawing Preferences dialog by clicking OK

test 1: Click Print Preview  - observe inconsistencies
test 2: Export as PDF - observe inconsistencies
test 3: open Current Drawing Preferences dialog again and observe paper size values

### Operating System and LibreCAD version info
OS: Windows 10
LibreCAD: v2.1.3

**Comment by slackuser0xae34** [comment]
Confirmed, I also see this behavior in LibreCAD (on Slackware64 14.2 Linux)

Easy Workaround:
    The problem appears (on my box) only when using "Custom" for "Landscape" pages, there isn't a problem for a "Portrait" oriented page.
    The easy solution, for landscape pages, is to draw something then save the drawing to a file, before attempting a print.

Technical Details & Tentative Solution:
    In "Options" -> "Current Drawing Preferences" LibreCAD saves the page dimensions in memory. If the user draws and saves the drawing to a file, then the page dimension are stored in the DXF file. This "sets" the page dimensions firmly.
    On the other hand, if the user goes back into "Options" -> "Current Drawing Preferences" without drawing/saving, then some items are reinitialized particularly "Custom" page dimensions.
    On the second entry into "Options" -> "Current Drawing Preferences" (with landscape dimensions and without saving) the "Height" and "Width" are reinitialized to 0. LibreCAD doesn't read the existing dimensions from memory.

    Specifically: when "Landscape" oriented dimensions are input (or the "Landscape" radio button is clicked) QT calls "void QG_DlgOptionsDrawing::on_rbLandscape_toggled(bool)" which calls "updatePaperSize()"

    The bug is in at line 755 in qg_dlgoptionsdrawing.cpp, 
        "QG_DlgOptionsDrawing::updatePaperSize()"
    ...
    RS_Vector s; //paper size: width, height

    if (format==RS2::Custom) {
        s.x = RS_Math::eval(lePaperWidth->text());
        s.y = RS_Math::eval(lePaperHeight->text());
    ...

    The RS_Vector "s" is presumably initialized to 0,0. Also, when the "Current Drawing Preferences" window is created and initialized, a Custom size of the value of 0 is assigned to the "Width" (which is "lePaperWidth") and "Height" (which is "lePaperHeight") boxes. Neither "lePaperWidth" nor "lePaperHeight" are updated with the paper sizes stored in memory. 

IMPORTANT: updatePaperSize is not called for an rbPortrait selection!

    The fix I've implemented is:

    ...
    RS_Vector s=graphic->getPaperSize();
    lePaperWidth->setText(QString("%1").setNum(s.x,'g',5));
    lePaperHeight->setText(QString("%1").setNum(s.y,'g',5));

    if (format==RS2::Custom) {
        s.x = RS_Math::eval(lePaperWidth->text());
        s.y = RS_Math::eval(lePaperHeight->text());
    ...

    This fix seems to work, but more extensive testing is needed. The "updatePaperSize" function is used for more than just the above. Thus, the above tentative fix may need tweaks. YMMV.

Thanks, slackuser0xae34
