### ISSUE TITLE
Fixed length dimension extension lines: more digits please

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1185]
In LibreCAD v 2.2.0 at Options - Current Drawing Preferences - Dimensions the General Scale now also affects Extension lines - Fixed length. 
Fine. Fixed length mostly is needed for architectural drawings. In Germany the standard unit for architecture is meter. The input box in LibreCAD only allows two digits after the decimal seperator. So the minimum input possible (xx,01) results in a 10 mm length on paper, which is too much if you don't have much space, for instance for cramped dimensions inside of a building.
So please at least one digit more or why not just use the same input box as for the other values. 

LibreCAD v 2.2.0

**Comment by lordofbikes** [comment]
fixed with merge of #1203
