### ISSUE TITLE
IDE support for the compilation of the sources for Windows

### ISSUE THREAD

**Issue by ber999** [LibreCAD/LibreCAD#1190]
### Expected behavior
N/A
### Observed behavior
N/A
### Steps to reproduce or sample file
N/A
### Operating System and LibreCAD version info
OS: Windows
How could I compile the sources for Windows by using the support of an IDE in particular eclipse?

**Comment by lordofbikes** [comment]
There is what we support for windows:
https://github.com/LibreCAD/LibreCAD/wiki/Build-from-source#windows
I don't know if somebody ever used Eclipse.
