### ISSUE TITLE
Crash when saving a block

### ISSUE THREAD

**Issue by Jim-2249** [LibreCAD/LibreCAD#1202]
### Expected behavior
Would save block just as any other

### Observed behavior
Crashes while saving block

### Steps to reproduce or sample file
1) open LibreCAD
2) open Crank circuit.dxf [Crank circuit.zip](https://github.com/LibreCAD/LibreCAD/files/4337616/Crank.circuit.zip)
3) select Block List tab
4) select Bridge three phase
5) click on "save the active block to a file"
6) wheel appears then LibreCAD closes

### Operating System and LibreCAD version info
Windows 10 pro 64
Version: 2.2.0-rc1-142-ge38b7088
Compiler: GNU GCC 4.9.1
Compiled on: May 17 2019
Qt Version: 5.4.1
Boost Version: 1.53.0
System: Windows

**Comment by TomaszPluta** [comment]
I can consider, reproducible. It ends with:
_malloc_consolidate(): invalid chunk size_
I will take a look at it.

**Comment by baranovskiykonstantin** [comment]
This issue has a fix: #1180.
