### ISSUE TITLE
Can't export the lines color to svg

### ISSUE THREAD

**Issue by liufeijin** [LibreCAD/LibreCAD#1218]
when export to svg all line becomes black.

**Comment by fa201** [comment]
Which version ?
Which system ?
How did you proceed ?

**Comment by liufeijin** [comment]
it is ok

**Comment by aslze** [comment]
I just noticed this problem and then found this issue (closed??). This is the stable 2.1.3 (as installed by winget).

Exporting to **MakerCAM SVG** produces all black lines (`stroke="black"`). Like this:

```xml
<g lc:layername="xxx" lc:is_locked="false" lc:is_construction="false" fill="none" stroke="black" stroke-width="1">
```

The lines are originally several different colors.

Maybe this is a limitation of MakerCAM (which I know nothing about). But there is no other **SVG** export than that.


Is 2.2 RC stable enough to be used?

**Comment by lordofbikes** [comment]
This fix is only in master branch, not in 2.3.1.
But the master is as stable as 2.3.1, so you can use nightly builds from our SourceForge downloads when you are on Windows or Mac.

**Comment by liufeijin** [comment]
Yes when i use the newest version , i found it is ok. so i close it.

**Comment by lordofbikes** [comment]
@liufeijin of course, my last post was to answer @aslze :grin:
