### ISSUE TITLE
Reverse operation to explode?

### ISSUE THREAD

**Issue by Harvie** [LibreCAD/LibreCAD#1235]
Hello, i create rectangle, fillet the corners and i do offset. it is done correctly (all offset segments are correctly inside or outside the rectangle). But when i explode it, the offset is done for individual segments instead (some inside, some outside). Is there way to join exploded shape back to single object?

Before exploding:
![image](https://user-images.githubusercontent.com/276504/83386301-1bf67480-a3eb-11ea-967d-d1ac31087e60.png)

After exploding:
![image](https://user-images.githubusercontent.com/276504/83386272-0da85880-a3eb-11ea-83dd-f49a1f2bc04d.png)

Let's say i dont start with rectangle at all and i want to join individual segments to single loop and then do the correct offset on it.

**Comment by fa201** [comment]
No the *join* feature is not implemented.

**Comment by lordofbikes** [comment]
In LibreCAD _JOIN_ is called _Create Polyline from Existing Segments_.
Find it in the Tools -> Polyline menu or Polyline tool bar
![Join](https://user-images.githubusercontent.com/386273/83420212-95f81f00-a426-11ea-9720-cf17fca38857.png)

This works only for lines and arcs.
An alternative is to create a block, therefore use the block list:
Select all entities and click _Create Block_

**Comment by fa201** [comment]
Sorry I was unclear. You can create polyline as said by @lordofbikes but you cannot group entities (as in Office programs or other CAD software) whether they are not lines/arcs or whether they do not intersect.
So you cannot make sub-assemblies apart from blocks and polylines.

**Comment by Harvie** [comment]
@DuncanLithgow Hello, why this was closed? Have you managed to solve the issue?

**Comment by DuncanLithgow** [comment]
@fa201 and @lordofbikes might of course correct me, but as far as I can tell reading this thread the software is working as expected. You can create a block or a polyline. If you'd like to describe a feature request maybe this issue could be reopened as a feature request.

**Comment by fa201** [comment]
If it is a feature request for group entities into one set which is not a block then it is already requested. [#1129 ](https://github.com/LibreCAD/LibreCAD/issues/1129)
