### ISSUE TITLE
Document introduction in lff font format

### ISSUE THREAD

**Issue by lianzaozi** [LibreCAD/LibreCAD#1238]
Are there any documents in lff format? I want to understand this format, but I can't find relevant information.

**Comment by lordofbikes** [comment]
There is not much magic in LFF format.
Find a single line description in https://github.com/LibreCAD/LibreCAD/issues/1252#issuecomment-650177740, see first line in section **Interesting trick**. The trick also explains how to paste the letter coordinates to LibreCAD command line to visualize letters.

LFF is pure ASCII, inspecting any file and looking at the less than 400 code lines of [tools/ttf2lff/main.cpp](https://github.com/LibreCAD/LibreCAD/blob/master/tools/ttf2lff/main.cpp) should be a good base to understand the format.

**Comment by app4soft** [comment]
Here is wiki with LFF font spec:

- https://github.com/LibreCAD/LibreCAD/wiki/LFF-Font-Format
