### ISSUE TITLE
Support for DWG format

### ISSUE THREAD

**Issue by SimplestStudio** [LibreCAD/LibreCAD#1239]
Hi!
Please support the DWG format. There is a "open DWG" tab, but the function doesn't actually work.

**Comment by liufeijin** [comment]
It will be crashed when i open DWG file.

**Comment by XVilka** [comment]
See https://github.com/LibreCAD/LibreCAD/issues/1055

**Comment by Helg1980** [comment]
... it is clear that nothing is clear...

**Comment by bzuillsmith** [comment]
The program crashed for me on Windows 10 when attempting to open a DWG. No error message.

**Comment by DuncanLithgow** [comment]
related to https://github.com/LibreCAD/LibreCAD_3/issues/207 on LibreCAD3

**Comment by fr4ncks** [comment]
Hi, I send this message to propose a solution, unfortunately not with
libreCAD, but to convert to DXF before opening, there is a soft (free for
non commercial use)from open design alliance that allows you to convert
files from DWG, it works perfect for me, even if it's not the right
solution (fun fact : I use it when AutoCAD refuse to register in DXF)

Le lun. 28 déc. 2020 à 13:20, Duncan Lithgow <notifications@github.com> a
écrit :

**Comment by DuncanLithgow** [comment]
@fr4ncks this has been the approach of FreeCAD for a while. It works. But it cannot be bundled it must be downloaded manually. It is gratis, but only for as long as ODA wants it to be that way. As with Draftsight, Sketchup and now Fusion360 that can change at any time from gratis to purchase only.

**Comment by lordofbikes** [comment]
No examples here, so no useful information for the issue.
The issue matches best with #988 and is tracked now there.
