### ISSUE TITLE
The program's appearance

### ISSUE THREAD

**Issue by SimplestStudio** [LibreCAD/LibreCAD#1240]
Let's make the program look like in ZWCAD (screenshot attached). With this look, you really want to do work.
![Screenshot_20200531_053633](https://user-images.githubusercontent.com/59513179/83677873-1fe9e880-a5dd-11ea-8d5e-61d2224cfec5.png)

**Comment by DuncanLithgow** [comment]
Please reopen this bug if you have specific suggestions for UI improvements.
