### ISSUE TITLE
LibreCAD crashed on opening DXF from file browser or CLI

### ISSUE THREAD

**Issue by Symbian9** [LibreCAD/LibreCAD#1250]
### Expected behavior

LibreCAD should not crash on opening broken or unsupported files.

### Observed behavior

LibreCAD crashed with segmentation fault on opening sample DXF files.

### Steps to reproduce or sample file

- Sample DXF files: https://github.com/michalolejejek/Arduino-schematic-patterns-in-LibreCAD

If try to open sample DXF files from file browser via *"Open with... > LibreCAD"*:

Also it crashed on opening those files from CLI:

```Shell
user@user:~/Downloads
$ librecad ./micro.dxf
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout
QG_LayerWidget::update: nullptr lastLayer
Segmentation fault
user@user:~/Downloads
$ librecad ./arduinouno.dxf
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout
QG_LayerWidget::update: nullptr lastLayer
Segmentation fault
```

But in same time its possible to open those files inside LibreCAD without crash:

![pic.1](https://i.imgur.com/n9nQlPE.png)

Terminal log on opening files inside LibreCAD:

```Shell
$ librecad
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout
QG_LayerWidget::update: nullptr lastLayer
QG_LayerWidget::activateLayer: invalid layer or nullptr layerView
QG_LayerWidget::activateLayer: invalid layer or nullptr layerView
QG_LayerWidget::activateLayer: invalid layer or nullptr layerView
QG_LayerWidget::activateLayer: invalid layer or nullptr layerView
```

### Operating System and LibreCAD version info

- Version: `2.2.0-alpha` (git: https://github.com/LibreCAD/LibreCAD/commit/38c3f94b58cad366ae39532411896f7d604049b2 )
- OS: Debian 10 buster (amd64)

**Comment by lordofbikes** [comment]
This was caused by merging pull request #1233.
And fixed next day with commit 4bfe117.
Please look at #1233 discussion if interested in more details.
Sorry for this inconvenience.
