### ISSUE TITLE
Read dwg file crash, code:tmpByteStr.resize(size) 

### ISSUE THREAD

**Issue by zhengf312** [LibreCAD/LibreCAD#1254]
### Observed behavior
tmpByteStr.resize(size)  crash; //line  327 in dwgreader.cpp,  parse text styles, start with style Control 

I found the 'size' value is 545541636;
then, resize the large vector 'tmpByteStr', program crash.

### Operating System and LibreCAD version info
OS：win64  8GB 
LibreCAD ： 2.2.0

**Comment by roncolat** [comment]
Hi! I tried to open a dwg files almost 15'400 kb in size. The result is that LibreCAD 2.2.0 is closing w/o any message.

**Comment by lordofbikes** [comment]
This issue is further tracked in #988
