### ISSUE TITLE
Why doesn't LibreCAD parse the OLE2FRAME entity in the dxf specification?

### ISSUE THREAD

**Issue by JasonStepan** [LibreCAD/LibreCAD#1260]

**Comment by lordofbikes** [comment]
Because nobody has implemented it yet.

**Comment by JasonStepan** [comment]
> Because nobody has implemented it yet.

Does anyone intend to implement this function?

**Comment by makuto** [comment]
I know this is a very old issue, but I have a tiny bit of information on OLE2FRAME 310 section written [here](https://macoy.me/blog/programming/DXFFormat).
