### ISSUE TITLE
Unable to process 3D DWG/DXF

### ISSUE THREAD

**Issue by Moult** [LibreCAD/LibreCAD#1267]
### Expected behavior

Opening a DWG/DXF with 3D data will show me the points and lines in 3D

### Observed behavior

No 3D functionality in LibreCAD.

### Operating System and LibreCAD version info

Version: 2.1.3
Compiler: GNU GCC 9.2.0
Compiled on: Jul 25 2020
Qt Version: 5.14.2
Boost Version: 1.72.0
System: Gentoo/Linux

**Comment by lordofbikes** [comment]
https://github.com/LibreCAD/LibreCAD/blob/master/README.md

**Comment by Moult** [comment]
OK :(
