### ISSUE TITLE
Impossible Condition 

### ISSUE THREAD

**Issue by maddin200** [LibreCAD/LibreCAD#1282]
[librecad/src/ui/forms/qg_polylineequidistantoptions.cpp line 116

void QG_PolylineEquidistantOptions::updateNumber() {
	if (action) {
		const QString& l = ui->leNumber->text();
		bool ok;
		unsigned i=static_cast<unsigned>(RS_Math::eval(l,&ok)+0.5);
		if (!ok || (i==0 && i>100))   // <-- impossible
			i=1;
		ui->leNumber->setText(QString::number(i));
		action->setNumber(i);
	}
}

**Comment by DuncanLithgow** [comment]
Could you maybe explain a bit what this bug report is about?

**Comment by maddin200** [comment]
Hi, 
The variable i can't be  == 0 and at the same time > 100  ( (i == 0) && (i >100) ); might be logical or  required

**Comment by fa201** [comment]
@lordofbikes  Can you  check if this condition correction can be implemented in next release ? Thanks.

**Comment by lordofbikes** [comment]
I wonder, how you found this, it should have been detected by static analysis.
Many thanks and great praise.
For curiosity's sake I looked for the source of this issue and I found it back in the first commit 2012, seems to be original QCAD code.
