### ISSUE TITLE
Trim Function Stops Working

### ISSUE THREAD

**Issue by LibreLahoo** [LibreCAD/LibreCAD#1296]
When I am editing a drawing, the trim function will randomly not work.  I will not be able to select a line.  The command line says it was selected, but it does not highlight and trim will not work.  I also can't select lines at all sometimes.  I have tried re-installing the software, but the problem recurs.

**Comment by fa201** [comment]
More information is required.
Can you go to **Help/About** and click on **Copy** and then paste the result here ?

**Comment by LibreLahoo** [comment]
It seems to have started working now.
