### ISSUE TITLE
all text displays as boxes

### ISSUE THREAD

**Issue by karlp** [LibreCAD/LibreCAD#1300]
### Expected behavior
* opening a dxf with text should display the text
* adding text should make the text visible

### Observed behavior
all text, even dimensions are just outline boxes (see images)
if I drag some text around sometimes it shows the text, but mostly just as outline boxes.
Print preview DOES correctly show the text, and if I edit text, the correct text is there, it's just crazy hard to work like that :)

### Steps to reproduce or sample file
sample file and images attached
[face-place-mods.zip](https://github.com/LibreCAD/LibreCAD/files/5784293/face-place-mods.zip)
![librecad22-dragging-text](https://user-images.githubusercontent.com/127907/103952846-fd9ee700-5138-11eb-92d2-25634cf105c7.png)
![librecad22-printpreview](https://user-images.githubusercontent.com/127907/103952844-fd065080-5138-11eb-8ec5-ee54b2d17986.png)

### Operating System and LibreCAD version info

fedora 32 on x86_64
versions: LibreCAD-2.2.0-rc2 built from source
also librecad-2.2.0-0.5.rc1.fc32.src.rpm the packaged version.

**Comment by fa201** [comment]
If draft mode is on (it looks it on) then it is not a bug. Try CTRL+D and check again.

**Comment by lordofbikes** [comment]
Indeed, draft mode is on
![grafik](https://user-images.githubusercontent.com/386273/103988005-a8d98b80-518d-11eb-9bac-2b91fbec7eb9.png)
https://forum.librecad.org/only-empty-boxes-frames-are-shown-for-image-text-no-line-thickness-td5706737.html

**Comment by karlp** [comment]
Might I suggest that draft mode on being the default setting should be revisited?  The out of box experience here is, unfriendly, to say the least.

**Comment by lordofbikes** [comment]
I'm not sure if draft mode is on with fresh installation, have to check this.
Anyhow, I link this issue to #1236, maybe we can kill two birds with one stone then.
