### ISSUE TITLE
Status bar dimensioning: text is not properly vertically aligned

### ISSUE THREAD

**Issue by fa201** [LibreCAD/LibreCAD#1304]
### Expected behavior
When redimensioning the status bar and the text in the status bar, the vertical centering should be kept.

### Observed behavior
When redimensioning the status bar through Options/Widget options/Status bar, there is more padding (in HTML sense) on the top than on the bottom.
Size changed from 32 to 30. Test changed from 11 to 8.
![image](https://user-images.githubusercontent.com/49532187/104124479-6365bb80-5351-11eb-99d9-ad971f230a88.png)

But changing the size of status bar to 40 with the same text height does not show the problem !
![image](https://user-images.githubusercontent.com/49532187/104124515-96a84a80-5351-11eb-8f1a-970ee0ef8ae5.png)

### Operating System and LibreCAD version info
Version: 2.2.0-rc2
Compiler: GNU GCC 7.5.0
Compiled on: Jan 10 2021
Qt Version: 5.9.5
Boost Version: 1.65.1
System: Ubuntu 18.04.5 LTS

**Comment by lordofbikes** [comment]
This is directly related to #1026 and should be solved with a status bar formatting revamp

**Comment by melwyncarlo** [comment]
Also related to #1010, I believe.

Mouse widget problem solved.

**Comment by lordofbikes** [comment]
fixed with eb0223968761df405c16a4885fff36c2fd05e9d1
