### ISSUE TITLE
Update the program version in the Ubuntu Software Center

### ISSUE THREAD

**Issue by Ubuntu-2020** [LibreCAD/LibreCAD#1311]
LibreCAD **2.0.9** is currently available for installation in **Ubuntu Software Center**.
But version **2.0.9** was released in **2016**. If possible, please update the program to version **2.1.3** or **2.2.0** (when it becomes stable).

P.S.: I checked in **Ubuntu 16.04**.

**Comment by lordofbikes** [comment]
Duplicate of #894
There is all said in #894, sadly there are no news, still no AppImage and still no maintainer for PPAs.
For 16.04 is at least a 2.1.1 package in the daily PPA.
