### ISSUE TITLE
Appearance of LibreCAD vs AutoCAD

### ISSUE THREAD

**Issue by Ubuntu-2020** [LibreCAD/LibreCAD#1318]
Probably the most popular CAD program is **AutoCAD**.
So why not change the LibreCAD interface so that it becomes exactly the same as in AutoCAD?
![autocad-lt-2017-elevations](https://user-images.githubusercontent.com/65112331/106387948-e2945f80-63e4-11eb-885f-cbc20298dd9d.png)

Of course first of all this concerns the **ribbon**.
It seems to me that if LibreCAD has exactly the same interface as AutoCAD, it will attract the attention of people and more users will use LibreCAD.
![AutoCAD Blockstream-2021 1-Red-border](https://user-images.githubusercontent.com/65112331/106387965-ffc92e00-63e4-11eb-91fb-1fc1959c6ccb.png)

Of course, redoing the interface and appearance will not solve the internal errors of LibreCAD. But over time, you can fix the errors.

In addition, if LibreCAD has exactly the same interface as AutoCAD, it will help users quickly learn how to work in it. After all, there are a lot of training videos for AutoCAD in the Internet and especially on YouTube. And LibreCAD has fewer training videos :-(
In addition, if LibreCAD has exactly the same interface as AutoCAD, it will help users who do not have the money to buy AutoCAD decide to use LibreCAD. 
Of course, it's not up to me to decide what LibreCAD's interface should be. Therefore, I ask you to attach the poll (voting) to this issue. Let users vote on what they would like to see the interface of LibreCAD.

**Comment by DuncanLithgow** [comment]
hi @Ubuntu-2020 I think the best place for this discussion is on the forum. Probably the LibreCAD3 part of the forum unless you think it would be worth changing the LibreCAD2 interface so much.
https://forum.librecad.org/LibreCAD-3-Development-discussion-f5709795.html
You can reopen this thread with a link to any discussion you start.

(for what it's worth I agree that the AutoCAD interface is a good one to be inspired by for many reasons - let's take that one on the forum)
