### ISSUE TITLE
Lost Dimension 

### ISSUE THREAD

**Issue by stefan2021** [LibreCAD/LibreCAD#1321]
I lost dimension information from a complex project. 
I test around and could not solve the problem. 
In invest a lot of time. Does somebody has a tipp for me?
best regards from munich, 
Stefan

**Comment by dellus** [comment]
For a help request like this the LibreCAD forum is a better place.
What means dimension information? The whole dimension drawing, or the dimension text?
More details please, or screen snapshot or a sample file.

**Comment by DuncanLithgow** [comment]
Yes, please ask for help on the forum. Reopen this report if the discussion suggests that it actually is a bug.
