### ISSUE TITLE
Auto backup file created when auto backup is disabled

### ISSUE THREAD

**Issue by cinderblock** [LibreCAD/LibreCAD#1351]
### Steps to reproduce

1. Disable "Auto Backup"
  ![image](https://user-images.githubusercontent.com/419955/119207517-58374080-ba53-11eb-8a4c-cff5f6f0d972.png)
2. Open a file
3. Make a change (or make the program think something has changed by making a change and then undoing it)
4. Save the file

### Observed behavior

A "backup" file (same name and path with `~` appended) is created.

### Expected behavior

No extra files created.

The documentation says that disabling "Auto Backup" will prevent LibreCAD from creating backup files.
https://librecad.readthedocs.io/en/latest/getstart/configure.html#program-defaults

### Operating System and LibreCAD version info
Version: 2.1.3
Compiler: GNU GCC 4.9.1
Compiled on: Sep 23 2016
Qt Version: 5.4.1
Boost Version: 1.60.0
System: Windows 10 x64

**Comment by fa201** [comment]
It is confirmed on last build also:
Version: 2.2.0-rc2-15-g76828565
Compiler: GNU GCC 7.5.0
Compiled on: Apr 17 2021
Qt Version: 5.12.8
Boost Version: 1.65.1
System: Ubuntu 20.04.2 LTS
