### ISSUE TITLE
"Multiple Copies" in "Move/Copy" should be considered as one action and be cancled by one ctrl-z

### ISSUE THREAD

**Issue by WhymustIhaveaname** [LibreCAD/LibreCAD#1357]
### Expected behavior, Observed behavior and Steps to reproduce

Multiple Copy anything, for example, 40 copies. Then using ctrl-z to cancel this action. Intuitively, this is one action so one ctrl-z is enough. Actually, I have to use 40 ctrl-z's to cancel it. I can understand reusing the function of "Keep Original" mode in "Move/Copy" many times to realize "Multiple Copy". However, not modifying histories is irresponsible.

### Operating System and LibreCAD version info

```
Fedora 33 (Workstation Edition)
```

```
Version: 2.2.0-alpha
Compiler: GNU GCC 10.2.1
Compiled on: Jul 28 2020
Qt Version: 5.15.2
Boost Version: 1.73.0
System: Fedora 33 (Workstation Edition)
```

**Comment by lordofbikes** [comment]
Fixed in latest code

**Comment by WhymustIhaveaname** [comment]
Oh, thanks.
