### ISSUE TITLE
Measurement issue meters unit

### ISSUE THREAD

**Issue by ccarlo88** [LibreCAD/LibreCAD#1360]
### Expected behavior
1- When I set the environment to meter unit, I expect the measurement in meter.
2- When I save the General Scale, from Drawing Preferences menu, next time I open up the original value is back to 0.001.

### Observed behavior
For me it's a little bit strange the default values from the Drawing Preferences->Dimensions menu.
(Environment set to meters)
1- If I write a simple 2 points line e.g.: (0,0) to (0,7), when I measure it, it shows 0.0070 because the default length factor is set to 0.001. I believe it should have the default as 1 to prevent confusion and match the desired scale (meters, millimeters, etc.). In fact, I don't even know if someone really use this feature in a scale different than the original one.
2- Probably the General Scale could also match the system unit for new drawing, e.g.: meters = 100, so the person can see the arrow/values when making a measurement.

### Steps to reproduce or sample file
Any new file from a fresh system configured for meter.

### Operating System and LibreCAD version info
Windows 10 19042.1083 - LibreCAD 2.2.0.0-rc2

**Comment by fa201** [comment]
I cannot reproduce this.
I set the units in both **Application preferences** and **Current drawing preferences**. When I measure, I get 7.0 and when I draw a dimension it shows 7 either.
**General scale** is still set to 1 (I did not change it).
