### ISSUE TITLE
Option to disable the Reference Line

### ISSUE THREAD

**Issue by jcbeppler** [LibreCAD/LibreCAD#1361]
Hello,

I couldn't find this option in the documentation but I think would be nice to have an option to disable the reference lines. Personally my eyes don't like it as they are quite "shinny".
![image](https://user-images.githubusercontent.com/59994318/125206295-db705800-e286-11eb-81b6-2c53149d31ab.png)

**Comment by lordofbikes** [comment]
https://librecad.readthedocs.io/en/latest/getstart/configure.html?highlight=crosshair#appearance
uncheck **Snap indicator lines**
