### ISSUE TITLE
Suggestion of feature for the 2-points line behavior

### ISSUE THREAD

**Issue by jcbeppler** [LibreCAD/LibreCAD#1362]
Hello,

One very useful functionality for the 2-points line is the following one:
For the first point, everything is the same as it is today, either by mouse or by specifying the coordinate.
For the second point, it could accept a single number which represents the size you want and it would draw the line with that size in the same direction where the mouse/snap is on the grid.

This functionality is really useful and makes drawing lines way faster.

**Comment by lordofbikes** [comment]
duplicate of #1210
