### ISSUE TITLE
Allow "Application Preferences" when no document is open

### ISSUE THREAD

**Issue by MarcelloTheArcane** [LibreCAD/LibreCAD#1369]
### Expected behavior

I would like to be able to view and edit the application preferences, even if no document is open.

### Observed behavior

Currently the `Application Preferences` option is greyed out if no document is open.

![image](https://user-images.githubusercontent.com/21159570/127870130-1422daa5-2e6b-462a-80e2-1cfeb8e593af.png)

### Steps to reproduce or sample file

1. Open LibreCAD
2. Go to `Options`
3. Observe that `Application Preferences` is disabled

### Operating System and LibreCAD version info

Version: 2.2.0-rc2
Compiler: GNU GCC 7.3.0
Compiled on: Dec 31 2020
Qt Version: 5.12.4
Boost Version: 1.65.1
System: Windows 10 (10.0)

**Comment by melwyncarlo** [comment]
Just the `Application Preferences` option?
