### ISSUE TITLE
LibreCAD - hangs when zoomed

### ISSUE THREAD

**Issue by 0nly1job** [LibreCAD/LibreCAD#1380]
Hi, after many attempts to continue the task I am handing the issue over.

operation:_Drawing vertical construction lines on layer (#0021) of 9 layers - application hanging as scroll to right to draw 4th line(dot dash) on zoom view

Version: 2.1.3
Compiler: Clang 8.0.0
Compiled on: Sep 22 2016
Qt Version: 5.6.1
Boost Version: 1.60.0

please see below Mac error report for crash. (LibreCad data only)

I have saved 2 similar reports just in case ... after many.
---------------------------------

Date/Time:        2021-09-13 08:21:54.907 +1000
End time:         2021-09-13 08:30:07.466 +1000
OS Version:       macOS 11.5.2 (Build 20G95)
Architecture:     x86_64h
Report Version:   32

Data Source:      Stackshots
Shared Cache:     0C9EB0DE-F5CE-3AFC-8F08-0C6DB1E7FC44 slid base address 0x7fff20216000, slide 0x216000

Command:          LibreCAD
Path:             /Volumes/VOLUME/*/LibreCAD.app/Contents/MacOS/LibreCAD
Identifier:       com.yourcompany.LibreCAD
Version:          ??? (???)
Parent:           launchd [1]
PID:              744
Time Since Fork:  768s

Event:            hang
Duration:         492.56s
Duration Sampled: 1.10s (process was unresponsive for 492 seconds before sampling)
Steps:            11 (100ms sampling interval)

Hardware model:   MacBookPro16,1
Active cpus:      16
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 1284s
Time Since Wake:  n/a (machine hasn't slept)

Fan speed:        2398 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  11  start + 52 (LibreCAD + 18228) [0x1005c9734]
  11  main + 7866 (LibreCAD + 3523498) [0x1009213aa]
  11  QCoreApplication::exec() + 341 (QtCore + 1983893) [0x101d37595]
  11  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401 (QtCore + 1966833) [0x101d332f1]
  11  ??? (libqcocoa.dylib + 143391) [0x10417c01f]
  11  -[NSApplication run] + 586 (AppKit + 195689) [0x7fff22e13c69]
  11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364 (AppKit + 252229) [0x7fff22e21945]
  11  _DPSNextEvent + 864 (AppKit + 258418) [0x7fff22e23172]
  11  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 198019) [0x7fff28861583]
  11  ReceiveNextEventCommon + 284 (HIToolbox + 198326) [0x7fff288616b6]
  11  RunCurrentEventLoopInMode + 292 (HIToolbox + 199299) [0x7fff28861a83]
  11  CFRunLoopRunSpecific + 563 (CoreFoundation + 521756) [0x7fff2061b61c]
  11  __CFRunLoopRun + 893 (CoreFoundation + 524380) [0x7fff2061c05c]
  11  __CFRunLoopDoSources0 + 242 (CoreFoundation + 529972) [0x7fff2061d634]
  11  __CFRunLoopDoSource0 + 180 (CoreFoundation + 530612) [0x7fff2061d8b4]
  11  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 530764) [0x7fff2061d94c]
  11  ??? (libqcocoa.dylib + 147745) [0x10417d121]
  11  ??? (libqcocoa.dylib + 145486) [0x10417c84e]
  11  QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 596 (QtCore + 1985348) [0x101d37b44]
  11  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164 (QtCore + 1982244) [0x101d36f24]
  11  QApplication::notify(QObject*, QEvent*) + 5941 (QtWidgets + 84357) [0x100f40985]
  11  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294 (QtWidgets + 73414) [0x100f3dec6]
  11  QMainWindow::event(QEvent*) + 1660 (QtWidgets + 1448700) [0x10108dafc]
  11  QWidget::event(QEvent*) + 2685 (QtWidgets + 340509) [0x100f7f21d]
  11  ??? (QtWidgets + 130049) [0x100f4bc01]
  11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3]
  11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118]
  11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3]
  11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118]
  11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3]
  11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118]
  11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3]
  11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118]
  11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3]
  11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118]
  11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3412 (QtWidgets + 313668) [0x100f78944]
  11  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164 (QtCore + 1982244) [0x101d36f24]
  11  QApplication::notify(QObject*, QEvent*) + 5941 (QtWidgets + 84357) [0x100f40985]
  11  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294 (QtWidgets + 73414) [0x100f3dec6]
  11  QG_GraphicView::event(QEvent*) + 132 (LibreCAD + 2288676) [0x1007f3c24]
  11  QWidget::event(QEvent*) + 2129 (QtWidgets + 339953) [0x100f7eff1]
  11  QG_GraphicView::paintEvent(QPaintEvent*) + 524 (LibreCAD + 2294684) [0x1007f539c]
  11  RS_GraphicView::drawLayer2(RS_Painter*) + 26 (LibreCAD + 1139866) [0x1006db49a]
  11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*) + 29 (LibreCAD + 1141261) [0x1006dba0d]
  11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*, double&) + 1216 (LibreCAD + 1142496) [0x1006dbee0]
  11  RS_EntityContainer::draw(RS_Painter*, RS_GraphicView*, double&) + 213 (LibreCAD + 319557) [0x100613045]
  11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*) + 29 (LibreCAD + 1141261) [0x1006dba0d]
  11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*, double&) + 1216 (LibreCAD + 1142496) [0x1006dbee0]
  10  RS_Line::draw(RS_Painter*, RS_GraphicView*, double&) + 2883 (LibreCAD + 442451) [0x100631053]
  8   RS_PainterQt::drawLine(RS_Vector const&, RS_Vector const&) + 122 (LibreCAD + 1170266) [0x1006e2b5a]
  5   QRasterPaintEngine::drawLines(QLine const*, int) + 457 (QtGui + 2488473) [0x1017e7899]
  4   ??? (QtGui + 2115094) [0x10178c616]
  1   ??? (QtGui + 2121953) [0x10178e0e1]

Process:          LibreCAD [744]
UUID:             42C2CC52-FA4B-35B8-823A-C63DB97528EF
Path:             /Volumes/VOLUME/*/LibreCAD.app/Contents/MacOS/LibreCAD
Architecture:     x86_64
Parent:           launchd [1]
UID:              501
Footprint:        201.54 MB
Time Since Fork:  768s
Num samples:      11 (1-11)
CPU Time:         0.999s (4.3G cycles, 12.0G instructions, 0.36c/i)
Note:             Unresponsive for 492 seconds before sampling
Note:             1 idle work queue thread omitted

  Thread 0x2815    DispatchQueue "com.apple.main-thread"(1)    11 samples (1-11)    priority 47 (base 47)    cpu time 0.999s (4.3G cycles, 12.0G instructions, 0.36c/i)
  <process frontmost, thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [135], IO tier 0>
  11  start + 52 (LibreCAD + 18228) [0x1005c9734] 1-11
    11  main + 7866 (LibreCAD + 3523498) [0x1009213aa] 1-11
      11  QCoreApplication::exec() + 341 (QtCore + 1983893) [0x101d37595] 1-11
        11  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401 (QtCore + 1966833) [0x101d332f1] 1-11
          11  ??? (libqcocoa.dylib + 143391) [0x10417c01f] 1-11
            11  -[NSApplication run] + 586 (AppKit + 195689) [0x7fff22e13c69] 1-11
              11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364 (AppKit + 252229) [0x7fff22e21945] 1-11
                11  _DPSNextEvent + 864 (AppKit + 258418) [0x7fff22e23172] 1-11
                  11  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 198019) [0x7fff28861583] 1-11
                    11  ReceiveNextEventCommon + 284 (HIToolbox + 198326) [0x7fff288616b6] 1-11
                      11  RunCurrentEventLoopInMode + 292 (HIToolbox + 199299) [0x7fff28861a83] 1-11
                        11  CFRunLoopRunSpecific + 563 (CoreFoundation + 521756) [0x7fff2061b61c] 1-11
                          11  __CFRunLoopRun + 893 (CoreFoundation + 524380) [0x7fff2061c05c] 1-11
                            11  __CFRunLoopDoSources0 + 242 (CoreFoundation + 529972) [0x7fff2061d634] 1-11
                              11  __CFRunLoopDoSource0 + 180 (CoreFoundation + 530612) [0x7fff2061d8b4] 1-11
                                11  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 530764) [0x7fff2061d94c] 1-11
                                  11  ??? (libqcocoa.dylib + 147745) [0x10417d121] 1-11
                                    11  ??? (libqcocoa.dylib + 145486) [0x10417c84e] 1-11
                                      11  QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 596 (QtCore + 1985348) [0x101d37b44] 1-11
                                        11  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164 (QtCore + 1982244) [0x101d36f24] 1-11
                                          11  QApplication::notify(QObject*, QEvent*) + 5941 (QtWidgets + 84357) [0x100f40985] 1-11
                                            11  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294 (QtWidgets + 73414) [0x100f3dec6] 1-11
                                              11  QMainWindow::event(QEvent*) + 1660 (QtWidgets + 1448700) [0x10108dafc] 1-11
                                                11  QWidget::event(QEvent*) + 2685 (QtWidgets + 340509) [0x100f7f21d] 1-11
                                                  11  ??? (QtWidgets + 130049) [0x100f4bc01] 1-11
                                                    11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3] 1-11
                                                      11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118] 1-11
                                                        11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3] 1-11
                                                          11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118] 1-11
                                                            11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3] 1-11
                                                              11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118] 1-11
                                                                11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3] 1-11
                                                                  11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118] 1-11
                                                                    11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4083 (QtWidgets + 314339) [0x100f78be3] 1-11
                                                                      11  QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1192 (QtWidgets + 315672) [0x100f79118] 1-11
                                                                        11  QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3412 (QtWidgets + 313668) [0x100f78944] 1-11
                                                                          11  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164 (QtCore + 1982244) [0x101d36f24] 1-11
                                                                            11  QApplication::notify(QObject*, QEvent*) + 5941 (QtWidgets + 84357) [0x100f40985] 1-11
                                                                              11  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294 (QtWidgets + 73414) [0x100f3dec6] 1-11
                                                                                11  QG_GraphicView::event(QEvent*) + 132 (LibreCAD + 2288676) [0x1007f3c24] 1-11
                                                                                  11  QWidget::event(QEvent*) + 2129 (QtWidgets + 339953) [0x100f7eff1] 1-11
                                                                                    11  QG_GraphicView::paintEvent(QPaintEvent*) + 524 (LibreCAD + 2294684) [0x1007f539c] 1-11
                                                                                      11  RS_GraphicView::drawLayer2(RS_Painter*) + 26 (LibreCAD + 1139866) [0x1006db49a] 1-11
                                                                                        11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*) + 29 (LibreCAD + 1141261) [0x1006dba0d] 1-11
                                                                                          11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*, double&) + 1216 (LibreCAD + 1142496) [0x1006dbee0] 1-11
                                                                                            11  RS_EntityContainer::draw(RS_Painter*, RS_GraphicView*, double&) + 213 (LibreCAD + 319557) [0x100613045] 1-11
                                                                                              11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*) + 29 (LibreCAD + 1141261) [0x1006dba0d] 1-11
                                                                                                11  RS_GraphicView::drawEntity(RS_Painter*, RS_Entity*, double&) + 1216 (LibreCAD + 1142496) [0x1006dbee0] 1-11
                                                                                                  8   RS_Line::draw(RS_Painter*, RS_GraphicView*, double&) + 2883 (LibreCAD + 442451) [0x100631053] 1-8
                                                                                                    1   RS_PainterQt::drawLine(RS_Vector const&, RS_Vector const&) + 90 (LibreCAD + 1170234) [0x1006e2b3a] (running) 1
                                                                                                    3   RS_PainterQt::drawLine(RS_Vector const&, RS_Vector const&) + 122 (LibreCAD + 1170266) [0x1006e2b5a] 2-4
                                                                                                      1   QRasterPaintEngine::drawLines(QLine const*, int) + 490 (QtGui + 2488506) [0x1017e78ba] 2
                                                                                                        1   free + 13 (libsystem_malloc.dylib + 8034) [0x7fff2034bf62] (running) 2
                                                                                                      1   QRasterPaintEngine::drawLines(QLine const*, int) + 457 (QtGui + 2488473) [0x1017e7899] 3
                                                                                                        1   ??? (QtGui + 2115094) [0x10178c616] 3
                                                                                                          1   ??? (QtGui + 2120200) [0x10178da08] 3
                                                                                                            1   ??? (QtGui + 2114764) [0x10178c4cc] (running) 3
                                                                                                      1   DYLD-STUB$$free + 0 (QtGui + 4330432) [0x1019a93c0] (running) 4
                                                                                                    1   RS_PainterQt::drawLine(RS_Vector const&, RS_Vector const&) + 102 (LibreCAD + 1170246) [0x1006e2b46] (running) 5
                                                                                                    3   RS_PainterQt::drawLine(RS_Vector const&, RS_Vector const&) + 122 (LibreCAD + 1170266) [0x1006e2b5a] 6-8
                                                                                                      3   QRasterPaintEngine::drawLines(QLine const*, int) + 457 (QtGui + 2488473) [0x1017e7899] 6-8
                                                                                                        2   ??? (QtGui + 2115094) [0x10178c616] 6-7
                                                                                                          1   ??? (QtGui + 2120124) [0x10178d9bc] (running) 6
                                                                                                          1   ??? (QtGui + 2120195) [0x10178da03] (running) 7
                                                                                                        1   ??? (QtGui + 2114974) [0x10178c59e] 8
                                                                                                          1   QTransform::map(QPointF const&) const + 9 (QtGui + 2911593) [0x10184ed69] (running) 8
                                                                                                  1   RS_Line::draw(RS_Painter*, RS_GraphicView*, double&) + 2956 (LibreCAD + 442524) [0x10063109c] (running) 9
                                                                                                  2   RS_Line::draw(RS_Painter*, RS_GraphicView*, double&) + 2883 (LibreCAD + 442451) [0x100631053] 10-11
                                                                                                    2   RS_PainterQt::drawLine(RS_Vector const&, RS_Vector const&) + 122 (LibreCAD + 1170266) [0x1006e2b5a] 10-11
                                                                                                      1   QRasterPaintEngine::drawLines(QLine const*, int) + 69 (QtGui + 2488085) [0x1017e7715] 10
                                                                                                        1   ??? (QtGui + 2780164) [0x10182ec04] (running) 10
                                                                                                      1   QRasterPaintEngine::drawLines(QLine const*, int) + 457 (QtGui + 2488473) [0x1017e7899] 11
                                                                                                        1   ??? (QtGui + 2115094) [0x10178c616] 11
                                                                                                          1   ??? (QtGui + 2121953) [0x10178e0e1] (running) 11

  Thread 0x2857    Thread name "com.apple.NSEventThread"    11 samples (1-11)    priority 47 (base 47)
  <process frontmost, thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [135], IO tier 0>
  11  thread_start + 15 (libsystem_pthread.dylib + 9283) [0x7fff20520443] 1-11
    11  _pthread_start + 224 (libsystem_pthread.dylib + 26876) [0x7fff205248fc] 1-11
      11  _NSEventThread + 124 (AppKit + 1856058) [0x7fff22fa923a] 1-11
        11  CFRunLoopRunSpecific + 563 (CoreFoundation + 521756) [0x7fff2061b61c] 1-11
          11  __CFRunLoopRun + 1328 (CoreFoundation + 524815) [0x7fff2061c20f] 1-11
            11  __CFRunLoopServiceMachPort + 316 (CoreFoundation + 531247) [0x7fff2061db2f] 1-11
              11  mach_msg_trap + 10 (libsystem_kernel.dylib + 4794) [0x7fff204ef2ba] 1-11
               *11  ipc_mqueue_receive_continue + 0 (kernel + 389472) [0xffffff800026f160] 1-11

  Binary Images:
           0x1005c5000 -        0x100d8efff  com.yourcompany.LibreCAD                <42C2CC52-FA4B-35B8-823A-C63DB97528EF>  /Volumes/VOLUME/*/LibreCAD.app/Contents/MacOS/LibreCAD
           0x100f2c000 -        0x10147ffff  org.qt-project.QtWidgets 5.6 (5.6.1)    <1FA494AC-3288-34DB-8241-FA76AF36A10B>  /Volumes/VOLUME/*/LibreCAD.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
           0x101588000 -        0x101a8dfff  org.qt-project.QtGui 5.6 (5.6.1)        <2D9980BF-CEC6-360B-B5FB-76AA0C96DEAE>  /Volumes/VOLUME/*/LibreCAD.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
           0x101b53000 -        0x102097fff  org.qt-project.QtCore 5.6 (5.6.1)       <0C924425-3ED8-340C-83BF-F598B124ADE9>  /Volumes/VOLUME/*/LibreCAD.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
           0x104159000 -        0x1042aefff  libqcocoa.dylib (0)                     <F05B9FD2-F8C1-3B35-9956-E156DF5065AC>  /Volumes/VOLUME/*/LibreCAD.app/Contents/PlugIns/platforms/libqcocoa.dylib
        0x7fff2034a000 -     0x7fff20376fff  libsystem_malloc.dylib (317.140.5)      <0AEDABF0-CFF7-3304-9FF8-EB3BBF0801E6>  /usr/lib/system/libsystem_malloc.dylib
        0x7fff204ee000 -     0x7fff2051dfff  libsystem_kernel.dylib (7195.141.2)     <B51DEA59-1260-35C6-B7B6-AA6D8459ECEC>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff2051e000 -     0x7fff20529fff  libsystem_pthread.dylib (454.120.2)     <B1A74420-49E9-32FC-BFCB-E53550236A23>  /usr/lib/system/libsystem_pthread.dylib
        0x7fff2059c000 -     0x7fff20a39fff  com.apple.CoreFoundation 6.9 (1777.103) <08B48289-1C59-3259-8D49-F1FA51ED53D2>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
        0x7fff22de4000 -     0x7fff23b2ffff  com.apple.AppKit 6.9 (2022.60.128)      <8B44AAAB-01A1-30A2-9B1B-CBBBE6DFB82A>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
        0x7fff28831000 -     0x7fff28b2cfff  com.apple.HIToolbox 2.1.1 (1062)        <EC082CDB-4679-3C92-B100-5795FEB21F42>  /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
   *0xffffff8000210000 - 0xffffff8000c0ffff  kernel (7195.141.2)                     <FECBF22B-FBBE-36DE-9664-F12A7DD41D3D>  /System/Library/Kernels/kernel

**Comment by lordofbikes** [comment]
This is a known issue with construction lines and solved in latest code.

You can update to latest release candidate 2.2.0-rc2 which is safe to use.
Find it here https://github.com/LibreCAD/LibreCAD/releases/tag/2.2.0-rc2
or here https://sourceforge.net/projects/librecad/files/OSX/2.2/preRelease/

Take care that there is a special package for macOS Big Sur.
