### ISSUE TITLE
How to build in the Msvc32 and Msvc64  debuggers

### ISSUE THREAD

**Issue by xutingjie168** [LibreCAD/LibreCAD#1385]
Hi,
I can build MinGW32 in the QT5.9.0,but Msvc32 or Msvc64 is not Successful in the QT or VS ,LibreCAD How to build in the Msvc32 and Msvc64  debuggers?Thank you!

**Comment by lordofbikes** [comment]
There is currently no active developer working on Windows with MSVC environment.
Our Windows deployment works with MinGW too.
So when this works for you I recommend to stay in this environment.
