### ISSUE TITLE
Create real dash or dot patterns

### ISSUE THREAD

**Issue by olcc** [LibreCAD/LibreCAD#1387]
In LibreCad, I expect to be able to specify a dot or a dash pattern precisely, like "dots, 2 mm spaced", or "dashes, 2 mm long, 3 mm space", for lines, circles, or other shapes.

Currently, the distance between the dashes is related to the paper output. This is nice for some situations, because zooming will always show the same distance between dashes to the eye. But other situations would require dots or dashes to represent "physical" elements with defined lengths.

Olivier, with LibreCAD 2.1.3

**Comment by lordofbikes** [comment]
Closing this means only that this feature will not find it's way into V2, but maybe found in V3 in future.
When time comes, we'll transfer these V3 tagged feature to V3 repo, don't duplicate them on V3 yet, this will only produce more work for us.
