### ISSUE TITLE
Lots problems, need improve commands and keyboard input

### ISSUE THREAD

**Issue by drinkjava2** [LibreCAD/LibreCAD#1394]
1. no c, z, p, t commands
2. Can't customize keyboard shortkey
3. Can't customize command?
4. Some commands like object-snap not show on command line
5. No object-snap command
Looks like programer never used AutoCAD before

**Comment by lordofbikes** [comment]
Closing this means only that this feature will not find it's way into V2, but maybe found in V3 in future.
When time comes, we'll transfer these V3 tagged feature to V3 repo, don't duplicate them on V3 yet, this will only produce more work for us.
