### ISSUE TITLE
LibreCAD on sale by 3rd-party publisher in Microsoft Store

### ISSUE THREAD

**Issue by Symbian9** [LibreCAD/LibreCAD#1399]
> **ATTENTION!** Do NOT buy LibreCAD for Windows on Microsoft Store!

### Expected behavior

There should be no illegal distribution of LibreCAD in any software stores

### Observed behavior

LibreCAD in Microsoft Store is on sold by publisher `Alef_Soft` as paid software *"LibreCad 2"*:

- https://www.microsoft.com/en-us/p/librecad-2/9nllw7jq3j84
  - archived copy 1: https://web.archive.org/web/20211025181929/https://www.microsoft.com/en-us/p/librecad-2/9nllw7jq3j84
  - archived copy 2: https://archive.is/25S1b

In description on this page GPL licensing mentioned and "LibreCAD Team" is attributed as developer.

FTR, Earlier there was also on sold *"LibreCAD 2.2.0 User Manual"*, uploaded to MS Store by `Nam Studio` publisher, but now it seems removed:

- ~~https://www.microsoft.com/en-us/p/librecad-220-user-manual/9nmdxd5j4d9j~~

**NOTE:** Not only LibreCAD, but also FreeCAD, Scribus and many other software are on sold by various 'publishers' at Microsoft Store :/

- https://twitter.com/yorikvanhavre/status/1452710856341565441
- https://twitter.com/AcikKaynakci/status/1452713662804897797

**Comment by lordofbikes** [comment]
I haven't got a response from Microsoft about my copyright infringement yet, but all LibreCAD search results in Microsoft Store, which I checked yet, have 404 response. So it seems to be worth the effort.
Many thanks to all.

**Comment by Symbian9** [comment]
> but all LibreCAD search results in Microsoft Store, which I checked yet, have 404 response. So it seems to be worth the effort.

To be clear, only 'Alef_Soft's "LibreCad 2" is not available now, BUT all other 'Alef_Soft's and  'appsmedia1' "forks" still exists:

- ~~LibreCAD as _"LibreCad 2"_ by 'Alef_Soft': https://www.microsoft.com/en-us/store/p/librecad-2/9nllw7jq3j84~~
- BRL-CAD as _"BRL-CAD"_ by 'Alef_Soft‬': https://www.microsoft.com/en-us/store/p/brl-cad/9p6fk5sxdjlq
- FreeCAD as _"FreeCad for Windows"_ by 'appsmedia1': https://www.microsoft.com/en-us/p/freecad-for-windows/9p1c586k5wj7
- Lightscreen as _"ScreenShot Lightscreen"_ by 'Alef_Soft‬': https://www.microsoft.com/en-us/store/p/screenshot-lightscreen/9mt8sgnk291s
- Scribus as _"Scribus Indesign"_ (`sic!`) by 'Alef_Soft':https://www.microsoft.com/en-us/store/p/scribus-indesign/9nv1w2cmjz4z
- darktable as _"DarkTable LightRoom"_ (`sic!`) by 'Alef_Soft': https://www.microsoft.com/en-us/store/p/darktable-lightroom/9pb7bbt1pkvc

**Comment by lordofbikes** [comment]
I don't know which actions other maintainers took, if they did at all.
The copyright infringement needs to provide personal data and links to prove concerns, so I could file my request for LibreCAD only and that seems to have success.
