### ISSUE TITLE
True Apple M1 support

### ISSUE THREAD

**Issue by Olegt0rr** [LibreCAD/LibreCAD#1405]
As described in [release](https://github.com/LibreCAD/LibreCAD/releases/tag/2.2.0-rc2) latest (2.2.0-rc2) version has M1 support, but it's not true. 

The app successfully installed and launched, but via Rosetta (Intel)!
![Screenshot 2021-11-15 at 12 53 56](https://user-images.githubusercontent.com/25399456/141760799-089d8e81-b8ce-42ce-8672-d8ea37fc01fa.png)

**Comment by PeterHagen** [comment]
With the 2.2.0 release, there is no M1 version available unfortunatly

**Comment by lordofbikes** [comment]
M1 packages, which were generously provided by a community member, were reported as not running. Even when it turned out, that it's probably only a matter of signing, we stopped that to avoid further issues.
I close this in favor of #1548.

**Comment by PeterHagen** [comment]
> M1 packages, which were generously provided by a community member, were reported as not running. Even when it turned out, that it's probably only a matter of signing, we stopped that to avoid further issues.
> I close this in favor of #1548.

Yeah, that was me. The second one I provided did work, and I am actually still using it.

**Comment by lordofbikes** [comment]
Sorry @PeterHagen, I didn't link that together.
Because of the discussion in #1548 I didn't ask you for a 2.2.0 release package.
Maybe in the new year, please see my recent response in #1548.
