### ISSUE TITLE
Specify auto save time units

### ISSUE THREAD

**Issue by melwyncarlo** [LibreCAD/LibreCAD#1412]
**Location :**
`Menu Bar → Options → Application Preferences → Defaults → Program Defaults → Auto save time`

**LibreCAD version :**
Latest development version 2.2.0

<hr>

It would be better to specify the units of time. 
* One way would be to append ` (seconds)` to the label.
* Another way would be to add a combo-box with the options: seconds and minutes.

The first idea is simple and uniform.

**Comment by fa201** [comment]
KIS(S): keep it simple. :-)
