### ISSUE TITLE
Feature request: deselect all with the mouse

### ISSUE THREAD

**Issue by gerardbm** [LibreCAD/LibreCAD#1426]
Deselecting is a very frecuent task, and doing it with a mouse click is actually a time-saver. LibreCAD and AutoCAD have the key `Escape` for this task. Also, the shortcut `Ctrl+k` can be used.

**QCAD deselects everything with a left-button mouse click in the background.** Allplan does it with a right-button mouse click in the toolbars. The QCAD implementation feels smooth, close enough to the mouse pointer, getting a good and fast workflow.

**Comment by lordofbikes** [comment]
Closing this means only that this feature will not find it's way into V2, but maybe found in V3 in future.
When time comes, we'll transfer these V3 tagged feature to V3 repo, don't duplicate them on V3 yet, this will only produce more work for us.
