### ISSUE TITLE
Mark relative position coordinates in status bar with @ (small GUI improvment)

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1452]
It is confusing to see absolute and relative coordinates running side by side in the status bar, at first sight I'm always not sure what is what. Newbees often don't realize the meaning at all.
So what about just putting an "@" in front of the readings. Seems simple, so maybe ok to include in 2.2.0. 
As i can't insert an image here I have posted it in the forum at Suggestions & Feedback.

**Comment by fa201** [comment]
![relposition](https://user-images.githubusercontent.com/49532187/144923829-a0cdc8e0-278e-4826-a261-8aa147fae057.png)
@dellus Well the '<' is for relative but adding a '@' would make more clear in my opinion. At least it would not harm...

**Comment by dellus** [comment]
I know drag and drop should work, but it doesn't, whatever I try. Maybe it is because my old win xp, or the mypal browser.
I also know the '<' is for relative. I find it to look less confusing when visually grouped by the '@'s.

**Comment by melwyncarlo** [comment]
Based on the above image (hoping it's the result of relevant code changes), I'd say that this issue has already been solved?

**Comment by dellus** [comment]
Sorry, it's just the result of image manipulation.

**Comment by melwyncarlo** [comment]
Oh, okay. So, it's up for grabs!

**Comment by fa201** [comment]
My mistake. '<' means polar I was not in my mind...
![relative](https://user-images.githubusercontent.com/49532187/145114467-9d040a57-2da3-48db-82a0-3597ccee9702.png)
Indeed a relative icon or character is missing.
