### ISSUE TITLE
In Drawing Preferences - Dimensions - Fixed length change naming "units" to the actually used units like in the other fields

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1453]
Another tiny GUI improvement:
In Drawing Preferences - Dimensions - Fixed length the naming is "units" instead of the actually used units (mm, m, inches or whatever) like in the other according fields. This might induce the user to think something here works differently. 
This might have made some sense in V 2.1.3, as there the length did not submit to "General Scale". In 2.2.0 it does submit, so it behaves the same way as the other settings.
So why not also use the actual units naming?

All OS'es, V 12.1.3 and 2.2.0

**Comment by fa201** [comment]
![units](https://user-images.githubusercontent.com/49532187/144924551-9528d919-b259-4b97-a9b6-3e3a0b3d353d.png)
I agree

**Comment by melwyncarlo** [comment]
![Screenshot from 2021-12-07 11-30-50](https://user-images.githubusercontent.com/66683108/144975229-3aa50245-0bfa-4e81-bbf4-88c239bc86e3.png)
