### ISSUE TITLE
moving elements changes their layer

### ISSUE THREAD

**Issue by phu9Suop** [LibreCAD/LibreCAD#1513]
### Expected behaviour
When I move an element, a line, circle or a marked set of these, I expect that each item  retains its original property layer.

### Observed behaviour

I have a set of 6 layers, consisting each of three component variations and three measurement layers .
When I mark all of them and move these to another place, 
all change into the active layer, also only a coordinate transformation was required.

### Steps to reproduce or sample file
mark some elements which are visible, but not in the active layer. 
select Tools / Change / copying-moving (I have German menus, names may be different)
press Enter
define reference coordinate
select target coordinate
now marked components move to new coordinate and change layer to the active layer.

### Operating System and LibreCAD version info
Version 2.1.3, debian packaging

When copying elements of multiple layers, these shall also retain their original layer.

**Comment by jbergengh** [comment]
When you do your move/copy make sure "Use current layer" is NOT checked.
Let us know if that was the problem.

![move copy](https://user-images.githubusercontent.com/55407804/149555644-560ddabd-8f17-4fe4-9296-d93c248d57e8.png)
