### ISSUE TITLE
Toggling layer visibility scrolls layer list to active layer

### ISSUE THREAD

**Issue by michalg0x5a** [LibreCAD/LibreCAD#1515]
Currently layer list scrolls back to the bottom of the list (the active layer). In my opinion it would be better to leave the scroll position as-is. If a drawing contains large number of layers (twenty or more), than it is hard to explore the drawing, because if wrong layer was hidden, then the user needs to scroll back to its position in layer list and to toggle its visibility again. If the scroll position stayed as is, than it would be much quicker.

### Expected behavior
If layerwidget contains many layers (scroll bar is visible), then simple toggling of layer visibility shouldn't change the scroll position.

### Observed behavior
Toggling layer visibility (or lock, print, construction layer) resets the scroll position to the active layer. The behaviour is irritating especially for drawings containing large number of layers (e.g. maps) opened for exploration.

### Steps to reproduce or sample file
Steps to reproduce:
1. Add enough layers for layerwidget to show scroll bar.
2. Scroll to the bottom of the layer list.
3. Select (activate) last layer.
![obraz](https://user-images.githubusercontent.com/3610260/150419458-80f9aa2d-3184-4c8a-96fa-159bedd5a94c.png)
4. Scroll the list to first item.
![obraz](https://user-images.githubusercontent.com/3610260/150419773-14f65d35-3a21-4108-b9bc-b78b8384312c.png)
5. Toggle first item visibility (toggling lock, print and construction has the same effect).
![obraz](https://user-images.githubusercontent.com/3610260/150419839-a54d63f9-0a0d-4a1c-a10d-1a4fefa9a48d.png)

### Operating System and LibreCAD version info
Fedora Linux 35 (x86_64), LibreCAD commit 5d331c8bf51031f46989a5ce3350c59508505289 (almost certain that issue is also present in 2.2.0-rc3).

**Comment by dellus** [comment]
There is the same issue with the Block List.
