### ISSUE TITLE
No tooltips shown for widgets on the 'Categories' toolbar

### ISSUE THREAD

**Issue by pollywinters** [LibreCAD/LibreCAD#1519]
### Expected behavior
Mouse hover over tool widgets shows tooltip text, this works for most of the standard toolbars. But not for the items on the 'Categories' toolbar.

### Observed behavior
Mouse hover over the widget icons for the tool categories - Lines, Circles, Freehand, Ellipses, Polylines, Select, Dimensions, Modify, Measure - does not show a tooltip.

### Steps to reproduce or sample file
Hover mouse over most any widget icon on the LibreCAD window and a tooltip will appear. But not when hovering over the categories icons as listed above.

### Operating System and LibreCAD version info
Linux Mint 20.3, LibreCAD 2.2.0-rc3

### Solution
Tooltips can be added by insertion of "setToolTip()" calls within the librecad/src/ui/lc_widgetfactory.cpp source file, function LC_WidgetFactory::createCategoriesToolbar().
Eg. 
>    tool_button = new QToolButton;
>    tool_button->setPopupMode(QToolButton::InstantPopup);
>    tool_button->setIcon(QIcon(":/icons/line.svg"));
>    tool_button->setToolTip(tr("Lines"));      **// this line inserted**
>    categories_toolbar->addWidget(tool_button);
>    tool_button->addActions(line_actions);

### Source committed on fork
Commit is in pollywinters/LibreCAD fork if anyone is interested! Tag 2.2.0-pw1

**Comment by fa201** [comment]
Thank you for the issue and the solution.

**Comment by ryanthara** [comment]
> Thank you for the issue and the solution.

And where is the Pull Request for it?

**Comment by pollywinters** [comment]
Erm... First time that I've done any change to be considered for inclusion,
and I'm not yet sure how the pull request system works. I'll read up on the
site and try to figure it out.
Best regards, Polly

**Comment by pollywinters** [comment]
Pull request created
https://github.com/LibreCAD/LibreCAD/pull/1530
