### ISSUE TITLE
Rename nested block not work 

### ISSUE THREAD

**Issue by npelletm** [LibreCAD/LibreCAD#1527]
### Expected behavior
Rename nested block rename all block name in dxf file

### Observed behavior
Rename nested block rename block name in dxf file
In dxf file the last occurence of block is not renamed
Rename last occurence of block directly in dxf file will work as expected

### Steps to reproduce or sample file
Import a dxf to block with a nested block
Rename a nested block 
Save and quit
Re-open and the nested block is empty

### Operating System and LibreCAD version info
Version: 2.2.0-rc3
Compiler: GNU GCC 7.3.0
Compiled on: Nov 29 2021
Qt Version: 5.12.4
Boost Version: 1.65.1
System: Windows 7 SP 1 (6.1)

**Comment by adamzimny** [comment]
Fix proposed here: https://github.com/LibreCAD/LibreCAD/pull/1528
