### ISSUE TITLE
Strange links in the wiki download page

### ISSUE THREAD

**Issue by Kuczu** [LibreCAD/LibreCAD#1529]
### Observed behavior
I have noticed that links in the wiki's download page https://github.com/LibreCAD/LibreCAD/wiki/Download for the "The official release page" and for the Windows SourceForge installers have strange redirect to bit.ly which leads to (I think) the non official LibreCAD github's repo.

### Expected behavior
I believe the "The official release page" link should redirect to https://github.com/LibreCAD/LibreCAD/releases
and the Windows SourceForge installers link should lead to https://sourceforge.net/projects/librecad/files/Windows/

**Comment by lordofbikes** [comment]
Many thanks for reporting!

We recently recognized this kind of GitHub wiki trolling. I have to check the wiki monitor, which should have reported these changes.

Anyhow the user is reported to GitHub stuff and I expect him to be banned soon.
The changes are reverted.
