### ISSUE TITLE
Exporting images using .dxflib  

### ISSUE THREAD

**Issue by dagata-mining** [LibreCAD/LibreCAD#1533]
Hi,

This is not related to LibreCad directly but  you might me abbe to help me on this one. I'm trying to export images to .dxf format from a CloudcCompare plugin. I've tried to follow qcad or librecad approaches but can't seem to find the correct approach for the last 3 days. My .dxf is exporting but no sign of images in autocad.

Based on this approach :   https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/filters/rs_filterdxf.cpp#L1384

Code starting from: https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_io/src/DxfFilter.cpp#L1002
 I've hardcoded a few parameters to make sure I was passing them correctly
```cpp
...		
//Writing the Objects Section
		dxf.writeObjects(*dw);

		int handle = dxf.writeImage(*dw, DL_ImageData(std::string(""), 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 3141, 7866, 50, 50, 0),
			DL_Attributes(qPrintable("0"), DL_Codes::bylayer, -1, "BYLAYER", 1.0));
		dxf.writeImageDef(*dw, handle, DL_ImageData(qPrintable("C:/Users/Asus/Documents/shaft/BG_Image_001.png"),
                0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 3141, 7866, 50, 50, 0));

		dxf.writeObjectsEnd(*dw);

		//Ending and Closing the File
		dw->dxfEOF();
		dw->close();
	}
	catch (...)
	{
		ccLog::Warning("[DXF] DxfLib has thrown an unknown exception!");
		result = CC_FERR_THIRD_PARTY_LIB_EXCEPTION;
	}

	delete dw;
	dw = nullptr;

	return result;

#endif
}
```

**Comment by dxli** [comment]
Dxf file format doesn't cover storing pixels in file, only image information in the dxf file.

To save a dxf with images in LibreCAD, please keep the image files at dxf creation, or keep them in the same folder as the dxf file
