### ISSUE TITLE
How to Draw Angular Arcs？

### ISSUE THREAD

**Issue by 4SM** [LibreCAD/LibreCAD#1542]
![Screenshot - 2022-05-21 , 16_02_32](https://user-images.githubusercontent.com/13938189/169642464-4ddd98c9-527e-4e4c-a9e1-82e400e0bd6d.png)

**Comment by lordofbikes** [comment]
https://forum.librecad.org/
https://librecad.readthedocs.io/
https://dokuwiki.librecad.org/doku.php/usage:tutorials
