### ISSUE TITLE
LibreCad bug or version

### ISSUE THREAD

**Issue by Mot007** [LibreCAD/LibreCAD#1544]
### Operating System and LibreCAD version info

**LibreCad bug**

I'm a new user to Libre cad and have found a couple of anomalies.
1st I would like to know if the version I installed is the latest.

Version: 2.1.3
Compiler: GNU GCC 4.9.1
Compiled on: Sep 23 2016
Qt Version: 5.4.1
Boost Version: 1.60.0
System: Windows  

if it is why is the compile date so old?

The 2 issues I have found
1.  The metric unit is always in cm. That is instead of 3.00 it shows 300.00 on the drawing.
2. the Jpeg/tiff import works properly on layer 0.  if on another created layer with nothing on layer 0, the file save as .dxf loses all the information and work. ie when you load the file again it has nothing on it.

Thanks

**Comment by lordofbikes** [comment]
2.1.3 is the latest official release. But we are near to the release of 2.2.0 and it is safe to use the latest release candidate.
Find it here https://github.com/LibreCAD/LibreCAD/releases/tag/latest
or on SourceForge https://sourceforge.net/projects/librecad/files/Windows/NightlyBuilds/master/

The other questions I recommend to ask in our forum https://forum.librecad.org/, where experienced users are happy to help to sort this out.

**Comment by Mot007** [comment]
Thank you.
