### ISSUE TITLE
Creating templates - Current Drawing Preferences location- [proposed Label] Documentation

### ISSUE THREAD

**Issue by dzalf** [LibreCAD/LibreCAD#1552]
### Expected behavior

On the _Creating Templates_ section from the latest guides [page](https://librecad.readthedocs.io/en/latest/guides/dwg-setup.html) Step 1 indicates to go to the _Edit_ Menu and then select _Current Drawing Preferences_. This is not the case anymore.

### Observed behavior

The reader should be directed to the _Options_ Menu 

![image](https://user-images.githubusercontent.com/3759916/175944792-63c85fcc-686c-4368-8f9e-95147b4d36c0.png)

### Steps to reproduce or sample file

Just compare the guide and the actual location of this menu

### Operating System and LibreCAD version info

Version 2.1.3

![image](https://user-images.githubusercontent.com/3759916/175946045-36a97bec-4cfd-45ed-a52e-cfe53a6b5072.png)

https://librecad.readthedocs.io/en/latest/guides/dwg-setup.html

**Comment by lordofbikes** [comment]
Many thanks for reporting! :+1: 

Just in case you find another issue:
The manual has its own repo https://github.com/LibreCAD/docs.
Each page on https://librecad.readthedocs.io/ has a link in the upper right edge, **Edit on GitHub**.
This directs to the source of the page and with a GitHub account you can edit the file and create a pull request with your changes.
Not more complicated than an issue report, but much less effort. :wink:
