### ISSUE TITLE
Text (value) in dimensions does not display

### ISSUE THREAD

**Issue by JeanLucCoulon** [LibreCAD/LibreCAD#1570]
Hi, 
Since commit cf6ebe4e04d718591c6a31affa8526480ec079c3 the text in dimensions does not display.
The arrow / lines are present, but no more the values.

Last good commit - for this problem - is b8deda762cedecc3fe426623e0ba032d04184514

I use debian sid with linux 6.0.

regards

Jean-Luc

**Comment by lordofbikes** [comment]
Many thanks for reporting.

This was because of missing resource files in `unix` folder.
Thus it affected only Linux systems, fresh builds or when `unix` folder was deleted.
And only in development environment, not in any distribution.
