### ISSUE TITLE
Unable to open Autocad DWG

### ISSUE THREAD

**Issue by rbncha** [LibreCAD/LibreCAD#1573]
### Expected behavior
Open the DWG created on AutoDesk AutoCAD

### Observed behavior
While opening the AutoDesk AutoCAD DWG file, it gives Warning message and 

### Steps to reproduce or sample file
1. Open an AutoDesk AutoCAD DWG file.
2. Gives Error: **experimental, save your work first. Continue ?**
![image](https://user-images.githubusercontent.com/767121/201488544-a70ce71c-fe78-45e8-a352-177fa3173e7d.png)
3. Gives 2nd message **Cannot open the file ..../example-autocad.dwg. Please check its existence and permissions.**

### Operating System and LibreCAD version info
Version: 2.1.3
Compiler: GNU GCC 11.2.0
Compiled on: Jan 30 2022
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Ubuntu 22.04.1 LTS

**Comment by lordofbikes** [comment]
#767, #988, #1074, #1294, #1573
