### ISSUE TITLE
fix GitHub Actions annotations

### ISSUE THREAD

**Issue by lordofbikes** [LibreCAD/LibreCAD#1578]
Lately GitHub Actions reports deprecated code/packages in our workflow.

To keep the workflow running, we have to fix this:
>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, MarkusJx/install-boost@v2.0.0, actions/upload-artifact@v2

and this:
>The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The faulted parts are planned to be disabled end of May 2023, resp. summer 2023.

**Comment by dxli** [comment]
Issue fixed by the latest action: 
marvinpinto/action-automatic-releases@latest
