### ISSUE TITLE
Drawing not displayed with latest git, only the background

### ISSUE THREAD

**Issue by JeanLucCoulon** [LibreCAD/LibreCAD#1579]
### Expected behavior
Drawing displayed when opened

### Observed behavior
Only the background is displayed, nothing in the layers list either

### Steps to reproduce or sample file
Open any dxf

### Operating System and LibreCAD version info
Debian sid, gnu/linux 6.0

I've done a bisect on the git repository.
I got the following:
/usr/local/src/librecad/ git bisect good
cca3c2dcfafa7ef9ddc902e305a030bf231a158f is the first bad commit
commit cca3c2dcfafa7ef9ddc902e305a030bf231a158f
Author: Armin Stebich <home@mail.lordofbikes.de>
Date:   Sat Dec 10 10:40:16 2022 +0100

    mitigated DWG open warning and allow opening with errors

 CHANGELOG.md                          |  3 +-
 librecad/src/lib/fileio/rs_fileio.cpp | 73 +++++++++++++++++++++++++++++------
 2 files changed, 63 insertions(+), 13 deletions(-)

Regards
Jean-Luc

**Comment by lordofbikes** [comment]
Many thanks for reporting :+1:
Obviously I missed the final test before committing last modification :angry:
