### ISSUE TITLE
Imported image absolute path

### ISSUE THREAD

**Issue by PeterHagen** [LibreCAD/LibreCAD#1589]
When an image is imported to a drawing, it's stored with its absolute path of the filesystem. This will make the image disappear when the drawing is opened on another machine, or another user account. The path also can't be edited in the property dialog.

### Expected behavior
Storing the image path relative to the drawing

### Observed behavior
Storing the image path absolute to the filesystem

### Steps to reproduce or sample file
Just insert some image, in my case a SVG, and check the properties

### Operating System and LibreCAD version info
macOS m1, Ventura and LibreCad Version: 2.2.0-2-gf55f341e

**Comment by fa201** [comment]
A work around could be to delete the absolute path in DXF file, providing image and DXF file stay in the same folder. I checked it works. To make it easy to spot, you can search the DXF file for the image name with a text editor.

**Comment by dellus** [comment]
If you place the image in the same folder as the dxf file, the image will always be found, where ever it was when you inserted it into the drawing.

**Comment by PeterHagen** [comment]
The issue is that the image is inside a block, that is being added to different drawings in different directories. It would be helpful if the path of the file is editable in the property window. Now its a readonly element.

**Comment by dxli** [comment]
The image source is now editable in the property dialog
