### ISSUE TITLE
Silent install in Windows opens website after installation

### ISSUE THREAD

**Issue by Saxomania** [LibreCAD/LibreCAD#1600]
We deploy software to our central managed windows clients via SCCM/MECM and it will be installed via Softwarecenter (user frontend),  this doing installations under SYSTEM account.  

"LibreCAD-Installer-2.2.0.exe /S" installation is working fine but at the the end it opens a website and the default browser opens under SYSTEM account, which is a real problem.

So please add an option to avoid opening this website or, much better, remove this option at all if /S is used.

**Comment by Coco05051989** [comment]
Same issue here.

**Comment by Saxomania** [comment]
Great, thank you. Just to be sure, this is now working in v2.2.1_alpha-59 but not in the latest stable release 2.2.0?

**Comment by dongxuli-concord-design** [comment]
We may want to release 2.2.1.

We got lots of pull requests and lots of other changes since 2.2.0, and some stabilization time is needed.

**Comment by Saxomania** [comment]
OK then i will wait for the next stable release. Thanks for your efforts.
