### ISSUE TITLE
The path for symbol libraries does not work

### ISSUE THREAD

**Issue by kberkut** [LibreCAD/LibreCAD#1603]
The path for symbol libraries does not work

### Expected behavior
Displaying custom blocks in the Library Manager.

### Observed behavior
The user library is not displayed.
Only the default library is displayed.
![image](https://user-images.githubusercontent.com/57869227/231945269-a04b7979-e386-4523-a531-3efb4d640795.png)

### Steps to reproduce or sample file
Add a path for your own block library.
![image](https://user-images.githubusercontent.com/57869227/231944169-da8c52a3-a313-49f9-b24b-bdaebe3fb984.png)

### Operating System
OS: Arch Linux x86_64 
Kernel: 6.2.10-arch1-1 
Resolution: 1920x1080 
DE: GNOME 43.4 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 5635MiB / 9886MiB  

### LibreCAD version info
Версия: 2.2.0
Компилятор: GNU GCC 9.4.0
Собран: Dec 17 2022
Версия Qt: 5.12.9
Версия Boost: 1.75.0
Система: Arch Linux

**Comment by fa201** [comment]
It works with 
Version: 2.2.0-alpha
Compiler: GNU GCC 11.3.0
Compiled on: Jan  7 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Ubuntu 22.04.2 LTS

Could it be OS dependent ?

**Comment by dxli** [comment]
Works for me now.

**Comment by kberkut** [comment]
The problem is not in the program, the problem is in the description in the help. It is necessary to add to the help that the settings specify the path to the directory that contains the subdirectory with the dxf files of the symbol library. I suggest adding it to the help:

To connect a third-party symbol library, write the full path to the directory in the LibreCAD settings, for example "/home/user/Library/".
For the specified path, the symbol library files must be located in the subdirectory "/home/user/Library/Library_1". Files with the dxf extension should be located in the "Library_1" subdirectory.
The name of the subdirectory "Library_1" will be displayed in the library manager.
