### ISSUE TITLE
Coordinate information always 0,0

### ISSUE THREAD

**Issue by akcansoft** [LibreCAD/LibreCAD#1611]
Librecad version: 2.2.0-28-g0f4bd405
May 16 2023

The coordinate information shown in the lower left pane always appears as 0,0

System:
ASUS FX502VE Notebook Windows 11
CPU: Intel i5-7300HQ CPU 2.5 GHz
RAM: 8 GB DDR4
GPU 1: Intel HD Graphics 630
GPU 2: 4GB NVIDIA GeForce GTX 1050 Ti

**Comment by akcansoft** [comment]
updated

**Comment by lordofbikes** [comment]
many thanks for reporting @akcansoft
many thanks for fixing @dxli
