### ISSUE TITLE
 Tangent (P,C) draws directly a line from P to Origin(0,0) 

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1612]
From the forum:
	
'Same on Fedora 38

Version: 2.2.0-28-g0f4bd405
Compiler: GNU GCC 13.1.1
Compiled on: May 17 2023
Qt Version: 5.15.9
Boost Version: 1.78.0
System: Fedora Linux 38 (Server Edition)

Tangent (P,C) draws directly a line from P to Origin(0,0) '

https://forum.librecad.org/Selecting-circle-in-tangent-tool-tp5721532p5722809.html

It is the same on Windows. I have checked with Win XP nightly builds, it is introduced at 2.2.0-7-g9f39a7b0 and persists in recent 2.2.1_alpha-2-g10b1c73c.

**Comment by dxli** [comment]
Should be an easy one. I will have time to work on it soon
