### ISSUE TITLE
Free snap button does not work at startup

### ISSUE THREAD

**Issue by gerardbm** [LibreCAD/LibreCAD#1619]
### Expected behavior

The "free snap" button should work after open a file.

### Observed behavior

The "free snap" does not work.

### Steps to reproduce or sample file

Open a file and enable the "free snap". Then close the file. Then open a new file and try to snap for free, you will see that it only snaps to the other snap options, but not the free one. Then enable/disable the grid and try again. Now the "free snap" works correctly.

Video with the example: [video](https://www.youtube.com/watch?v=I1ixehGwd98)

### Operating System and LibreCAD version info

```
Version: 2.2.1_alpha-51-ge1aad908
Compiler: GNU GCC 6.3.0
Compiled on: Jun  4 2023
Qt Version: 5.7.1
Boost Version: 1.62.0
System: Debian GNU/Linux 9 (stretch)
```

**Comment by dxli** [comment]
I cannot reproduce this one:

1, Open a dxf file, enable "Snap Free" only(other snap options disabled);
2, Close the dxf file, and open another dxf file;
3, "Snap Free" is still the only enabled snapping options;
4, Snap free works (say, with line 2 points).

**Comment by gerardbm** [comment]
I compiled the last version and it still fails for me.

To reproduce this, enable also the "snap on endpoints".

**Comment by gerardbm** [comment]
I compiled again and now it works perfect, as it's expected!

Thanks a lot for the job you're doing these days. <3

**Comment by gerardbm** [comment]
Resolved
