### ISSUE TITLE
I can't compile LibreCAD after last update

### ISSUE THREAD

**Issue by gerardbm** [LibreCAD/LibreCAD#1630]
### Observed behavior

This is the error I'm getting after the command `make -j4`:

```
[...]
Makefile:5710: recipe for target '../../generated/librecad/obj/rs_ellipse.o' failed
make[2]: *** [../../generated/librecad/obj/rs_ellipse.o] Error 1
make[2]: *** Waiting for unfinished jobs....
lib/engine/lc_splinepoints.cpp: In function ‘double DrawPatternLine(const std::vector<double>&, int, double, QPainterPath&, RS_Vector&, RS_Vector&)’:
lib/engine/lc_splinepoints.cpp:1554:16: warning: unused variable ‘dt2bak’ [-Wunused-variable]
         double dt2bak=dt1;
                ^~~~~~
make[2]: Leaving directory '/home/gerard/Workspace/varis/librecad/librecad/src'
Makefile:42: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory '/home/gerard/Workspace/varis/librecad/librecad'
Makefile:88: recipe for target 'sub-librecad-make_first-ordered' failed
make: *** [sub-librecad-make_first-ordered] Error 2
```

This is thet last part of the error, because it's too long.

**Comment by fa201** [comment]
Which OS ?

**Comment by gerardbm** [comment]
Debian GNU/Linux 9 (Stretch)

**Comment by dxli** [comment]
To see the actual error message, run "make -j1" after the building failure.

**Comment by gerardbm** [comment]
I redirected it to a file with `2>`

[log.txt](https://github.com/LibreCAD/LibreCAD/files/11712421/log.txt)

**Comment by dxli** [comment]
the log file contains no compiler command lines.

**Comment by gerardbm** [comment]
I don't know what I should do. I always do the following: `qmake -r` and then `make -j4`. At the end of this process, the binary file `./unix/librecad` is not created. The output is so long that I don't know how to copy it. Let me show you a video with the process: [Youtube](https://www.youtube.com/watch?v=EktxwhTpm3g)

**Comment by gerardbm** [comment]
Well, I'm gonna use the AppImage from now. Probably this issue occurs because my OS is too old. Close it if it's the case. Thanks a lot for the fixes and the improvements.

**Comment by dongxuli-concord-design** [comment]
No, your compilern new enough, and it's just one incorrect compiler command line option. Try to supply a CXXFLAGS="-std=c++1y" in custom.pro

**Comment by gerardbm** [comment]
Is it possible that the compiler is not reading the file `custom.pro`?

**Comment by dongxuli-concord-design** [comment]
No.

librecad.pro is our entry point for qmake.

custom.pro is called by librecad.pro

custom.pri is used by librecad/src/src.pro

**Comment by gerardbm** [comment]
Finally I could compile LibreCAD, adding the following line in `custom.pro`:

```
QMAKE_CXXFLAGS += -fext-numeric-literals
```

Now I have a binary file. However, when I execute it I get the following output error:

```
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout
pure virtual method called
terminate called without an active exception
```

**Comment by dxli** [comment]
Could you update your source and try again?

It's probably due to a mistake I made today. Should be fixed in master already.

**Comment by gerardbm** [comment]
Yes, that worked perfect now! Thanks a lot again.
