### ISSUE TITLE
Text rendering issue with French accent

### ISSUE THREAD

**Issue by fa201** [LibreCAD/LibreCAD#1638]
### Expected behavior
French accent is always properly rendered.

### Observed behavior
A DXF file generated with one of 2.2.0 release candidates has some French accent `é` not rendered correctly at file opening. `'` is rendered with the `e` below.

### Steps to reproduce or sample file
Open the file.
Show all layers (layers with text were hidden and locked when the file was saved). See picture.
Hide the text layer (still locked)
Show the text layer: now the text is OK. See picture.

### Operating System and LibreCAD version info
Version: 2.2.1_alpha-188-g5c4d14de
Compiler: GNU GCC 11.3.0
Compiled on: Jun 20 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Ubuntu 22.04.2 LTS
CI AppImage
![text_NOK](https://github.com/LibreCAD/LibreCAD/assets/49532187/31b803f0-31c1-4343-bef0-c27f914f23a0)
![text_OK](https://github.com/LibreCAD/LibreCAD/assets/49532187/c7e64664-1fe8-4771-83a0-3912a2ee2311)

Notes:
- switching on/off another layer without text give OK result.
- redraw does not help

**Comment by dxli** [comment]
This appears to be a hard one. Conceivable workaround could be larger text sizes, higher dpi at rendering, or another font

**Comment by fa201** [comment]
The work around is to show on/off some layers which is faster without any impact on the drawing.

**Comment by dxli** [comment]
Can you upload a test case dxf file?

**Comment by fa201** [comment]
Unfortunately, I am not allowed to share this file.
