### ISSUE TITLE
Target shape appear on last AppImage

### ISSUE THREAD

**Issue by fa201** [LibreCAD/LibreCAD#1639]
### Expected behavior
There is no target shape as shown on picture generated by 
Version: 2.2.0
Compiler: GNU GCC 9.4.0
Compiled on: Dec 17 2022
Qt Version: 5.12.9
Boost Version: 1.75.0
System: Ubuntu 22.04.2 LTS
CI AppImage
![shape_OK](https://github.com/LibreCAD/LibreCAD/assets/49532187/654f014a-ec84-4208-a1cf-f5fab84d8d28)

### Observed behavior
A target shape appear with a constant size (in pixels not in mm). See pictures with increased zoom for each picture.
Version: 2.2.1_alpha-188-g5c4d14de
Compiler: GNU GCC 11.3.0
Compiled on: Jun 20 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Ubuntu 22.04.2 LTS
CI AppImage
![shape_NOK1](https://github.com/LibreCAD/LibreCAD/assets/49532187/008c6812-9554-44ea-8498-40ee03afbf88)
![shape_NOK2](https://github.com/LibreCAD/LibreCAD/assets/49532187/4a472dca-67d6-41a1-b43e-90bd29ae0922)
![shape_NOK3](https://github.com/LibreCAD/LibreCAD/assets/49532187/03d7d078-7451-4f64-a590-41f76ed78bd4)
![shape_NOK4](https://github.com/LibreCAD/LibreCA
![shape_NOK5](https://github.com/LibreCAD/LibreCAD/assets/49532187/8c2291fb-a9e7-4a03-81d9-bfb27b9ae410)
D/assets/49532187/bf2f565b-1969-43ca-8857-90392beb6233)

Note that this shape can be selected as shown on the last picture.

**Comment by dxli** [comment]
This is a new feature: customized point shapes

Please have a look at drawing preferences, and there's a new tab "Points", and the point outlines can be selected there.

I will review the default choice in code.

**Comment by dxli** [comment]
The current default point outline and size are defined in lc_defaults.h

```C++

/**
 * Defines default values for system settings etc within the
 * LibreCAD program. 
 * Eg. Application preferences default values, current drawing preferences
 * default values, 
 *
 * @author Polly Winters
 */

/*	Point display mode and size  */
#define LC_DEFAULTS_PDMode		DXF_FORMAT_PDMode_EncloseCircleSquare(DXF_FORMAT_PDMode_CentreDot)
#define LC_DEFAULTS_PDSize		        DXF_FORMAT_PDSize_Percent(2.0)
```

Since both the default shape and size could be set by the end user in:

Edit > Current drawing preferences > Points > Point Size

it's not considered a regression.
