### ISSUE TITLE
Assets not updated in Continuous Build

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1643]
### Expected behavior

Latest assets produced by GitHub Actions should be uploaded Continious Build release:

- https://github.com/LibreCAD/LibreCAD/tree/latest

### Observed behavior

Fresh built Assets not uploaded after commit https://github.com/LibreCAD/LibreCAD/commit/5c4d14de31ca767d3751d93c8a46816c2dc0b479

**Comment by dxli** [comment]
fixed by reverting the workflow changes
