### ISSUE TITLE
Strange highlighting elements on hover

### ISSUE THREAD

**Issue by PeterHagen** [LibreCAD/LibreCAD#1645]
### Expected behavior

Not sure what the expected behaviour should be, but I guess the element where the mouse is hovering about is highlighted

### Observed behavior

See image: 

<img width="1728" alt="Screenshot 2023-06-29 at 22 56 36" src="https://github.com/LibreCAD/LibreCAD/assets/12300899/b75d286d-3c61-4a15-a9ca-25d6cfd9469f">

### Steps to reproduce or sample file

Any file will reproduce

### Operating System and LibreCAD version info

macOS (M1) 13.4.1

LibreCAD
Version: 2.2.1_alpha-212-g9ad76aa2
Compiler: Clang 14.0.3
Compiled on: Jun 29 2023
Qt Version: 5.15.10
Boost Version: 1.76.0
System: macOS 13.4

**Comment by dellus** [comment]
I have discovered the size of the effect depends on the line width. It is OK with line width 0.00 mm and grows with larger, real widths.

**Comment by dxli** [comment]
@dellus confirmed.

So, we have two issues:

1, width control: currently the width could be too much. The goal, the glowing effect shouldn't be larger than double the displayed width;
2, The "Selected" and "Highlighted" colors messed up: "Selected"(glowing) color is displayed by the "Highlighted" color.

**Comment by dxli** [comment]
Included in 951c845

1, Glowing effects are using the color of selected unitities, instead of highlighted, which is reserved for actions, such as trimming;
2, Glowing effects screen width is limited to certain maximum, which may need to be further optimized.

**Comment by PeterHagen** [comment]
I'm personally not happy with the highlighting. This is a screenshot of the latest master:

<img width="361" alt="Screenshot 2023-07-07 at 14 30 43" src="https://github.com/LibreCAD/LibreCAD/assets/12300899/4610d5cb-ee62-4763-a4f2-da7d1c38b977">

As far as I know I didn't make any user settings for the highlighting, so this should be with default values. In this case it's just one text block, but in case of a block, everything turns into a grey blur.

Previously, there was no highlighting as far as I can recall. Can this feature be made optional?

**Comment by dongxuli-concord-design** [comment]
Yes, it shouldn't be disruptive.

I will add an option to enable it.

**Comment by fa201** [comment]
@dxli I agree with @PeterHagen . I was about to open an issue to ask for a check box for this feature as I find it annoying for some works.

**Comment by PeterHagen** [comment]
Perfect! Thanks for the fix!
