### ISSUE TITLE
MText object shows only first line of multiline text

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1654]
### Expected behavior

MText object should show all multi-line text as it inputed.

### Observed behavior

MText object shows only first line of multi-line text input.

In same time when move MText object bounding box shows as it include text of multi-line text input.

![screen-2023-07-13-12-09-49](https://github.com/LibreCAD/LibreCAD/assets/22447924/8fa97848-e8c2-49bc-81a5-72bb6ba16021)

### Steps to reproduce or sample file

1. Create "MText" object;
2. Input multi-line text:
    ```
    R/L*360°
    25/74.33*360°
    121.08°
    ```
3. Press <kbd>OK</kbd>

### Operating System and LibreCAD version info

GitHub's latest AppImage

```
Version: 2.2.1_alpha-222-gfc51494d
Compiler: GNU GCC 11.3.0
Compiled on: Jul 13 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Debian GNU/Linux 12 (bookworm)
```

**Comment by efraletti** [comment]
Hi, I'm having this exact issue, only first line shows, even in "print preview"

I'm using

Version: 2.2.1_alpha-224-gc8389f010
Compiler: GNU GCC 13.1.1
Compiled on: Jul 13 2023
Qt Version: 5.15.10
Boost Version: 1.81.0
System: Arch Linux

**Comment by dongxuli-concord-design** [comment]
I will look into this one.
Just in case, could you test whether this is a regression, say from 2.1.3

**Comment by app4soft** [comment]
> Just in case, could you test whether this is a regression, say from 2.1.3

May You provide AppImage for `2.1.3`? (and add it to related release assets)

**Comment by efraletti** [comment]
last commit fixed it! thank you!

```
Version: 2.2.1_alpha-231-g3974b2205
Compiler: GNU GCC 13.1.1
Compiled on: Jul 14 2023
Qt Version: 5.15.10
Boost Version: 1.81.0
System: Arch Linux
```

**Comment by app4soft** [comment]
Confirming: issue fixed now.

![screen-2023-07-14-20-58-12](https://github.com/LibreCAD/LibreCAD/assets/22447924/c204a596-1e3f-40fb-8d79-1985fc90b667)
