### ISSUE TITLE
Zoom is slower while a hatch is highlighted by the cursor

### ISSUE THREAD

**Issue by gerardbm** [LibreCAD/LibreCAD#1670]
### Expected behavior

Zoom in or zoom out with the mouse becomes slower than normally usage when the mouse is highlighting a hatch.

### Observed behavior

The zoom should be consistent and stable, independently of the viewer or the highlighted or selected objects.

### Steps to reproduce or sample file

Create a new file, create a polygon, add a hatch into it with a lot of lines. For example this one:

![2023-07-28_20:05:35](https://github.com/LibreCAD/LibreCAD/assets/5253997/eed3c81b-37bd-4e22-8466-678565da6db8)

### Operating System and LibreCAD version info

Version: 2.2.1_alpha-255-gf4985ac4
Compiler: GNU GCC 11.3.0
Compiled on: Jul 28 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Debian GNU/Linux 9 (stretch)

**Comment by dxli** [comment]
I am wondering whether we can move hatching to the display layer. Conceptually, nothing relies on the details of hatching lines or how they are trimmed exactly.

**Comment by dxli** [comment]
Need to disable mouse hovering effects on hatch. Instead show borders
