### ISSUE TITLE
Selected object line type has low visibility

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1671]
### Expected behavior

Selected objects line type should visible or there should be an option to customize "Selected Line type" in application preferences.

### Observed behavior

Actually selected objects almost invisible due to hard-coded "Dot" style.

![Screenshot_2023-07-29_02-42-27](https://github.com/LibreCAD/LibreCAD/assets/22447924/2752a977-c951-46d8-9ff0-33403741a56f)

![Screenshot_2023-07-29_02-42-58](https://github.com/LibreCAD/LibreCAD/assets/22447924/b4d7aa3a-27b8-45a2-bc63-383a99ddee68)

### Steps to reproduce or sample file

1. Create some objects;
2. Select some object.

### Operating System and LibreCAD version info

```
Version: 2.2.1_alpha-255-gf4985ac4
Compiler: GNU GCC 11.3.0
Compiled on: Jul 28 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Debian GNU/Linux 12 (bookworm)
```

**Comment by CTuBu** [comment]
Same on Win10

**Comment by dxli** [comment]
Looks like the pen style of selected was lost to me

**Comment by app4soft** [comment]
For me it looks like now exact `Dot` line type (which is in between `Dot small` and `Dot (large)`) is used as a line type for all selected objects. Previously selected objects has line type similar to `Dash (tiny)`.

Here is comparison (grid is off): on the left — selected spline with `Continious` line type, on the right — non-selected spline with `Dot` line type.

![Screenshot_2023-07-29_19-05-14](https://github.com/LibreCAD/LibreCAD/assets/22447924/1407dc96-b1bc-4709-ae7c-3794d9c93d9a)
