### ISSUE TITLE
Error on dimension display

### ISSUE THREAD

**Issue by fa201** [LibreCAD/LibreCAD#1675]
### Expected behavior
Dimension value is shown in the middle of arrow as for this version:
Version: 2.2.0.2
Compiler: GNU GCC 9.4.0
Compiled on: Jul 29 2023
Qt Version: 5.12.9
Boost Version: 1.75.0
System: Ubuntu 20.04.6 LTS

![ok](https://github.com/LibreCAD/LibreCAD/assets/49532187/d70dc199-0ae4-4523-b5bc-af1fc07d9ed8)

### Observed behavior
Dimension is shifted to the right for vertical and horizontal dimensions for this version:
Version: 2.2.1_alpha-270-g5e5eaff3
Compiler: GNU GCC 11.3.0
Compiled on: Aug  7 2023
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Ubuntu 20.04.6 LTS

![error](https://github.com/LibreCAD/LibreCAD/assets/49532187/cbb99239-f67a-4e59-9c2e-7dce935f71a2)

**Comment by dxli** [comment]
this is fixed in 2.2.1_rc2 and 2.2.0_alpha
