### ISSUE TITLE
identical expression

### ISSUE THREAD

**Issue by maddin200** [LibreCAD/LibreCAD#1679]
libraries/jwwlib/src/dl_jww-copy.cpp line 4409
Code:
  if (!strcmp(var, "$ACADVER")) {
        return true;
    }
    if (!strcmp(var, "$ACADVER")) { // <-- identical
        return true;
    }

**Comment by dxli** [comment]
this is a leftover file, should be removed.

Currently, it's not in the project and won't get compiled.
