### ISSUE TITLE
no way to re-dock widgets when using a tiling window manager

### ISSUE THREAD

**Issue by jmcantrell** [LibreCAD/LibreCAD#1685]
The tiling window manager in my case is sway, but I'm betting the behavior is the same for other similar window managers.

### Expected behavior
I expected some way (like a button) that would re-dock a widget that has been detached.

### Observed behavior
In addition to not having a way to re-dock the widgets, they are incredibly easy to detach unintentionally. I initially discovered this by trying to re-order them.

As soon as they are detached, the only way I found to re-attach them is to reset the application defaults and restart.

### Steps to reproduce or sample file

1. Open librecad in sway
2. Drag a dock widget
3. Notice it is now a floating window
4. Notice there is no way to re-dock this widget

### Operating System and LibreCAD version info
Arch linux, kernel 6.4.10, librecad 2.2.0.2, sway 1.8.1 (all the latest packaged versions at the time of this post)

**Comment by dxli** [comment]
I just added a fix for the command widget, which bothers me the most. The command widget has a menu, so it's convenient to add a menu entry to re-dock the widget, if it's floating.

e6fd1a44da8

I am not sure about a generic fix here. A quick fix could be adding a command to re-dock all floating widgets.

**Comment by dellus** [comment]
I can not confirm the issue. For me it's no problem to relocate a  floating widget to the original position by dragging it to there. Just might be a bit tricky to find the right spot to drop it.
Works with 2.1.3 and 2.2.0 in WinXP and with 2.2.0 appimage in Puppylinux Fossapup.

**Comment by dongxuli-concord-design** [comment]
I am running kde plasma, and found no way to re-dock floating widgets.
Wondering how it works on Mac.

**Comment by jmcantrell** [comment]
> I am not sure about a generic fix here. A quick fix could be adding a command to re-dock all floating widgets.

The first thing that came to mind was a button that would re-dock the widget to it's previous spot, like what you have for the command window. A command that snaps them all back would be good too. I'm not familiar with the capabilities of the qt toolkit, so I'm not sure what the optimal solution is. Anything would be a step in the right direction.

**Comment by dongxuli-concord-design** [comment]
> I can not confirm the issue. For me it's no problem to relocate a  floating widget to the original position by dragging it to there. Just might be a bit tricky to find the right spot to drop it.
> Works with 2.1.3 and 2.2.0 in WinXP and with 2.2.0 appimage in Puppylinux Fossapup.

I remember running into the situation with an other Qt based app on Windows. You can re-dock a floating widget, but you may have to drag around for a while first, since the active spot is tiny.

It makes sense to have a direct control in those cases.

**Comment by dxli** [comment]
I am thinking about a "Reset widgets" in the View menu.

**Comment by dxli** [comment]
Added a menu entry:

Widgets > Dock Widgets > Re-dock Widgets
