### ISSUE TITLE
Construction layer not working in continuous Build 2.2.0.x

### ISSUE THREAD

**Issue by CTuBu** [LibreCAD/LibreCAD#1698]
### Expected behavior
Drawing line in construction layer is infinite

### Observed behavior
Drawing line in construction layer is not visible at all. 
If remove # in layer list before construction layer lines become visible, but not infinite.

### Operating System and LibreCAD version info
Win7 , Win10
LibreCad 2.2.0.2-3 and LibreCAD 2.2.0.2-4-g4cfa8d9f

**Comment by lordofbikes** [comment]
many thanks for reporting :+1:
