### ISSUE TITLE
Add command-line option for dxf2svg

### ISSUE THREAD

**Issue by WillAdams** [LibreCAD/LibreCAD#1705]
I frequently use LibreCAD to open problematic DXFs and then export them as an SVG file --- which usually fixes all the problems and results in an SVG which works perfectly.

Unfortunately, this is not supported at the command line AFAICT, or at least when I tried:

    "C:\Program Files (x86)\LibreCAD\LibreCAD.exe" dxf2svg gcode.dxf gcode.svg

I did not get an SVG (though LibreCAD launched, and opened the file in question) --- would it be possible to add this?

**Comment by dxli** [comment]
309500152 : added support for dxf2svg
