### ISSUE TITLE
Command and mouse wheel zoom problem

### ISSUE THREAD

**Issue by akcansoft** [LibreCAD/LibreCAD#1713]
### Operating System and LibreCAD version info
Windows 11 TR
LibreCAD-Installer-x64-2.2.1_alpha-312-gb46986b3.exe

If you zoom in/out with the mouse wheel after entering a command, the command does not work.

**Comment by rola22** [comment]
I can confirm this behaviour on Linux Mint
Librecad version: 2.2.1_alpha-311-g17fabaff
