### ISSUE TITLE
using CPP17 features didn't work

### ISSUE THREAD

**Issue by AMen9** [LibreCAD/LibreCAD#1716]
lib\engine\lc_looputils.cpp:422:12: error: 'make_unique' is not a member of 'std'
     m_data{std::make_unique<LoopSorter::Data>(this, std::move(loops))}

### Operating System and LibreCAD version info
windows 10, libreCAD master main, qt5.9.9, mingw53_32

**Comment by dxli** [comment]
Hi std::make_unique is part of c++14.

Please note, we now require qt5-15 (the LTS) and C++17.
