### ISSUE TITLE
Import Error: Undefined Error

### ISSUE THREAD

**Issue by pgclark96** [LibreCAD/LibreCAD#1721]
![Screenshot from 2024-01-11 11-46-17](https://github.com/LibreCAD/LibreCAD/assets/38139082/798b8a19-d99a-4d13-813b-ba10ceaba8f1)

Observed when first opening all sessions. I am proficient on program, not power user, and i don't think it has impacted my work.
Curious/annoying.

### Operating System and LibreCAD version info
Ubuntu 22.04 LTS
LibreCAD 2.2.0-x86_64.appimage

**Comment by dxli** [comment]
Steps to reproduce? 
Sample dxf files?

DWG support is not complete, and there's currently no developer working on DWG support.

**Comment by pgclark96** [comment]
One file was Autocad2010 saved as dxf
One file was Autocad2017 saved as dxf
One file from PDF to dxf via Scan to Cad
Error occurs on first screen as program starts. I do not use start screen.
Error clears after hitting OK and has not reappeared during work session so far

**Comment by pgclark96** [comment]
After-thought..
I cannot open a LibreCAD drawing by double clicking on drawing name. Get software not found which I attribute to using the .appimage.
Start LibreCAD first to blank screen (with error), then open files
