### ISSUE TITLE
Cannot load a basic DXF file

### ISSUE THREAD

**Issue by 5axes** [LibreCAD/LibreCAD#1733]
Cannot load a "basic" DXF file .

OS Windows 10 
LibreCad : [LibreCAD-Installer-x64-2.2.1_alpha-332-g5b50aa69.exe](https://github.com/LibreCAD/LibreCAD/releases/download/latest/LibreCAD-Installer-x64-2.2.1_alpha-332-g5b50aa69.exe)

Error Message
![image](https://github.com/LibreCAD/LibreCAD/assets/11015345/09857b73-685f-435d-9b8f-1c96801f7e8f)

DXF file
![image](https://github.com/LibreCAD/LibreCAD/assets/11015345/3b8351b2-689f-4ea8-ab8e-f425c14d4e80)

[Урал 44202.zip](https://github.com/LibreCAD/LibreCAD/files/14126194/44202.zip)

**Comment by lordofbikes** [comment]
It opens for me on Linux, with 2.2.0 release and latest master.
Probably it's an OS issue with non ASCII characters in the filename.
Please try to rename the file to something without local character set or numbers only.

The drawing has some issues, missing fonts and unsupported text formatting, but basically the drawing should be usable.

**Comment by 5axes** [comment]
It's ok for the file name ... but even it's an unsupported text formatting other Viewer can read it.

LibreCad
![image](https://github.com/LibreCAD/LibreCAD/assets/11015345/955ff10f-e169-41dc-9adc-7d4b75578a98)

eDrawings
![image](https://github.com/LibreCAD/LibreCAD/assets/11015345/0907c39d-027d-400d-848d-c9d15d757f3d)
 
[44202.zip](https://github.com/LibreCAD/LibreCAD/files/14131140/44202.zip)

**Comment by lordofbikes** [comment]
That's what I meant, missing fonts. LibreCAD has it's own font format and does not support standard fonts like TTF.
And the front dimensions has some formatting which is also not supported in LibreCAD, that's why the dimension label is much longer than in your screenshot.
For both issues we already have tickets (#1105, #1286), but no solution so far.

Sadly, that's the best LibreCAD can do for this drawing.

**Comment by dellus** [comment]
44202.dxf: I exploded the inserted title/frame block. Clicked with "Properties" on one of the text rectangles. An MText input box appeared.
In the text field the text was shown. Font field was empty, height = 0. After defining a font and changing height to a proper value, the text appeared in the drawing.

**Comment by dongxuli-concord-design** [comment]
Should we provide a default font size? If the font size was found to be zero.

Default font should be unicode.

Intentionally don't 0 to hide is not useful

**Comment by 5axes** [comment]
This seems a good principle in the absence of values, or if a value is set to zero for no logical reason, why not use the default value, the default font, etc.?  If an application is to be appreciated by users, it must be robust in reading and adapt to the errors of others (within reason), and flawless in writing.
