### ISSUE TITLE
Small yet nice widget to add - pen palette  

### ISSUE THREAD

**Issue by sand1024** [LibreCAD/LibreCAD#1735]
I've created a small yet nice widget for a bit more convenient way for working with pens. 

It allows managing of persistent pens, select entities based by pens and apply pens to selection, current layer and so on.  

Demo video for the widget is there - https://youtu.be/YSU0K3-PfbI
Feature branch - https://github.com/sand1024/LibreCAD/tree/pens_palette_widget
Readme - https://github.com/sand1024/LibreCAD/blob/pens_palette_widget/PEN_PALETTE_README.md

If it is better to create a merge request rather than issue there - please let me know.

**Comment by dongxuli-concord-design** [comment]
Can you send in a Pull Request?

**Comment by sand1024** [comment]
here it is - https://github.com/LibreCAD/LibreCAD/pull/1745

**Comment by dxli** [comment]
Merged
