### ISSUE TITLE
Librecad disappearing completely from Mac after force quitting

### ISSUE THREAD

**Issue by libreuser1** [LibreCAD/LibreCAD#1737]
### Expected behavior
To be able to see Librecad in the dock

### Observed behavior
Librecad disappears from dock and the system. Its like its uninstalled or was never even installed

### Steps to reproduce or sample file
1. Librecad froze when I was doing some drawing 
2. I tried to quit, but was unable to.
3. So did a Force Quit
4. Next I am unable to find the Librecad application on my Mac
5. I did a search in application but could not find anything related to librecad
6. This is the second time it has happened. 

### Operating System and LibreCAD version info
OS : MAC Sonoma: 14.2.1 (23C71)
Librecad version: Latest version as of Librecad for Mac as of 8th Feb 2024

**Comment by dxli** [comment]
I suppose this cannot be an issue of LibreCAD, as we do not (or shouldn't) have code to destroy app.

Closing this one.
