### ISSUE TITLE
'Properties' doesn't show 'By layer' for an entity if so assigned but the end result

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1759]
Expected behavior: 'Properties' for an entity drawn with 'by layer' should show 'By layer'.

Observed behavior: 'Properties' for an entity drawn with 'by layer' shows the attributes assigned to the layer.

LibreCAD 2.2.1 alpha 412 appimage or earlier (since introduction of Layer Tree and Pen Palette).
Puppylinux Fossapup64

**Comment by sand1024** [comment]
mmm - not sure I understand. In which place so you observe such a behavior? In properties dialog? In active pen buttons? 
Please add more details.

**Comment by dongxuli-concord-design** [comment]
By layer
By block

I do remember there's something logic cleanup needed.

**Comment by sand1024** [comment]
mmm - I think I finally got it - if properties dialog is invoked for the entity, "By layer/By Block" label is not shown anymore, only actual color name. 
Yes, it seems it's my fault related to setup of properties dialogs, I'll fix it. Actually, the intent was to show not a black/white icon for the color in dialogs, but actual color (that same logic as in active pen toolbar).  
Anyway, I'll correct this with separate pull request.

**Comment by dongxuli-concord-design** [comment]
We can keep the color icon and the text "by Layer" for example. Hope it works out for all languages

**Comment by sand1024** [comment]
yep, that was exactly my original intent - yet there is a bug in implementation I didn't notice.

**Comment by dxli** [comment]
I disabled the PenPallet by default.

You can remove the setting, or enable it by:

```
[CustomToolbars]
UsePenPallet=1
```

**Comment by dxli** [comment]
Tools > Modify > Attributes, color is shown as "Unchanged";

Tools > Modify > Properties, color is shown as the current value.

Two behavior is good (for different usages). Closing this one.
