### ISSUE TITLE
Hatch and construction layer

### ISSUE THREAD

**Issue by sand1024** [LibreCAD/LibreCAD#1773]
Hi! 
just found an interesting behavior. 

1) Hatch is created
2) Layer is marked as construction layer
3) Visual mess related to hatch lines (that become construction lines too) on the screen.... 

I'm not sure whether it's intentional, however, I suppose lines used for drawing hatch should not be considered as construction ones? 
Otherwise, it looks really messy...

Hatch
<img width="1692" alt="hatch no construction" src="https://github.com/LibreCAD/LibreCAD/assets/1469803/d62f386a-776a-4144-a165-439b2d89f810">

Hatch with construction layer enable

<img width="1692" alt="hatch constructuion layer" src="https://github.com/LibreCAD/LibreCAD/assets/1469803/fb92301f-a18e-4ea5-a4a8-4c744180af6a">

Reproduced on 
Version: 2.2.0
Compiler: GNU GCC 12.2.0
Compiled on: Dec 17 2022
Qt Version: 5.12.11
Boost Version: 1.75.0
System: Windows 10 (10.0)

And on current snapshot from master

**Comment by dongxuli-concord-design** [comment]
We can disable this one. 

The construction layer behavior is controlled at drawing time, rs_line::draw()

Maybe, we can get a better design here.
