### ISSUE TITLE
Request to add a simple resize tool.

### ISSUE THREAD

**Issue by NabilAKROUD** [LibreCAD/LibreCAD#1777]
### Expected behavior
I miss a tool to RESIZE objects by selecting, for example, two points: the initial and the final.
I created a simple shape in PowerPoint imagining how it should work.
The tool would greatly simplify the work when the drawing is too large and would avoid using [cross your heart](https://en.wikipedia.org/wiki/Cross-multiplication) method , which always leaves much to be desired.

### Operating System and LibreCAD version info
Any

https://github.com/LibreCAD/LibreCAD/assets/32953485/34678084-ae64-4e67-b01f-d9d54c06b1e8

**Comment by lordofbikes** [comment]
This is exactly, what Modify - Scale does.
https://docs.librecad.org/en/2.2.0_a/ref/tools.html?highlight=scale#modify

**Comment by NabilAKROUD** [comment]
Thanks for your quick response,
I've been trying to figure out how to scale from a _REF_ point to a _TARGET_ point and am not getting any satisfactory results.
unlike the _[Move/Copy Tool]_ which asks for two points _REF_ and _TARGET_, the _[Scale Tool]_ always asks for a _REF_ point and a scale _FACTOR_. To get that _FACTOR_ I use the _[Point to Point Distance tool]_ tool to get the _FACTOR_ (e.g. 60.186/60.162) but I always have a small mismatch.

Thank you and sorry for the inconvenience if I'm not doing things right.

**Comment by lordofbikes** [comment]
Sorry, my bad. Seems I've mixed up things, Rotate works this way, with two points, I'd expected, that Scale works the same way. Or maybe it was changed in the past and my memories fooled me.
Now that I've tried myself, I can confirm, that Scale only works with one reference point and the options dialog.

But this cuts both ways, for the Rotate tool we have regularly requests to change it to use one reference only, because entering the parameter in the dialog is more accurate.

**Comment by dxli** [comment]
@NabilAKROUD 

We can add a button to the scale dialog, so the end user can select a reference and a target point to fill the numbers automatically.

**Comment by NabilAKROUD** [comment]
It would help. 
Thanks ☺️

**Comment by dxli** [comment]
I am in the process of implementation, but looks like I get a busy week ahead. Will try to get it work by this weekend.

**Comment by dxli** [comment]
The implementation is ready for testing.

A button is added next to the factor input fields. If you gets a better icon for the button, please upload an SVG version here, or create a pull request.

**Comment by dxli** [comment]
Question: do we need to consider maintaining aspect ratio(isotropic) in the new methods? 

If the x/y lead to different factors, it's not clear on which one to use, if isotropic scaling is intended

**Comment by NabilAKROUD** [comment]
Great question 🤔
To avoid losing functionality in the unforeseen future, I would leave both tools, that is, implement the new resize tool without removing the current one.
... and then if it is seen that the current one is redundant during beta testing, it would be removed before releasing the stable version.

**Comment by dongxuli-concord-design** [comment]
That's not actually my question. 

My question is:

1, if user chooses isotropic scaling in dialog, then click "find factors";
2, user select source and target points. 

Currently, the isotropic selection is ignored, if points lead to different scaling factors in xy- directions. 

To improve:

If isotropic scaling is set, the target selection is limited on the line by the center and the source points;

Some minor issues: avoid selecting the center as source or target;

More improvement: allow selecting two source points and two target points (by auto selection xy- directions of the scaling), so the scaling is defined by points not by the current coordinate system.

**Comment by NabilAKROUD** [comment]
What this tool does is incredible 🤩.
It does exactly what I was looking for and more.
thank you!!!!!
![image](https://github.com/LibreCAD/LibreCAD/assets/32953485/2ebbf6da-103a-4109-9cd2-8e062c9a0575)

**Comment by dxli** [comment]
Hi @NabilAKROUD,

The current behavior is chosen to based on the  easiest for implementation by reusing the current "scale" method, so there's no change to previous scaling workflow for scaling by ratios, where a reference point is not necessary.

It's interesting to investigate how to provide behaviors for other transforms:

1, isometrics (translation, rotation, and mirroring) by reference and target;
2, other offline transforms: scale, shear, perspective, etc.

**Comment by NabilAKROUD** [comment]
Hello again, 
it's possible to force the target point to snap to the "Snap selection"

https://github.com/user-attachments/assets/0d5d0c7c-fdc8-4240-8f04-2c403473ba50
