### ISSUE TITLE
Delete an overlapped node (vertex) 

### ISSUE THREAD

**Issue by NabilAKROUD** [LibreCAD/LibreCAD#1788]
Hi!

Is there a way to select a vertex from the overlapping vertices whether it is a line or a polyline?

For the purpose of the demo video, I tried overlapping the nodes and although you can see the number of vertices of the polylines in the status bar when the vertices overlap, I haven't found a way to separate them later.

https://github.com/LibreCAD/LibreCAD/assets/32953485/d1323a18-28b5-467a-af96-0229924b8a3f

Thank you!

**Comment by dongxuli-concord-design** [comment]
Did you try exploding?

**Comment by NabilAKROUD** [comment]
Thanks @dxli, it was what I was looking for. 
your steps are helping me 🫱🏻‍🫲🏽
