### ISSUE TITLE
從現有的線段創建聚合線指令 此功能能否框選所有的雲行線後一次全部連接

### ISSUE THREAD

**Issue by AK5978** [LibreCAD/LibreCAD#1789]
從現有的線段創建聚合線指令 此功能能否框選所有的雲行線後一次全部連接

**Comment by lordofbikes** [comment]
This is possibly just a _how can I_ question.
I recommend to ask in the forum, https://forum.librecad.org.
Using an online translator and post in English increases the chances for an answer significantly.
Also add more details.
