### ISSUE TITLE
Extended axis lines disappears if origin is out of canvas

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1870]
### Expected behavior

Extended axis lines should be shown, even origin is moved out of actual window canvas:

- if origin is moved _horizontally_ out of actual window canvas — extended Y axis line visible;
- if origin is moved _vertically_ out of actual window canvas — extended X axis line visible;
- if origin is moved _horizontally and vertically_ out of actual window canvas — no axis lines visible.

### Observed behavior

Extended axis lines disappears when origin is moved out of actual window canvas in all cases.

### Steps to reproduce or sample file

1. Enable _"Extend axis lines"_ in _"Current drawing > Grid"_ preferences;
2. Pan canvas horizontally or vrtically to move origin out of actual window canvas.

Screencast:
[simplescreenrecorder-2024-08-31_14.18.41.webm](https://github.com/user-attachments/assets/c5673ba4-ba14-41b9-9e24-6ccf9c027f8a)

### Operating System and LibreCAD version info

- Version: 2.2.2_alpha1-151-g614f82dc
- Compiler: GNU GCC 9.4.0
- Compiled on: Aug 31 2024
- Qt Version: 6.6.3
- Boost Version: 1.71.0
- System: Debian GNU/Linux 12 (bookworm)

**Comment by sand1024** [comment]
oh, what a nighty bug... thank you for reporting, it's weird that I've relied on merge and missed it. 
Will be fixed in next build.

**Comment by sand1024** [comment]
@app4soft  - please check and close if it works fine now
