### ISSUE TITLE
Parts of drawing exported to PDF are missing after choosing to automatically fit to page

### ISSUE THREAD

**Issue by ksio89** [LibreCAD/LibreCAD#1897]
### Expected behavior
The whole drawing is preserved after clicking on "Fit to Page" and then exported to PDF

### Observed behavior
Parts of the drawing are not present in PDF document after clicking on "Fit to Page". I have to choose a slight smaller ratio so the whole drawing is visible, even when paper margins are set to 0.

### Steps to reproduce or sample file
1. create a drawing
2. on Print Preview, click on "Fit to Page" button to automatically adjust the drawing to the paper size configured and calculate the print scale 
3. export the drawing as PDF
4. parts of the deawing are missing.

### Operating System and LibreCAD version info
Version: 2.2.1_rc3-23-g05f8dc7f
Compiler: GNU GCC 12.2.0
Compiled on: Sep 17 2024
Qt Version: 5.15.2
Boost Version: 1.75.0
OS: Windows 11 Version 23H2

Here are some screenshots to illustrate the issue:

1. Print Preview window, showing the drawing of an A3 page drawn at 1:1 scale
2. PDF of the drawing at 1:1 scale, showing that the bottom line of the frame and corner marks were discared
3. same drawing, but at 1:2 scale, the whole drawing was preserved on the PDF document

![LibreCAD print preview](https://github.com/user-attachments/assets/0738464b-62e8-4ce5-8c0c-4bdb21a31e4f)
![A3 100%](https://github.com/user-attachments/assets/50538030-7778-46bc-9acf-bc32f3bc5049)
![A3 50%](https://github.com/user-attachments/assets/84c2c44f-03c6-49f1-8a32-fd02bbb91ed4)

As you can see, I have to choose a smaller scale (larger denominator) in order for the drawing to be preserved. It seems the PDF exporter functionality is applying non-zero margins after clicking on "Fit to Page" button.

**Comment by dxli** [comment]
Can you share the dxf?

**Comment by ksio89** [comment]
Here its, sorry for not uploading earlier. Though it happens with any drawing, it's easier to reprodue on a drawing at 1:1 scale. On build 2.2.0.2, the frame is visible, but the corner marks are only partially preserved.

[Legenda A3, paisagem final.zip](https://github.com/user-attachments/files/17067894/Legenda.A3.paisagem.final.zip)

![A3 100% (2 2 0 2)](https://github.com/user-attachments/assets/f8602667-3159-4c53-9529-0f6444292e66)

**Comment by dellus** [comment]
For me Legenda A3 exports to PDF completely in LibreCAD 2.2.1 rc23 in Linux appimage.

A Windows issue?

**Comment by ksio89** [comment]
Might be, I will test on a Linux virtual machine.

**Comment by ksio89** [comment]
Thank you for looking at the issue, but unfortunately parts of the drawing are still missing on latest RC build. The frame bottom line is now present, but the corner marks are still only partly rendered, exactly as on 2.2.0.2. The PDF looks the same as the last screenshot I uploaded, so no need to upload it again. Here is another screenshot comparing print preview window on latest 2.2.1 RC build with the exported PDF of a drawing on an A4 page, also with zero margins:

![A4](https://github.com/user-attachments/assets/bf5d6973-cd46-49f7-a1a2-6c6a61bb3e6c)

And why the console says this after clicking on Fit to Page, even though the paper size is set to A4 dimensions?


``Warning:: Paper size less than 10mm. Paper is too small for fitting to page
Please set paper size by Menu: Edit->Current Drawing Preferences->Pape``

![Paper](https://github.com/user-attachments/assets/a923cb16-85e4-4e47-a533-6fc187986e42)

**Comment by ksio89** [comment]
The message is no longer shown, but the margins isuse still not, sadly.

**Comment by dxli** [comment]
@ksio89 

this is an actual bug. When printing/exporting (two different things by our implementation), the output needs to follow user drawing settings on paper size and margins.

This bug happens because the way Qt handles paper sizes and margins. Our way was good for Qt4, but since Qt5, our settings became recommendations, not  necessarily  used by Qt.

The current fix makes sure "Export PDF" will be using user settings, so everything should show up (instead of being cropped) in PDF.

If trouble persists in "Printing" (to PDF or not), we will port this fix to printing in the future.

**Comment by ksio89** [comment]
But then why is the bug not reproduced on Linux and Windows VMs that I've tested? They use the same version of Qt libraries.

FWIW, the cropping issue is also happening with the LibreCAD installation in my desktop PC running Windows 11. This bug seems completely random if you ask me, and so far seems to not affect virtual machine guests.

**Comment by dxli** [comment]
Qt provides a uniform interface for applications across platforms, so mostly, we, "write once, run everywhere".

However, sometimes, like printing, the underneath qt implementations do behavior differently for platforms. Qt printing actually splits into separate systems at quite high level, and leaving us, the qt user to having to split our usages to different platforms also.

For example, printing to files will rely on printer drivers on different OSs, while exporting PDF will rely on qt pdfwriter.

**Comment by app4soft** [comment]
> I'm glad to report that this issue has been fixed on latest alpha build (2.2.2_alpha1-172-gb5de5c97), thank you very much!

If so, You, as author of this issue report, may close actual issue thread as "Done".

> Now the only stopping bug AFAIK that needs to be fixed is https://github.com/LibreCAD/LibreCAD/issues/1864, hope it doesn't take too long.

Its probably fixed already, see: https://github.com/LibreCAD/LibreCAD/issues/1864#ref-commit-dba58f3
