### ISSUE TITLE
Add option to hide "Close tab" icon

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1904]
### Expected behavior

LibreCAD should has a checkbox option to hide "Close tab" icons on the tabs via menu *"Drawings > *`[*]`* Hide "Close tab" icons"*.

### Observed behavior

Actually LibreCAD in "Tabs mode" has tabs with "Close tab" icons and context menu "Close" (on RMB click). Keeping such icons on tabs may results in closing tabs of open docs by curios clicks, and its waste of space in tabs bar as well. User should be able to customize this behavior

### Operating System and LibreCAD version info

- Version: 2.2.2_alpha1-173-g8640f77a
- Compiler: GNU GCC 9.4.0
- Compiled on: Sep 28 2024
- Qt Version: 6.6.3
- Boost Version: 1.71.0
- System: Debian GNU/Linux 12 (bookworm)

**Comment by sand1024** [comment]
support included into last alpha (settings in Application preferences->Defaults tab)
