### ISSUE TITLE
Allow double click on Layer Lists layer name to open layer settings dialog

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1905]
Suggesting to maybe add the ability to be able to double click on a layer name in the "Layers List" widget which would open up that layers "Layer Settings" dialog box to be able to change its properties.

Thank You

**Comment by sand1024** [comment]
This is supported by Layer Tree Widget - actually, I suppose Layer List stays rather for compatibility reasons...

**Comment by Questions2000** [comment]
Okay
