### ISSUE TITLE
Entity Properties does not appear to do anything

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1908]
Linux Debian Based
LibreCAD-2.2.2_alpha1-172-gb5de5c97.AppImage

Tools - Info - Entity Properites

This does not appear to do anything, not sure if I am not using this correctly?
Can anyone confirm that this is not working?

Thank You

**Comment by sand1024** [comment]
Well, in order this action work correctly, it's necessary:
1) Enable Entity Info widget (probably I'll invoke it automatically later on action's invocation)
2) Select entity. 

If Entity Info widget is enabled, Entity Property may be also invoked on mouse move (according to settings of the widget), or with selecting/hovering entity with CTRL. 

Actually, here are more details for this tool:

https://github.com/LibreCAD/LibreCAD/pull/1779
