### ISSUE TITLE
Capitalize Command Line floating text header label

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1910]
I just noticed that if you make the Command Line widget a floating window, the header does not say "Cmd" it actually says "Command line"
Would anyone be willing to capitalize the "L" in "line" to match the "title/proper" case labels used by all the other widget header labels.

Also if my suggestion found in the following post gets added in the future, would also make proper case when CL is docked to sides. #1909

Thank You

**Comment by dxli** [comment]
Just wondering:

Do we really want to say "Command Line" instead of "Command" for a floating command window?

"Command" is more consistent with "Cmd", where abbreviation is used to save space.
