### ISSUE TITLE
Startup screen image does not corresponds build version

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1913]
### Expected behavior

Startup screen image should corresponds to the LibreCAD version its starting.

cc @dxli @sand1024

### Observed behavior

I once has been experimenting with setting "Dark" (`librecad01_dark.png`) startup image and it was set to use in `2.2.2_alpha` CI builds with the next workaround:

- https://github.com/LibreCAD/LibreCAD/blob/a03184f4f3dba225e51f0e85e29fef09eb8331a7/.github/workflows/build-all.yml#L41-L48
- https://github.com/LibreCAD/LibreCAD/blob/master/desktop/media/splash/librecad01_dark.png

With some later commits in `master`, my workaround in `build-all.yml` is now ignored by CI and the latest `2.2.2_alpha` startup screen image now replaced with a "BETA" (`splash_librecad_alpha.png`) startup screen image in latest builds:
- https://github.com/LibreCAD/LibreCAD/blob/master/librecad/res/main/splash_librecad_beta.png

But just now, the version in `master` was set to `2.2.2 alpha1`:
- https://github.com/LibreCAD/LibreCAD/commit/a03184f4f3dba225e51f0e85e29fef09eb8331a7

So, if my workaround with "Dark" splash is ignored (intentionally, or by side effect of some commits), it might good to setup CI to bundle correct splash screeen according LibreCAD version its building binary for.

> [!NOTE]
>"ALPHA" (`splash_librecad_alpha.png`) splash image exists in repo too:
>
> - https://github.com/LibreCAD/LibreCAD/blob/master/librecad/res/main/splash_librecad_alpha.png

### Steps to reproduce or sample file

![Screenshot_2024-10-04_01-07-47](https://github.com/user-attachments/assets/636d4acf-c918-41eb-a60b-c4195f3d59e5)

### Operating System and LibreCAD version info

- Version: 2.2.2_alpha1-174-ga03184f4
- Compiler: GNU GCC 9.4.0
- Compiled on: Oct  3 2024
- Qt Version: 6.6.3
- Boost Version: 1.71.0
- System: Debian GNU/Linux 12 (bookworm)

**Comment by app4soft** [comment]
@dxli Latest commit solves issue only partially: its correct now for startup splash, but in "About" dialog it still shown wrong.

![Screenshot_2024-10-08_22-03-29](https://github.com/user-attachments/assets/b58c7015-aec0-47cc-a377-227b07b3ef49)

![Screenshot_2024-10-08_22-01-11](https://github.com/user-attachments/assets/247677aa-1bfd-4781-b6bc-9acf69c764c2)

Also, I propose to show in "About" dialog stripped in a half splash as a banner, and here are templates for about banner:

![about_light](https://github.com/user-attachments/assets/7bc31236-70ca-45cd-8927-254496a7688c)

![about_dark](https://github.com/user-attachments/assets/df6f7f91-7100-4993-8648-099fa72952e5)

And resulted look for "About" dialog of "alpha" build:

![LibreCAD-about](https://github.com/user-attachments/assets/9d7d5c0a-0d5f-472c-ae1f-a6a46fa48bc5)

**Comment by app4soft** [comment]
And here is comparison of "About" dialogs in `2.2.0.1` (release/stable) and `2.2.2.2` (alpha)

![LibreCAD-about](https://github.com/user-attachments/assets/bf86100a-d526-4f63-badf-60ae728e2162)

**Comment by app4soft** [comment]
@dxli, this issue almost solved.

The only thing left is to set "About" dialog to fit its minimal size, because actually there are a lot of space in vertical dimension (see screenshots).

### Actual behavior
![Actual about dialog](https://github.com/user-attachments/assets/8984b679-7dfa-417c-a5ed-06083f7551c4)

### Expected behavior
![Expected about dialog](https://github.com/user-attachments/assets/e28f6d70-cf0a-475e-94d0-125a44099a6a)

**Comment by sand1024** [comment]
> The only thing left is to set "About" dialog to fit its minimal size, because actually there are a lot of space in vertical dimension (see screenshots).

Well, It might be that size of the dialog was remembered from previous invocation (with larger logo).

Could you please resize the dialog to required size, close it and open again (of course, my consideration makes sense if appropriate options for persisting dialogs positions/sizes is checked)

**Comment by app4soft** [comment]
> Could you

After https://github.com/LibreCAD/LibreCAD/commit/8ed4c62238f9de6ed7cb67ad0a18434f842878b9 there was no issue anymore.
