### ISSUE TITLE
Set Layer Tree new layer dialog to open with focus in the name field

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1921]
If possible, set the Layer Tree new layer dialog to open with focus given in the name field automatically so user can instantly type in new layers name.  I believe this is how the Layer List widget used to function.

Thank You

**Comment by Questions2000** [comment]
@sand1024 
I tested this and it appears to be updated if you want to close this?
Thank you for making this update.

**Comment by sand1024** [comment]
yes, this is fixed in last update, so the issues may be closed. 
This one as well https://github.com/LibreCAD/LibreCAD/issues/1912
There is a button in toolbox near to draft button and it is used disabling screen width of lines, named "Draft Lines"

**Comment by Questions2000** [comment]
Oohhh I didn't know about that one, thank you for updating that as well :)
