### ISSUE TITLE
When new statusbar is turned off the setting does not save

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1931]
### Expected Behavior
If the new statusbar (blank bar at bottom) is turned off, to save/remember this setting for the next time LC is launched.

### Observed Behavior
When you turn off this new statusbar, the setting does not appear to save and it shows up every time LC is launched again.

### Steps To Reproduce
-Legacy statusbar setting is set to off (unchecked)
-Right click on any toolbar to open context menu
-Uncheck "Statusbar" to hide the blank statusbar at the bottom of screen.
-Close LC completely
-Launch new LC
-Notice at the bottom the new statusbar appears again, the state of it does not appear to be saved.

### Operating System and LibreCAD Version
LibreCAD-2.2.2_alpha1-181-g8b3cf9ca.AppImage
Linux - Debian 12 based distro
GTK based Desktop Environment

**Comment by sand1024** [comment]
included into last alpha, may be closed

**Comment by Questions2000** [comment]
I tested this out yesterday and confirm that this works great, thank you for this update.
