### ISSUE TITLE
Instruction text above command line field does not remove once command is complete

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1933]
### Expected Behavior
When you use a tool the “Command:" text above the command line field in the past would change to instructions for that active tool.
Once that tool was escaped out of, then that text above the command line field would go back to reading “Command:” because the tool was no longer active.
This is one, if possible I hope can be looked at soon, can make things really confusing when trying to test things out because it always appears as if a command is active.

### Observed Behavior
-Older versions performed as mentioned in Expected Behavior
-In recent versions the "Command:" text did not change at all, stayed "Command:"

-Now currently when you escape out of the active tool, that text shows the last instruction given for that tool.
It does not go back to reading “Command:” as it has in the past.

### Steps To Reproduce
Use any tool, for example the “Line" tool.
Draw some quick lines and you will notice the text above the field showing instructions.
Escape out of that tool and you will notice the text instruction remains instead of returning to “Command:” text
It will say something like “Specify the first point” even thought the line tool is no longer active.

### Operating System and LibreCAD Version
LibreCAD-2.2.2_alpha1-181-g8b3cf9ca.AppImage
Linux - Debian 12 based distro
GTK based Desktop Environment

**Comment by sand1024** [comment]
oh, that's a really good point - thank you for reporting it. 
Yes, that's definitely a bug - will be fixed in the next update, I suppose.

**Comment by sand1024** [comment]
fixed, please check in last alpha and close

**Comment by Questions2000** [comment]
@sand1024 
Tested this one out yesterday, ahh thank you so much for this, this is much better :)
This one was making things a little confusing, always felt like I was in a command :)
Also like the text change to “Enter Command:”
Thank you again
