### ISSUE TITLE
"TEXT" objects are ignoring line width setting

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1935]
### Expected behavior

"TEXT" objects should follows line width setting.

### Observed behavior

"TEXT" objects are ignoring line width setting and is always shown 1px width.

"MTEXT" objects in the same time works correctly.

### Steps to reproduce or sample file

1. Create "TEXT" object;
2. Apply different line width;
3. Zoom in to see real scale line width.

On screenshot, upper is the "TEXT" and lower is the "MTEXT" — both with the same line width.
![librecad-width](https://github.com/user-attachments/assets/e9a5844e-bc62-4d3b-a260-6888d3844ab6)

### Operating System and LibreCAD version info

Version: 2.2.2_alpha1-188-g6e86fe5d<br/>Compiler: GNU GCC 9.4.0<br/>Compiled on: Oct 23 2024<br/>Qt Version: 6.6.3<br/>Boost Version: 1.71.0<br/>
System: Debian GNU/Linux 12 (bookworm)

**Comment by sand1024** [comment]
I think it is fixed in latest alpha (193), please retest and close
