### ISSUE TITLE
Statusbar Toolbar - Issues with mouse hover tag for Current Layer

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1944]
BUG REPORT

### Expected Behavior
In the Statusbar toolbar when you hover your mouse over each item an info tag appears.
Each Statusbar toolbar section/pieces info tag should appear no matter what text the mouse is hovering over, whether it be the top label text or the value text underneath it.

### Observed Behavior
I noticed some issues with the info tags for some of the section/pieces of the Status toolbar.

`Current Layer`
-If you hover over “Current Layer” text you see a tall narrow empty tag, contains no text.
-If you hover over the layer name underneath it, then you see a tag that says “Name of current active layer" in a very small font size (compared to the font size used in all the other tags).

`Selected`
-If you hover over “Selected” text no tag appears at all
-If you hover over the number underneath it, then you see a tag that says “Number of selected entities” in a very small font size

`Total Length`
-If you hover over “Total Length” text no tag appears at all
-If you hover over the number underneath it, then you see a tag that says “Total length of selected entities” in a very small font size

### Operating System and LibreCAD Version
Linux / Debian 12 based distro / GTK based Desktop Environment
LibreCAD-2.2.2_alpha1-207-g7838da61.AppImage

**Comment by IamLRBA** [comment]
Hello @Questions2000 , is this issue still open?
I'd like to contribute to it

**Comment by sand1024** [comment]
@Questions2000 
addressed in last AppImage

**Comment by Questions2000** [comment]
Tested and appears to be corrected.
Thank You for fixing this reported issue.
