### ISSUE TITLE
Orange layer colors are out of rainbow order in the drop down menu

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1948]
The two newly added orange colors appear to be out of rainbow order in the drop down menu.  They are showing up after magenta.
There are two colors doubled in the location orange would go, which I reported here #1949

### Operating System and LibreCAD Version
Linux / Debian 12 based distro / GTK based Desktop Environment
LibreCAD-2.2.2_alpha1-194-g744fa227.AppImage

**Comment by Questions2000** [comment]
Issues
1948 (this one)
1949
1952
are all regarding the adding of an "Orange" layer.
This was kind of left in a strange state, have held off on asking this for a while, but have been wondering....
What does a "restriction" label mean?

**Comment by sand1024** [comment]
@Questions2000 
addressed in last AppImage

**Comment by Questions2000** [comment]
Tested and appears to be corrected.
Thank You for fixing this reported issue.
