### ISSUE TITLE
Layer dialog color drop down contains double instances of certain colors

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1949]
I noticed that the Layer dialog color drop down menu contains doubles of certain colors.
Yellow & Dark Red

Related Issue: #1948
(I think this was suppose to be where Orange & Dark Orange were going to go)

### Operating System and LibreCAD Version
Linux / Debian 12 based distro / GTK based Desktop Environment
LibreCAD-2.2.2_alpha1-194-g744fa227.AppImage

**Comment by sand1024** [comment]
@Questions2000 
addressed in last AppImage

**Comment by Questions2000** [comment]
Tested and appears to be corrected.
Thank You for fixing this reported issue.
