### ISSUE TITLE
Orange layer colors contrast

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1952]
### Expected Behavior
I tested out the new orange layer colors.
It seems that there is very little contrast between the light orange and the dark orange, in comparison to the contrast used with all of the other colors.  If agreed maybe can update with the following color codes provided.  I believe the orange code used is the same, but the dark orange color code is different then the one used.  With the dark orange I used the orange #ffa500 code and brought its fader on the right side of the color picker down to 50% which I believe is how all the other dark color versions for the other colors were achieved.

ORANGE
#ffa500
DARK ORANGE
#7f4e00

### Operating System and LibreCAD Version
Linux / Debian 12 based distro / GTK based Desktop Environment
LibreCAD-2.2.2_alpha1-194-g744fa227.AppImage

Thank You

**Comment by sand1024** [comment]
@Questions2000 
addressed in last AppImage

**Comment by Questions2000** [comment]
Tested and appears to be corrected.
Thank You for fixing this reported issue.
