### ISSUE TITLE
Break Divide tool sets remaining pieces to overridden color

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1957]
BUG REPORT
I apologize I am trying to hold off on creating new posts but this is one that could cause issues for users using continuous release version.

### Observed Behavior
If you use the Break/Divide tool, any pieces of drawn items that remain on screen end up having layer color overridden instead of leaving color "By Layer".

### Operating System and LibreCAD Version
Linux / Debian 12 based distro / GTK based Desktop Environment
LibreCAD-2.2.2_alpha1-198-g8919ed83.AppImage

**Comment by sand1024** [comment]
@Questions2000 
`I apologize I am trying to hold off on creating new posts `
Oh, no need to do this - if you see some issue - please report it. 

`drawn items that remain on screen end up having layer color overridden`
Yes, this seems to be a bug... resolved color is set instead of "by layer" one.

**Comment by sand1024** [comment]
@Questions2000 
addressed in last AppImage

**Comment by Questions2000** [comment]
Tested and appears to be corrected.
Thank You for fixing this reported issue.
