### ISSUE TITLE
Named Views widget borders appear thicker than other widgets

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1968]
GRAPHICAL BUG

### Observed Behavior
New widget “Named Views” has been added, thank you for adding this, very nice feature.
I just noticed that the borders of the widget on left, right and bottom are thicker then the borders used on all the other widgets.

### Operating System and LibreCAD Version
Linux / Debian 12 based distro / GTK based Desktop Environment
LibreCAD-2.2.2_alpha1-207-g7838da61.AppImage

**Comment by sand1024** [comment]
ouch.... yes, you're right - this is a bug and I'll adjust this

**Comment by sand1024** [comment]
@Questions2000 
addressed in last AppImage

**Comment by Questions2000** [comment]
Tested and appears to be corrected.
Thank You for fixing this reported issue.
