### ISSUE TITLE
Layer visibility

### ISSUE THREAD

**Issue by eworm-de** [LibreCAD/LibreCAD#253]
I have some problems with layer visibility, some layers seem to "depend" on each other, so making one invisible makes everything invisible. Take this example:
http://www.eworm.de/tmp/qr-code-anhaenger.dxf
- select block "Vorderseite" or block "Rueckseite"
- edit active block in separate window
- play with the layer visibility

Tried with Qcad, works as expected there.

**Comment by sjfloat** [comment]
Is it possible that this regressed? I'm still seeing this behavior in 2.1.2.
