### ISSUE TITLE
Back from Print Preview to a subwindow in always restore down state

### ISSUE THREAD

**Issue by csanyipal** [LibreCAD/LibreCAD#273]
Hi,

I have installed LibreCAD 2.0.0.alpha1 builded from source, using git.

When I have opened only one subwindow then from PrintPriview I get always maximised subwindow.

If I have opened two or more subwindows then from PrintPriview of second, third etc. subwindow I get always subwindows in 'restore down' state (not maximised and not minimised but that state between). From PrintPriview of first subwindow (when there are more subwindows opened) I get always maximised subwindow.

However when I click on the Print Preview button the button doesn't stay pushed and from the Print Preview I have to click on it twice to close Print Preview; click for the first time does nothing but the button stay 'pushed' and the second click close the Print Preview and the button come to the 'unpushed' state.

Is this a bug?

Regards from Pal

**Comment by r-a-v-a-s** [comment]
csanyipal, was this fixed for you?

**Comment by r-a-v-a-s** [comment]
I think I have fixed everything mentioned here. Let me know.

**Comment by u2fly** [comment]
@dxli @sand1024 

In latest 2.2.2-alpha, if click "Print Preview" once it opens print preview as a tab/subwindow, but if click "Print Preview" again tab splits into separate window.

Repeating this two steps produces more splitted separate windows.
