### ISSUE TITLE
Printing A0 page size to PDFCreator - only part of drawing is printed

### ISSUE THREAD

**Issue by flyasky** [LibreCAD/LibreCAD#274]
I open dxf file with maximun dimensions fits A0 page size.
I set A0 for document, open print preview and set scale 1:1 and move page to cover all drawing.
On printing I select PDFCreator.
As result I get only bottom-left part of drawing clipped in size approx A4 page.

**Comment by fa201** [comment]
@lordofbikes 
I cannot reproduce with
Version: 2.2.0-rc1-190-g51b21cc7
Compiler: GNU GCC 7.5.0
Compiled on: Mar 29 2020
Qt Version: 5.9.5
Boost Version: 1.65.1
System: Ubuntu 18.04.4 LTS

**Comment by DuncanLithgow** [comment]
None of the files are available to test. @flyasky please reopen if you still have this issue in the current version.
