### ISSUE TITLE
Error pa keystroke for paint parallel line

### ISSUE THREAD

**Issue by diegofrafer** [LibreCAD/LibreCAD#297]
In function keycodeToAction of file rs_commands.cpp:

    ... else if (c==tr("pa", "parallel")) {
        ret = RS2::ActionDrawLine;

It is correct?
Could It be?

 else if (c==tr("pa", "parallel")) {
        ret = RS2::ActionDrawLineParallel;.

**Comment by r-a-v-a-s** [comment]
All commands noted are working as expected in commit: https://github.com/LibreCAD/LibreCAD/commit/d1f7f92fe22f8863f7e8dc718c1c2e512ae7c0ac
