### ISSUE TITLE
DXF open from command line with old dxf parser

### ISSUE THREAD

**Issue by martinstingl** [LibreCAD/LibreCAD#303]
Start librecad with the filename as command line parameter:
librecad topo.dxf
There are no objects shown in the drawing

Open the same file with the file menu:
Now the drawing contents are shown.

It seems that "New drawing exchange" is not used with the command line but is the default setting.
The file topo.dxf can be downloaded from https://launchpadlibrarian.net/26365610/topo.dxf

**Comment by r-a-v-a-s** [comment]
What is the status of this?

**Comment by martinstingl** [comment]
Command line input and File Open now uses the same input method, so this can be closed.
