### ISSUE TITLE
Bad grid when zooming

### ISSUE THREAD

**Issue by martinstingl** [LibreCAD/LibreCAD#305]
Open the file inside that archive with "New drawing exchange" selected and zoom out. There are too many grid points shown, see the screenshot.
When opened with "QCad 1.x file" selected the grid works fine while zooming.
Even if the file is bad condition the grid should be presented correctly.
https://sourceforge.net/projects/martinstingl.u/files/dots.zip

**Comment by r-a-v-a-s** [comment]
Does QCad still generate this type of file? If not then I think these issues can be closed.

**Comment by atorrey** [comment]
The report I made didn't involve Q-Cad, but I think that given the age of the report, it can probably be closed as it isn't getting current complaints....
