### ISSUE TITLE
Printing no continios line

### ISSUE THREAD

**Issue by Valber** [LibreCAD/LibreCAD#334]
System Debian 7.0 amd64
LibreCAD
SCM Revision: 2.0.0alpha3-123-gd568c73
Compiled on: Jun 3 2012

When I print a no continuous line in PDF, they are shown by continios lines

Screen http://cs405826.userapi.com/v405826658/1b4/6-kR17yzqrg.jpg

**Comment by r-a-v-a-s** [comment]
Line segments are represented correctly in an exported PDF when I test.
I'll assume this was fixed.
