### ISSUE TITLE
snap to block elements does not work

### ISSUE THREAD

**Issue by steelman** [LibreCAD/LibreCAD#339]
In general snapping to block elements does not work with one execption: "Snap Distance". When on it is possible to snap to ends (or at some distance from them) of lines, otherwise blocks do not snap cursor in any way.

**Comment by r-a-v-a-s** [comment]
This was implemented.

**Comment by r-a-v-a-s** [comment]
I guess this was not implemented... not sure how it was working for me earlier. @_@

**Comment by fa201** [comment]
It is possible to snap on block.
Version: 2.2.0-rc3
Compiler: GNU GCC 9.3.0
Compiled on: Dec 21 2021
Qt Version: 5.12.8
Boost Version: 1.71.0
System: Ubuntu 20.04.3 LTS
