### ISSUE TITLE
Installing on Ubuntu 12.04.1 LTS, W: Duplicate sources.list entry

### ISSUE THREAD

**Issue by csanyipal** [LibreCAD/LibreCAD#347]
Hi,

on my Ubuntu 12.04.1 LTS system when I added PPA repository:
$ sudo add-apt-repository ppa:librecad-dev/librecad-daily

and run
sudo apt-get update

I get Warnings:
W: Duplicate sources.list entry http://archive.canonical.com/ubuntu/ precise/partner amd64 Packages (/var/lib/apt/lists/archive.canonical.com_ubuntu_dists_precise_partner_binary-amd64_Packages)
W: Duplicate sources.list entry http://archive.canonical.com/ubuntu/ precise/partner i386 Packages (/var/lib/apt/lists/archive.canonical.com_ubuntu_dists_precise_partner_binary-i386_Packages)

How can I solve this problem? Can I just ignore it?
Is this a bug?

**Comment by r-a-v-a-s** [comment]
Not something we can address.
