### ISSUE TITLE
DWG format support on LibreCAD -- any solution or plugin available?

### ISSUE THREAD

**Issue by ghost** [LibreCAD/LibreCAD#351]
Dear Sir / Mdm,

  Librecad is a project that I have been observing for close to two years, and apart from the observation that it doesn't support DWG format, that brings Autocad users on board with some ease, the user interface reminds me of a Autocad R12, R13, and R14 that I once came across years ago as a student..

**Comment by Rallaz** [comment]
LibreCAD can now open dwg files

**Comment by BitPuffin** [comment]
Great!

This should really *really* be bragged about on the homepage and maybe even in the readme on github. Because trust me pretty much any architect or whatever out there will look at a software and decide whether it's worth trying or not based on if it supports DWG or not :)

**Comment by seiferflo** [comment]
@Rallaz I'm sorry but how are we supposed to do that? 
I'm probably mistaken but I still haven't found how to open a dwg in LibreCAD 2.0.7

**Comment by kromanenko** [comment]
This feature is not included into binary release yet. You can build fresh LibreCAD from sources.

**Comment by Rallaz** [comment]
In binary, to install, only for linux
daily buid for ubuntu:
https://launchpad.net/~librecad-dev/+archive/ubuntu/librecad-daily
or for openSuse - Fedora:
http://download.opensuse.org/repositories/home:/Rallaz/

**Comment by dxli** [comment]
please note: daily builds for ubuntu has been broken for months. a maintainer is needed.

**Comment by hinakhan09** [comment]
Download Now https://pclife.info/librecad-crack/
