### ISSUE TITLE
Grid "Auto" doesn't work

### ISSUE THREAD

**Issue by atorrey** [LibreCAD/LibreCAD#352]
Version: master
SCM Revision: 2.0.0beta1
Compiled on: Jan 3 2013

Original drawing created in rev. 1.01 on Kubuntu

If I have program preferences set to automatically scale grid, and minimum grid spacing to 0, and drawing preferences to show orthogonal grid, and auto spacing, I get no visible grid.  If I set the grid to .1" spacing, I see the grid, but as I zoom out, the grid intensity becomes so high that it obscures the actual drawing.  (in 1.01, the .1" dots went away as you zoomed out)  My drawing is of an item about 4" x 4" x 8" so .1" grid spacing works well when I'm zoomed in close, but it's failure to auto-space change is a problem.

**Comment by r-a-v-a-s** [comment]
> Perhaps it might be a good thing to change the default on the grid spacing to 10

This is now the default.
