### ISSUE TITLE
broken line dimensions to BIG

### ISSUE THREAD

**Issue by atorrey** [LibreCAD/LibreCAD#353]
Version: master
SCM Revision: 2.0.0beta1
Compiled on: Jan 3 2013

Original drawing created in rev. 1.01 on Kubuntu

I use a mix of line types, in addition to continuous, I have dashed, dotted, and dash-dot lines that I use to signify drawing features...  In some cases they are the default line type for the layer, in others they are a particular line in a layer with the default set to continuous 

In 1.01, I used the plain dot, dash, or dash-dot sizes, and the results were quite satisfactory.  The dots and dashes were sized and spaced such that the lines were very clear, with just big enough breaks that one could see the difference in the line types.  The sizing of the lines seemed to self adjust as one zoomed in and out, so they always looked about the same.

In the upgraded version, the dots and dashes are HUGE, with big spaces between them, to the point where it is hard to tell that they are actually lines.

I edited all the line types, to use the ---(small) version, which helped some, but the lines are still WAY to coarse, making it hard to see intersections, judge angles, and so on.  When zooming out, the large dots and dashes can often be as big as the feature, so that the line either looks solid or disappears depending on whether the dash or the space lines up with it....

Can we get back the really SMALL dash / dot / dash-dot lines?

(I have not tried them, but I suspect the same issues may apply to the other types of broken lines)

**Comment by r-a-v-a-s** [comment]
Art, what is the status of this now?

**Comment by atorrey** [comment]
It appears fixed, many thanks....
