### ISSUE TITLE
Bypass selection menu if already have selected items to modify - suggestion

### ISSUE THREAD

**Issue by atorrey** [LibreCAD/LibreCAD#354]
This is a minor annoyance, that I think shouldn't be terribly hard to fix...

I find that if I want to modify an element in my drawing, I tend to select it first, then click the appropriate modify button.  Currently, this  drops me into the selection menu, and I have to click on the continue button to actually get to the screens that make the modifications....

This is an extra step that gets annoying over time.

It would be nice if the program could check to see if items have already been selected when a modify button is pressed, and if they have been, to bypass the selection menu.  If nothing has been selected, then it should continue the current behavior of going to the select menu.

**Comment by r-a-v-a-s** [comment]
Bypass selection has been implemented.
Deselect all can be accomplished with the Esc button or Ctrl+K.
