### ISSUE TITLE
Angle measurement won't do >180* values - please fix!

### ISSUE THREAD

**Issue by atorrey** [LibreCAD/LibreCAD#358]
When measuring the angles on an arc, I have not found it possible to get LibreCAD to print an angle greater than 180*, even though that is the value I am interested in for my drawing.

If I try moving the cursor to the outside area, the program draws the extra lines for the corresponding angle, and gives the smaller value.  It doesn't matter in what order I select the two lines of the angle.

I will grant that it is always possible to calculate the value of the opposite angle by subtracting from 360*, but the extra manual step shouldn't be needed.

The better program behavior IMHO would be for the program to give the value for the angle that matches the cursor position - i.e. <180 if the cursor is inside the angle, and >180* if it is outside the angle.

**Comment by r-a-v-a-s** [comment]
Is this regarding 
Dimension→Angular 
or 
Info→Angle between two lines
?

**Comment by atorrey** [comment]
I am 90% certain that it was 'dimension angular' - however IMHO having the program give the angle value dependent on the cursor location as I suggested in the original comment would be desirable for both functions.

This also appears to be fixed now - at least I just did a quick test drawing of an angle, and info gave both inside and outside angles, and the Dimension  allowed me to show both the inside and outside measurements (and also tried to draw the corresponding angles) depending on where I put the cursor.
