### ISSUE TITLE
spline optimization

### ISSUE THREAD

**Issue by markvdb** [LibreCAD/LibreCAD#360]
(I just mistakenly submitted this bug to sf.net. Sorry about the double reporting.)

This makes librecad choke:
http://glasno.st/ugis/prototype.dxf

librecad 1.0.1+nolibs-2~daily~natty1
libdxf lib 2.2.0.0-8~daily8~natty1

Is there anything I can do?

P.S. Thank you for your work on Librecad!

**Comment by markvdb** [comment]
The spline optimisation is still absent from LibreCAD 2.0.4 (the most recent Debian packaged version).

I haven't rebuilt librecad from the latest git source yet, but I _have_ checked the current issues list (no mention of spline optimisation), and I do not see any reference to a fix, so I would really like to see this issue reopened...

**Comment by r-a-v-a-s** [comment]
The file has almost 900,000 entities :astonished: 

I'm going to try make some optimizations... but that's simply a ton of entities that need processing.

The first thing I can do is make it only draw the bounding boxes while panning.
I've done it for text; and I've already tried it for splines, and your drawing pans at high speeds...
Is it too visually disruptive to do this for splines?

**Comment by markvdb** [comment]
Thank you for your good work on this. Much appreciated!

**Comment by r-a-v-a-s** [comment]
I've noticed your circles are actually splines,
and each one is 8k entities!

I'm curious, were you using a circle tool in another program?
Or did you purposefully use a spline tool to create the circles?
Converting them would definitely help.

**Comment by markvdb** [comment]
This was created in a non-free piece of software that I have no access to.
Corel Draw even originally, if I'm not mistaken. Being able to use the dxf
export in LibreCad is somewhat of a corner case, but a useful one I hope...

2016-06-21 21:53 GMT+02:00 ravas <notifications@github.com>:

> I've noticed your circles are actually splines,
> and each one is 8k entities!
>
> I'm curious, were you using a circle tool in another program?
> Or did you purposefully use a spline tool to create the circles?
> Converting them would definitely help.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/LibreCAD/LibreCAD/issues/360#issuecomment-227552227>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAviCLBfmTCYRBIGp0SEDzJewND66qoWks5qOEEfgaJpZM4AYBzD>
> .
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by DuncanLithgow** [comment]
The original file is no longer available. Please file a new bug if there are similar problems with the current version of LibreCAD.
