### ISSUE TITLE
Request: Package LibreCAD in Fedora

### ISSUE THREAD

**Issue by Andrew89** [LibreCAD/LibreCAD#362]
I notice the availability of LibreCAD in RPM packages. But it would be even nicer if Rallaz went ahead and submitted LibreCAD to Fedora package maintenance, and regularly maintained the package.

This would be much appreciated, if it is not too much trouble for Rallaz. Fedora has a near-total absence of quality CAD software. Only QCad CV is available, and that's abandonware.

**Comment by Osndok** [comment]
I'm pretty sure this is resolved/closable, as I actually found librecad through the fedora project.

<pre>
$ rpm -q --info librecad
Name        : librecad
Version     : 2.0.8
Release     : 1.fc22
Architecture: x86_64
Install Date: Sun 01 Nov 2015 01:06:03 PM CST
Group       : Unspecified
Size        : 5857336
License     : GPLv2 and GPLv2+
Signature   : RSA/SHA256, Sat 12 Sep 2015 03:06:21 PM CDT, Key ID 11adc0948e1431d5
Source RPM  : librecad-2.0.8-1.fc22.src.rpm
Build Date  : Fri 11 Sep 2015 11:49:50 AM CDT
Build Host  : buildhw-04.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://librecad.org/
Summary     : Computer Assisted Design (CAD) Application
Description :
A graphical and comprehensive 2D CAD application.
</pre>

**Comment by r-a-v-a-s** [comment]
2.1.0 is available.
https://apps.fedoraproject.org/packages/librecad/builds/

Github issues are things that can be closed by changing the repository.
Feel free to discuss anything at http://forum.librecad.org/
