### ISSUE TITLE
Qt5 json file format

### ISSUE THREAD

**Issue by TNick** [LibreCAD/LibreCAD#383]
Since [this commit](https://github.com/LibreCAD/LibreCAD/pull/378#commit-ref-e349899) the plug-ins are equiped with both Qt4 and Qt5 style macros. This is an invitation in the spirit of Rallaz's comment [here](https://github.com/LibreCAD/LibreCAD/pull/378#issuecomment-15108548) to argue about the content of the json files for plug-ins. Are there any required fields? Should we just remove them, since the FILE directive is optional?

References:
http://qt-project.org/doc/qt-5.0/qtcore/qtplugin.html#Q_PLUGIN_METADATA
http://qt-project.org/doc/qt-5.0/qtcore/plugins-howto.html

**Comment by r-a-v-a-s** [comment]
Apparently no one wants to argue... ;D
Because we have a [forum][1] it seems more appropriate for development discussions to be held there.

[1]:http://forum.librecad.org/
