### ISSUE TITLE
LibreDWG license compatibility

### ISSUE THREAD

**Issue by kxra** [LibreCAD/LibreCAD#392]
LibreDWG is GPLv3. QCad is GPLv2 and no later versions.

Please comment with other incompatible pieces, and relevant mailing list threads.

I have contacted RibbonSoft and will report back with their response.

**Comment by Rallaz** [comment]
LibreCAD can now open dwg files with its own library GPLv2+

**Comment by liufeijin** [comment]
> LibreCAD can now open dwg files with its own library GPLv2+

LibreCAD can't import dwg at all , a lot of bug and crash . PLS change to Libre DWG.
