### ISSUE TITLE
Feature Request: Layer Control

### ISSUE THREAD

**Issue by BitPuffin** [LibreCAD/LibreCAD#393]
Hello!

It appears that there is nothing like AutoCADs layer control in LibreCAD (unless I'm missing something).

What it is (according to my dad) is an extra box next to line type, line width and line color that shows the active layer of what you've selected (some line in the drawing or even a layer). So say you've selected a line, it will then show what layer it is on, and if you would like to move what you have selected to another layer then you can press the box and a drop down of all the layers appears and you can just move your way down and click on the layer you'd like to move the selected things to.

It would be really nice if this was added! Cheers.

**Comment by r-a-v-a-s** [comment]
Options->Application Preferences->Defaults
Enable "Modify layer of selected entities, at layer selection"
