### ISSUE TITLE
Point to new build instructions

### ISSUE THREAD

**Issue by dbenamy** [LibreCAD/LibreCAD#413]
It looks like the most up to date build instructions are in the readme which is shown at https://github.com/LibreCAD/LibreCAD.

The "From Source" tab on the site should link to there. Eg: the header on http://librecad.org/cms/home/from-source/linux.html.

Then you can remove the linux and windows build pages on the site.

**Comment by r-a-v-a-s** [comment]
GitHub issues are for things that contributors can deal with via git.

Also, we usually refer people to the wiki now:
http://wiki.librecad.org/index.php/LibreCAD_Installation_from_Source
