### ISSUE TITLE
Most menu entries are missing from HUD search results in Ubuntu (Unity)

### ISSUE THREAD

**Issue by agerber85** [LibreCAD/LibreCAD#420]
Prior to LibreCad 2.0, all menu entries could be accessed via Unity's HUD.  With 2.0, only entries from the File menu are there.

**Comment by r-a-v-a-s** [comment]
Can anyone using Unity tell/show us how this is working now?

**Comment by agerber85** [comment]
Yes.  It appears to all be working as it should now.  (Testing on 14.04.3
LTS.)

Thanks so much!
