### ISSUE TITLE
Feature Request: Automatic Scale of Dimensions

### ISSUE THREAD

**Issue by daemonTutorials** [LibreCAD/LibreCAD#421]
I've drawed something and added dimensions to it. Then I printed it out in a scale of "1:2" and the dimensions and the text are scaled with it.
So the dimensions are not longer exact 10mm away from the drawing, instead they are just 5mm away. And so on. 
My thought is, that you multiply the dimensions with the scale of the printout and the user enter the "real measures" of the dimensions. 

In the first image I added dimensions without scaling it manually up. In the second image I did it. I have multiplied the measures of the dimensions with 2. 

In the easiest case you could add a button that multiplies the dimension-measures "on-the-fly" because the print-preview is connected to the draw-viewport. That would be to heavy to seperate the views, or isn't it?

Image 1 -> Print out -> First dimension line is in real 5mm away from drawing on an A4-Paper
Image 2 -> Print out -> First dimension line is in real 10mm away from drawing on an A4-Paper
![weihnachtsbaum](https://f.cloud.github.com/assets/864633/1542941/472307c2-4d4e-11e3-825c-a77d42302c0d.png)
![weihnachtsbaum_corrected](https://f.cloud.github.com/assets/864633/1542942/4725eb90-4d4e-11e3-9fb1-ec87d4d12b1d.png)

**Comment by r-a-v-a-s** [comment]
Solution exists / no feedback from OP.
Armin, it might be nice to place your information somewhere on the wiki, if it is not.
