### ISSUE TITLE
Crash during startup on Mac OS X Lion (10.7.5)

### ISSUE THREAD

**Issue by effad** [LibreCAD/LibreCAD#435]
I have just downloaded 2.0.3 for Mac OSX Lion from source forge. When I try to start, LibreCAD crashes immediately.

This is the Log from the system.log:

Jan 12 16:57:49 Lothars-iMac ReportCrash[1589]: Failed to create CSSymbolicatorRef for launchd[1588]
Jan 12 16:57:49 Lothars-iMac ReportCrash[1589]: Failed to create dSYM-less CSSymbolicatorRef for launchd[1588]
Jan 12 16:57:49 Lothars-iMac com.apple.launchd.peruser.501[218] ([0x0-0xfd0fd].com.yourcompany.LibreCAD[1588]): Job appears to have crashed: Segmentation fault: 11
Jan 12 16:57:49 Lothars-iMac ReportCrash[1589]: Saved crash report for launchd[1588] version ??? (???) to /Users/lothar/Library/Logs/DiagnosticReports/launchd_2014-01-12-165749_Lothars-iMac.crash

An kernel.log says:
Jan 12 16:57:49 Lothars-iMac kernel[0]: Data/Stack execution not permitted: launchd[pid 1588] at virtual address 0x7fff5fc01000, protections were read-write

**Comment by turtlepa** [comment]
Did you by any chance, at some point, install os x server lion?  I have this error long after trying to remove os x lion server after i changed my mind on having it
Feb 24 09:52:41 mac ReportCrash[45343]: Saved crash report for launchd[48830] version ??? (???) to /Library/Logs/DiagnosticReports/launchd_2016-02-24-095241_localhost.crash
Feb 24 09:52:41 mac ReportCrash[45343]: Removing excessive log: file://localhost/Library/Logs/DiagnosticReports/launchd_2016-02-24-094914_localhost.crash
Feb 24 09:52:41 mac com.apple.launchd[1] (net.privatetunnel.ovpnagent[48830]): Job appears to have crashed: Illegal instruction: 4
Feb 24 09:52:41 mac com.apple.launchd[1] (net.privatetunnel.ovpnagent): Throttling respawn: Will start in 10 seconds
Feb 24 09:52:49 mac org.postgresql.postgres[50030]: postgres_real cannot access the server configuration file "/var/pgsql/postgresql.conf": No such file or directory
Feb 24 09:52:49 mac com.apple.launchd[1] (org.postgresql.postgres[50030]): Exited with code: 2
Feb 24 09:52:49 mac com.apple.launchd[1] (org.postgresql.postgres): Throttling respawn: Will start in 10 seconds
Feb 24 09:52:51 mac ReportCrash[50277]: Failed to create CSSymbolicatorRef for launchd[50276]
Feb 24 09:52:51 mac ReportCrash[50277]: Failed to create dSYM-less CSSymbolicatorRef for launchd[50276]
Feb 24 09:52:51 mac com.apple.launchd[1] (net.privatetunnel.ovpnagent[50276]): Job appears to have crashed: Illegal instruction: 4
Feb 24 09:52:51 mac com.apple.launchd[1] (net.privatetunnel.ovpnagent): Throttling respawn: Will start in 10 seconds
Feb 24 09:52:51 mac ReportCrash[50277]: Saved crash report for launchd[50276] version ??? (???) to /Library/Logs/DiagnosticReports/launchd_2016-02-24-095251_localhost.crash
Feb 24 09:52:51 mac ReportCrash[50277]: Removing excessive log: file://localhost/Library/Logs/DiagnosticReports/launchd_2016-02-24-094924_localhost.crash

**Comment by r-a-v-a-s** [comment]
@turtlepa I don't understand how that relates to LibreCAD.

If anyone is willing to be a beta tester, I could upload a dmg somewhere.
Everything seems to be working smoothly on OS X 10.11.3 now.

**Comment by r-a-v-a-s** [comment]
Feel free to reopen this if 2.0.9 does not work for you.
