### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by cicku** [LibreCAD/LibreCAD#438]
Hi,

librecad is now in Fedora's official repo.

Please update the info on install page of homepage. And tell tallaz if he has interests of becoming a packager of Fedora Project. We don't want users to install from 3rd repo especially when the target is available in the Fedora repo simultaneously.

Thanks.

https://apps.fedoraproject.org/packages/librecad

**Comment by r-a-v-a-s** [comment]
Our webpage is somewhat neglected; I'll add it to the wiki.
Create a topic on the [forum][1] for further discussion.

[1]:http://forum.librecad.org/
