### ISSUE TITLE
Problem in saving/loading DFX

### ISSUE THREAD

**Issue by AgoBr** [LibreCAD/LibreCAD#449]
I installed Librecad 2.0.4 on UBUNTU 12.04 LTS 32 bit.
when i try to save a file in a subdirectory  other from my Home directory (I'm owner of this different directory) LibreCad shutdown suddenly.
Same when I try to open a file saved in my Home directory.
Could you resolve this problem?
Thank
Ago

**Comment by r-a-v-a-s** [comment]
Can anyone confirm this?

**Comment by FelixNotTheCat** [comment]
Ubuntu 16.04, LC 2.0.9 - receive 'not allowed/check permissions' rebuke message when attempting to save outside home directory, but no crash.

**Comment by fa201** [comment]
@lordofbikes 
I successfully saved and re-opened a DXF at /tmp on Ubuntu.
Version: 2.2.0-rc1-190-g51b21cc7
Compiler: GNU GCC 7.5.0
Compiled on: Mar 29 2020
Qt Version: 5.9.5
Boost Version: 1.65.1
System: Ubuntu 18.04.4 LTS

**Comment by DuncanLithgow** [comment]
Please make a new bug report is you see this behavior in the latest version. Thanks for testing @fa201
