### ISSUE TITLE
Feature Request: Gears Generator Plugin

### ISSUE THREAD

**Issue by Drakelive** [LibreCAD/LibreCAD#453]
Hi

I propose to create a plugin for creating gears
I unfortunately do not have the capacity.
Any idea?

**Comment by kromanenko** [comment]
Hi all! 
Cylindrical gear tooth profile mainly corresponds to an involute (evolvent) curve. 
Also there is simple approximate method that allows to draw gears teeth with circular arcs.

**Comment by bd** [comment]
Hello, came here looking for this feature, for what it's worth. Probably not qualified to submit anything anytime soon, but I'll take a look at the codebase on the off chance. 

Also, [geargenerator.com](http://geargenerator.com/) is one of the better tools I've yet found for this purpose, as a user.

**Comment by lordofbikes** [comment]
https://github.com/LibreCAD/LibreCAD/tree/master/plugins/gear

**Comment by kromanenko** [comment]
Great news!
