### ISSUE TITLE
Is there a way to make the "canvas size" match the drawing size?

### ISSUE THREAD

**Issue by atorrey** [LibreCAD/LibreCAD#456]
I have a problem that is annoying but not a total show stopper - and am wondering if there is a fix, or a way to find what the problem is...

My drawing is of relatively small objects - at 100% I can easily fit everything on two sheets of letter paper, with lots of room between the views...

The problem is that the drawing background is HUGE in relation to this - if I zoom so that everything fits on my screen, the pan sliders are about 1/4" long, with the result that the slightest false move while panning shoots the drawing right off the screen....

I realize that part of the advantage of a CAD package is that it allows almost infinitely large / small scale drawing in the same project, but it would be a GREAT help if the available drawing area could automatically be sized to the size of the actual stuff being drawn....

Currently using - 
Version: master
SCM Revision: 2.0.4
Compiler: GNU GCC 4.6.3
Qt Version: 4.8.1
Compiled on: Jun 24 2014
Running on Kubuntu Linux

**Comment by J-A-M** [comment]
I think this is indicative of a another problem.

When I load a DXF from LibreCAD into Creo Schematic, it thinks the 'page' is the wrong size and won't load it.

In the DXF file there is a key called EXTENTS (iirc)  this sets the size of effective page.  This is larger than the page size I am importing into (by a factor of 100) so the DXF does not import.

Other similar software has the concept of model space and page space.  When you save a model you state which.  That way EXTENTS is set to either the size of the printable page or the limits of the model, not simply the size of the virtual page.

Right now I have to save load the saved DXF into another program (an old copy of ProgECAD) and save it again.  Sadly this means using an old DXF format.

**Comment by DuncanLithgow** [comment]
As far as I can see this now works well in 2.2rc2.
