### ISSUE TITLE
Line weight problem

### ISSUE THREAD

**Issue by libertas** [LibreCAD/LibreCAD#461]
I set the line weight of a  layer to 50mm in AutoCAD(and latter Draftsight),but they could neither be shown in LibreCAD(I could see 50mm in the layer manager,but it's of the same weight as a 25mm-line).
I used Libre to set the line weight and saved it,the same thing happen to Draftsight.All the lines are the same.
Is there a bug or I used it in a wrong way?

**Comment by efa** [comment]
see https://sourceforge.net/p/librecad/bugs/520/
