### ISSUE TITLE
Endless loop when drag and zoom the DXF file under ArchLinux

### ISSUE THREAD

**Issue by xiangzhai** [LibreCAD/LibreCAD#462]
1. downloaded DXF file from http://www.arcat.com/details/fsrinc/16141101.dxf
2. opened it with LibreCAD, then dragging by pressing the mouse middle button ... Why I dragged it? because LibreCAD failed to render the frame, I mean, the frame's position is wrong, it is clear to compare with it's PDF http://www.arcat.com/details/fsrinc/16141101.pdf

![frame-wrong-position](https://cloud.githubusercontent.com/assets/851100/4932183/c7e67452-6585-11e4-9e61-f12d7ab277d0.png)
1. then LibreCAD was in endless looping status, when top, it used a lot of CPU resource

![endless-loop](https://cloud.githubusercontent.com/assets/851100/4932228/72a281c4-6586-11e4-88f7-e3301efbc7d9.png)

```
lib/math/rs_math.cpp : quarticSolver : line 613
Quartic Error:: Found one real root for cubic, but negative
```

My environment is:

Linux isoft 3.12.7-10 #1 SMP PREEMPT Tue Jun 3 16:50:44 CST 2014 x86_64 GNU/Linux

QMake version 2.01a
Using Qt version 4.8.5 in /usr/lib

LibreCAD github master version

Regards,
Leslie Zhai
a KDE developer

**Comment by r-a-v-a-s** [comment]
When I load this file, in the commandline output:
```
Hatch failed due to a gap=0.0113137 between (53.544, 25.3173) and (53.536, 25.3253)
Hatch failed due to a gap=0.0447214 between (64.394, 19.3483) and (64.438, 19.3563)
Hatch failed due to a gap=0.016 between (53.598, 19.3563) and (53.614, 19.3563)
Hatch failed due to a gap=0.0113137 between (53.544, 35.0217) and (53.536, 35.0297)
Hatch failed due to a gap=0.0447214 between (64.394, 29.0527) and (64.438, 29.0607)
Hatch failed due to a gap=0.016 between (53.598, 29.0607) and (53.614, 29.0607)
```
and in Qt Creator in the application output:

```
RS_FilterDXF::addLayer: layer BORDER PAPER have extended data
RS_FilterDXF::addLayer: layer vports have extended data
RS_FilterDXFRW::endEntity(): updating hatch failed: invalid hatch area
RS_FilterDXFRW::endEntity(): updating hatch failed: invalid hatch area
RS_FilterDXFRW::endEntity(): updating hatch failed: invalid hatch area
RS_FilterDXFRW::endEntity(): updating hatch failed: invalid hatch area
RS_Math::pow: EDOM in pow
```
With many duplicates of the last line.

The program was very slow to respond / pan (3Ghz quad core).

**Comment by r-a-v-a-s** [comment]
What is your CPU? Have you tried with the latest version of LibreCAD?
It could just be that it's taking a really long time to process.
The test file's link is now dead.

**Comment by luzpaz** [comment]
@xiangzhai ping

**Comment by DuncanLithgow** [comment]
The original file is not available and the OP has not responded for 4+ years.
