### ISSUE TITLE
Usage from command line

### ISSUE THREAD

**Issue by Acconut** [LibreCAD/LibreCAD#465]
Is it possible to use use the `librecad` binary from the command line (e.g. bash)? I would like to convert DWG/DWF files on Ubuntu to PDFs automatically without a GUI.
If that's not available are you aware of any project which are capable of this?

**Comment by micropole-cdescours** [comment]
It seems that QCAD is offering these features, but I haven' tested them yet : http://www.qcad.org/en/qcad-documentation/qcad-command-line-tools
