### ISSUE TITLE
When switching off printing of layer 0, undesired lines appear

### ISSUE THREAD

**Issue by jborme** [LibreCAD/LibreCAD#470]
Open a new document.
1. Draw things in layer 0.
2. In the "Layer list" window, press the small "printer" icon of layer 0 to toggle it off.

Result: it seems to prolongate infinitely every segment. Gives best results by drawing several polygons with many vertices in each.

Actually I normally don't use this small icon, I'm not sure what it should do or not, but it does not do that on layers other than 0 so I think it's a bug.

**Comment by lordofbikes** [comment]
This is the **Help Layer** feature, see http://wiki.librecad.org/index.php/LibreCAD_users_Manual#Help_Layers.
It was renamed to **Construction Layer** in newer releases.
