### ISSUE TITLE
Drawing ellips inscribed in a quadrilateral brings crash

### ISSUE THREAD

**Issue by glushko311** [LibreCAD/LibreCAD#480]
Environment: 
OS: Windows 7 x64
LibreCAD: 2.0.7

This bug is not reproduce every time!
I didn't find any regularity in its reproduction.

Steps for reproduce
1.Create rectangle.
2. Use the tool "Draw ellipse  inscribed in a quadrilateral i. e. tangential to four lines" .
3.Mark four lines of rectangle.
4.When you marked last line application will crash.
5.Maybe for reproduction of a bug you have to repeat steps 1-4 five or six times.

![1](https://cloud.githubusercontent.com/assets/10559084/5801258/b4009a02-9ff1-11e4-9801-c5f45d2ea3fe.png)

![2](https://cloud.githubusercontent.com/assets/10559084/5801283/0170f476-9ff2-11e4-93ef-0a38cece047d.png)

**Comment by kromanenko** [comment]
I have experimented some more with that tool. 

Actually application fails in those conditions: 
- when lines are connected into correct rectangle
- when lines are situated orthogonally to each other 

In following conditions given function works as expected:
- having 4 scattered lines
- in some random quadrilateral with different sides and angles
- in paralelogram

Screenshot attached. 

![480](https://cloud.githubusercontent.com/assets/10499375/5866543/f7c259b4-a29a-11e4-92c5-bea62baa71be.PNG)

Environment:
LibreCAD version 2.0.7, GCC 4.8.2. Qt 5.3.1 (2015-01-03 Release from SourceForge).
OS: Windows 8.1 (64bit)

**Comment by dxli** [comment]
Please test with the latest nightly builds, for windows:

https://sourceforge.net/projects/librecad/files/Windows/NightlyBuilds/

**Comment by r-a-v-a-s** [comment]
I could not reproduce this crash. One thing I noticed is 
![quad_no_ellipse](https://cloud.githubusercontent.com/assets/12013378/7622929/656d2a6c-f989-11e4-81da-c9cc21afae08.png)

Is this a case where the ellipse does not exist?

**Comment by dxli** [comment]
for a trapezoid, if it's not isosceles, there's no inscribed ellipse.
We may have some tolerance issue in detecting trapezoid though

**Comment by dxli** [comment]
sorry, there's no "unique" inscribe ellipse for "non-isosceles trapezoid".
More work is needed to handle "infinite number of inscribed ellipses":

for parallelogram and trapezoid

**Comment by kromanenko** [comment]
Verified on Windows nightly build 2.0.7-274-g821f837. Now it works.

**Comment by dxli** [comment]
fixed for:

parallelograms (and rectangles)
trapezoid isosceles
cleaned up for quadrilateral identification
