### ISSUE TITLE
No tooltip for green hand icon in status bar

### ISSUE THREAD

**Issue by kromanenko** [LibreCAD/LibreCAD#487]
There is no tooltip for green hand icon in statusbar. 
I tried to figure out what green hand icon in status bar does. But i still have no idea about that button. 
![green hand](https://cloud.githubusercontent.com/assets/10499375/5897697/c241fa94-a54f-11e4-942b-197a93a071e6.png)

Environments:
LibreCAD version 2.0.7, GCC 4.8.2. Qt 5.3.1 (2015-01-03 Release from SourceForge).
OS: Windows 8.1 (64bit)
LibreCAD version 2.0.2, GCC 4.8.2. Qt 4.8.6, OS: Ubuntu 14.04 LTS (64bit)

**Comment by lordofbikes** [comment]
This Icon is part of the Mouse Widget. It has no function. But in drawing mode you can see on left/right side of it the current action for left/right mouse button.

We should apply another icon for this button and possibly select another control instead of a clickable button.

**Comment by lordofbikes** [comment]
I fixed this with commit https://github.com/LibreCAD/LibreCAD/commit/9ccfb496037fd1e04755becee16e673c65cd4d2d
It's not longer a button and it has a tool tip now.

**Comment by kromanenko** [comment]
Nice mouse icon :)
