### ISSUE TITLE
delete this

### ISSUE THREAD

**Issue by kromanenko** [LibreCAD/LibreCAD#494]
Posted mistakenly. Delete this issue :)

**Comment by lordofbikes** [comment]
As this was a good question, I restored it and here is the answer for other contributors running into this issue:

SCMREVISION is determined by qmake and qmake is building the makefiles for a LibreCAD build.
So first step to update this info is to run `qmake librecad.pro`, then the current SCMREVISION should be added to the makefiles.
But this doesn't change anything until the source file for the about dialog window is rebuild. Thus you have to touch the file `librecad/src/main/qc_applicationwindow.cpp` to force a rebuild for it.
Then, after calling make, you should see the latest commit in the about window.

With the built in scripts for release builds in the scripts folder all this is done automatically, but then everything is rebuild, what makes the build process much longer.
