### ISSUE TITLE
Trim / Extend label in menu

### ISSUE THREAD

**Issue by kromanenko** [LibreCAD/LibreCAD#501]
Steps: 
1) Open *Modify* toolbar
2) Hover on "Trim" button. 
See tooltip: "Trim / Extend"

3) Click *Modify*  drop-down menu. 
See there "Trim" option. 
Exected to see label: "Trim / Extend"

By the way, it`s a bit confusing that Extend option is same button as Trim, but Lengthen is another button.

Environment: Ubuntu 14,04
master, on commit ae5cc64
Windows, build: 2.0.7-33-g9ccfb49

**Comment by r-a-v-a-s** [comment]
This was fixed.
