### ISSUE TITLE
RS_VariableDict can return uninitialised values (suggested fix provided)

### ISSUE THREAD

**Issue by nathan-williams-farnese** [LibreCAD/LibreCAD#504]
I am working on a fork of LibreCAD for a completely different purpose, but I have found a bug that results in random crashes when a new document window is created (new doc or open doc).

The problem is with the "get" logic in RS_VariableDict, for example:

https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/engine/rs_variabledict.cpp#L220

`QHash<QString, RS_Variable>::iterator i = variables.find(key);
if (i != variables.end() || i.value().getType()==RS2::VariableInt)`

This should be a logical AND not OR.
As long as we get a result from the find, then we ignore the type of the variable altogether!
(This happens in all "get" methods)

If you then look at how RS_Variable is implemented, all values are stored uninitialised unless directly set.

In my case the problem comes up in `int RS_Graphic::getLinearPrecision()`
It is looking for the Int variable "$LUPREC", which seems to sometimes get stored / overwritten by a non-integer value of the same key.

I'm going to make a fix in my fork, but I am not great at GIT, so I am unsure of how to provide a pull request / patch from a private repo that has diverged in other areas.
It might be simpler if someone looks over the logic to confirm my findings and applies the change directly.

**Comment by lordofbikes** [comment]
Good catch!
I fixed this, as it was not too much typing and did some clean up with it.

Many thanks for your effort and reporting this.

In general you can simply create patches with git. If you have a clean commit, concerning only a special fix, redirect the output of `git diff` to a file.
E.g. `git diff [commit] >myfix.patch`.
Send this file by mail or post it somewhere. Then somebody can merge it with `git apply myfix.patch` to another repo.
