### ISSUE TITLE
layer activation added to undo stack

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#528]
The recent change to the undo system regarding
_Application Preferences → Defaults → Modify layer of selected entities, at layer activation_
makes it so every click on a layer is added to the undo stack.

**Comment by kromanenko** [comment]
Please clarify actions by more detailed way, i could not reproduce. 
BTW, creation of layer can not be reverted, that`s looks like a bug.

**Comment by kromanenko** [comment]
On new commit 9f6f40070a227b6c7f79cea66b8501206c7ba004 it is also reproduced.

**Comment by r-a-v-a-s** [comment]
- create a circle
- click on a layer three times

You will have to undo 4 times for the circle to be removed.

**Comment by r-a-v-a-s** [comment]
This bug still exists; and it adds a lot of pollution to the undo stack for anyone who uses layers.
Note that disabling "Modify layer of selected entities, at layer activation" fixes the issue.

I'm still an advocate for replacing "Modify layer of selected entities, at layer activation" with:

1. right click context menu for layers has "move selected here" 

2. make a hotkey, command and/or top level icon for Modify → Attributes

**Comment by atorrey** [comment]
Sort of related, though probably not directly...

One of my minor annoyances, and it isn't a show stopper, but just slows me down, is that if I want to modify something, I tend to select the entities first, then select the modification.  It is annoying that the modification step then brings up the select menu that I have to click through....

Would it make any sense to have the modification steps check to see if entities have been selected, and if so, skip the select menu step, and if not then bring up the menu?  That way it is efficient whichever way you do your workflow...

ART

------------------
Arthur Torrey - <arthur_torrey@comcast.net>
-------------------


----- Original Message -----

**Comment by dxli** [comment]
atorrey,

have a look at commit: 872e3e52a
Please help to improve this feature.

**Comment by dxli** [comment]
In general, the undo cycle needs some enhancement.

**Comment by atorrey** [comment]
I'm not a code person, but if I'm reading it right, looks like you have a good solution...

I need to figure out how to download the version with this in it to test, but not tonight...

Many thanks for working on this!

ART

------------------
Arthur Torrey - <arthur_torrey@comcast.net>
-------------------


----- Original Message -----

**Comment by dxli** [comment]
ART,

for windows/mac, nightly builds can be found at: https://sourceforge.net/projects/librecad/files/
In general, you can follow our wiki to build from latest source:
http://wiki.librecad.org/index.php/LibreCAD_Installation_from_Source

**Comment by lordofbikes** [comment]
With latest fixes to undo/redo code, 2d8e025 to ed90a19, it should be more stable now.
But this doesn't change the primary issue.
Also there is nothing wrong with that behavior in my eyes. After selecting a layer, with entities selected, the entities are moved to the selected layer and the selection is revoked. Only when entities are selected again the click on the layer list adds a new undo cycle. Well, this may be different before.
But now, if one repeats this multiple times, I see nothing wrong when each cycle is added to the undo stack.
