### ISSUE TITLE
Layer creation can not be reverted

### ISSUE THREAD

**Issue by kromanenko** [LibreCAD/LibreCAD#530]
Steps:
1. Open new drawing.
2. Create new layer.
3. Note that Undo button and menu item are still disabled. Expected to be able to undo layer creation.

Env: Ubuntu 14.04, build on commit 140eaee3bd0610f49a848e1cce539d0ab008660d

**Comment by kromanenko** [comment]
On new commit 9f6f400 it is also reproduced.

**Comment by dxli** [comment]
Currently, "Undo/Redo" are for entities only, while Layer is a property of entities, but not an entity *per si*.
Therefore, this feature can not be easily supported.

**Comment by r-a-v-a-s** [comment]
It doesn't seem worth the added complexity.
I suggest keeping the undo stack as simple / clean as possible.

**Comment by lordofbikes** [comment]
After getting my teeth into undo code I come to the same conclusion.
Undo/redo stack is implemented in entities, layer creation/removal is something completely different.
So to revert layer creation, don't use undo, but remove layer.
Concerning redo layer removal see #531
