### ISSUE TITLE
Failed to Undo layer removal operation

### ISSUE THREAD

**Issue by kromanenko** [LibreCAD/LibreCAD#531]
Steps:
1. Open new drawing.
2. Create new layer.
3. Remove this layer. 
4. Undo button and menu item became enabled. Click Undo.
5. Expected the layer removal operation to be reverted. Actually i could not to undo this.
Env: Ubuntu 14.04, build on commit 9f6f400.

**Comment by lordofbikes** [comment]
As discussed in #530 undo/redo for layers is not easy to implement.
For layer removal you have to confirm now, that this action can't be undone.
But entities which are on the removed layer are not lost. They are moved to layer 0 which couldn't be removed. So you could redo the deleted entities, but they will be on layer 0, even when you recreate the deleted layer.
