### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#532]
The first crash happened when I was deleting an overlapping circle after using modify-rotate to create multiple copies of a circle. The second crash was right after pressing OK while trying to rotate/create multiple copies of a circle.

![seg_fault_01](https://cloud.githubusercontent.com/assets/12013378/7764195/019e4c4e-0002-11e5-8a25-cae4a491794a.png)
![seg_fault_02](https://cloud.githubusercontent.com/assets/12013378/7764196/03f0e5c4-0002-11e5-875e-316c0d4df270.png)

I'm sensing this has something to do with line 64... ;-]

**Comment by dxli** [comment]
detailed steps to reproduce this bug?

**Comment by r-a-v-a-s** [comment]
Perhaps your change to the debugging on line 64 fixed it. I have not been able to reproduce this.

**Comment by dxli** [comment]
Cad toolbars, always ugly.
