### ISSUE TITLE
The layer is changing itself

### ISSUE THREAD

**Issue by vlad1777d** [LibreCAD/LibreCAD#533]
The layer of some line, when i click to copy\move it, is changing itself from current to 0.

I know English badly, not enough to describe detailed steps of problem problem, so i writed the video:
https://vk.com/video16425447_171546310 ,
or:
https://youtu.be/1zhqJrYAJfI
From there you can see, that the line, that i choose first time, after click move and copy, after unfreezing the 0 layer, became to belong to 0 layer.

In the copy properties window (on the video) there was marked "use the current layer". I have not changed the current layer, i only pressed to unfreeze 0 layer, and the line, from which i copied next line changed it's layer.

Version of program: Version: master
SCM Revision: 2.0.4
Compiler: GNU GCC 4.8.2
Qt Version: 4.8.6
Compiled on: Jun 24 2014
Portions (c) 2011 by R. van Twisk

PS. the layer is changing itself not only as was written in top:
https://youtu.be/y_OiCm5vLZM
https://vk.com/video16425447_171546358
If i select line, than click unhide (or unfreeze) the layer button (on that layer there is an image), than that line becames belong to that layer, which I just unhided.

**Comment by lordofbikes** [comment]
This was implemented fix into revision 2.0.4 as feature.
Selected entities are moved to a layer, when it is clicked in the layer list.
On request it was converted into an option, disabled by default, on the way to revision 2.0.5.
At some point after 2.0.7 a check box in application preferences was added for easy switching on/off this feature.

In other words, in your version 2.0.4 deselect all entities before you click anything in the layer list, except you really want to change the layer of selected entities.
If this upset you, you have to update LibreCAD to any later version than 2.0.4.

**Comment by vlad1777d** [comment]
Thank you.
