### ISSUE TITLE
hatch outside boundary

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#537]
* create circle with radius 100
* apply hatch: ansi31 (scale 1, angle 0)

![hatch](https://cloud.githubusercontent.com/assets/12013378/8151606/96da7c26-12c5-11e5-8e4e-9825bfe5062d.png)

**Comment by dxli** [comment]
looks like a regression.

**Comment by dxli** [comment]
fixed by reverting my copy ctors,  d8e789b528d6fa0994e232790278ff88b31fa756

The reason, copy ctors needed for all derived classes.

We either actually implement them all, or just remove the copy ctor attempt.

It still helps, if we can have all entities by shared_ptrs

**Comment by r-a-v-a-s** [comment]
confirmed fix
