### ISSUE TITLE
Tangential 3 Circles problem case

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#548]
The circle in the upper half of the [vesica piscis][1] is not considered for "Tangential 3 Circles".

![3tan_issue](https://cloud.githubusercontent.com/assets/12013378/8738205/85a4f506-2be0-11e5-88cc-186b6421aff9.png)

[1]:https://en.wikipedia.org/wiki/Vesica_piscis

**Comment by r-a-v-a-s** [comment]
Actually it is considered if the two circles have a radius of 100, but not when their radius is 10.

**Comment by dxli** [comment]
can you send in the dxf file?

I can get 6 possible tangential circles here.

**Comment by dxli** [comment]
I can still get all 6 possible solutions with your dxf file

**Comment by r-a-v-a-s** [comment]
:astonished:

**Comment by dxli** [comment]
Looks like we can expand this tangent3 feature to include "point" entities to provide features like:

draw a circle passing 3 given points;
draw a circle passing 2 points and tangential to a given line/circle
draw a circle passing 1 point and tangential to two given lines/circles

**Comment by dxli** [comment]
allow point entities for "tan3": 73cab7e

**Comment by r-a-v-a-s** [comment]
Now I get all solutions. :+1:
