### ISSUE TITLE
Error compiling on Centos

### ISSUE THREAD

**Issue by jacusiel** [LibreCAD/LibreCAD#551]
/usr/lib64/qt4/bin/uic ui/forms/qg_dlgoptionsmakercam.ui -o ../../generated/librecad/ui/ui_qg_dlgoptionsmakercam.h
Hello, I get the following error when compilimgo on Centos. Please tell me what aditional info you need. Thanks

uic: Error in line 46, column 34 : Unexpected attribute alignment
File 'ui/forms/qg_dlgoptionsmakercam.ui' is not valid
make[2]: *** [../../generated/librecad/ui/ui_qg_dlgoptionsmakercam.h] Error 1
make[2]: Leaving directory `/root/lintex/LibreCAD/librecad/src'
make[1]: *** [sub-src-make_default] Error 2
make[1]: Leaving directory `/root/lintex/LibreCAD/librecad'
make: *** [sub-librecad-make_default-ordered] Error 2

**Comment by dxli** [comment]
can you test building with qt5?

**Comment by jacusiel** [comment]
Hello, thanks for your reply. I'll try to install qt5 and compile.

On 08/03/2015 02:39 PM, Dongxu Li wrote:
>
> can you test building with qt5?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LibreCAD/LibreCAD/issues/551#issuecomment-127341981>.
>

-- 
*Rodrigo Jacusiel*
jacusiel@lintex.cl <mailto:jacusiel@lintex.cl>
56 (2) 2328 9400 <tel:+56223289400>
www.lintex.cl <http://www.lintex.cl>
Lintex - Chile
