### ISSUE TITLE
Shortcuts for drawing order

### ISSUE THREAD

**Issue by Rupicapra-rupicapra** [LibreCAD/LibreCAD#562]
Hello,
I want to set shortcuts for drawing order modifiers (menu Edit > Draw order), and I would like to have your opinion on the best shortcuts to use.

For 'Move to Top' & 'Move to Bottom', I would like to use these shortcuts : Ctrl + PageUp & Shift + PageDown.
For 'Lower after entity' & 'Raise over entity', I was thinking about Ctrl + up & Ctrl + down.

Another way would be using inkscape-like shortcuts (do not use modifier keys) :
 - 'Move to top' -> 'Start';
 - 'Move to bottom' -> 'End';
 - 'Lower' -> PageDown;
 - 'Raise' -> PageUp.
What do you thing about these possibilities ? Would you prefer other shortcuts ?

Thanks,

Rupi

**Comment by severoraz** [comment]
I think this is a good idea

**Comment by dxli** [comment]
merged #564

**Comment by dxli** [comment]
Thanks a lot to jerry: @Rupicapra-rupicapra
