### ISSUE TITLE
anti-aliasing 

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#565]
I can add an option for anti-aliasing in the drawing area if that is agreeable.

**Comment by dxli** [comment]
no reason not to play with it. I suppose there's some performance cost, but shouldn't be much.

**Comment by severoraz** [comment]
I'm all in favor for this option!

**Comment by r-a-v-a-s** [comment]
I'll get to this in a few days, after the gui update is polished.

What do you guys think:
- an option in application preferences
- or a toggle icon (like the grid toggle)

**Comment by dxli** [comment]
I don't suppose this would be tweaked often, so within application preferences is fine

it's global and takes effect immediately, unlike many application preferences which requires restarting of the app to take effect.

**Comment by severoraz** [comment]
I also favor the option within application preferences (if I have vote haha)

**Comment by severoraz** [comment]
In which build will we find this feature?

**Comment by lordofbikes** [comment]
You will find it in the last night build installer for Windows: *LibreCAD-Installer-2.0.7-603-g00eb65b.exe* at https://sourceforge.net/projects/librecad/files/Windows/NightlyBuilds/master/.

If you build from source, pull latest changes and ensure that you are on the master branch.

**Comment by severoraz** [comment]
I built it, looks great!
