### ISSUE TITLE
can't see preview with certain combinations of background color and pen color

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#576]
If I set the background to white and I have a black pen, then I can not see the preview when drawing.

**Comment by dxli** [comment]
should be an easy one.

I still don't quite understand why CAD likes a smart "black/white" color. If we set it to two black or white options.
User can ask for white background and white pen, and a blank page won't be considered as a bug

**Comment by r-a-v-a-s** [comment]
This is why we can't see the preview:
https://github.com/LibreCAD/LibreCAD/commit/fba9948b6fe21f33ef5e98ca8c7136adab54aeca

**Comment by r-a-v-a-s** [comment]
The composition mode breaks the principle of least astonishment.
People will keep posting about this.
I don't think being able to see orthogonal lines under the crosshair is worth it.
I suggest removing this in favor of an additional crosshair as I have suggested.

**Comment by r-a-v-a-s** [comment]
I'll work on this.
