### ISSUE TITLE
2.0 branch block and text are drawn bad

### ISSUE THREAD

**Issue by Rallaz** [LibreCAD/LibreCAD#582]
To reproduce:
1. draw a text with angle 0
2 draw a rectangle, create a block with it, insert with rotation angle 0.

Both can be shown horizontal but are drawn rotated, this bug was introduced with this commit:
vector: c++11 style cleanup
https://github.com/LibreCAD/LibreCAD/commit/640fa5e2e41053d644eb5a4505bbf2b2c402af42

**Comment by dxli** [comment]
sorry Rallaz,

my bad, forgot to apply the fix to 2.0

cherry-picked: 076be30
