### ISSUE TITLE
easier access to "select intersected entities"

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#585]
In the default selection mode you can window select by:
- click-drag-release
- click-release-move-click-release

It seems like one of these could be "select intersected entities".

**Comment by lordofbikes** [comment]
LibreCAD handle this as many other CAD software.
Drag the window from left to right, it's blue then and only fully included entities are selected.
Drag it from right to left, it's green then and everything that is intersected by the window is selected.

**Comment by r-a-v-a-s** [comment]
The difference is that "select intersected entities" can select the top and bottom of this parallelogram without selecting the other sides.
![parallelogram](https://cloud.githubusercontent.com/assets/12013378/10447978/1622a9e6-713e-11e5-8e9c-d820d2adea65.png)

**Comment by r-a-v-a-s** [comment]
Custom toolbars and menus are sufficient.
