### ISSUE TITLE
How to get perimeter, area of files for .pdf, .dxf, .svg files?

### ISSUE THREAD

**Issue by nikhilbhansali** [LibreCAD/LibreCAD#587]
Hey
This is for cost calculation of laser cutting and CNC routing, is there a way to get perimeter? 
Please do let me know!

**Comment by lordofbikes** [comment]
In the status bar is a box where you could see the number of selected entities and their total length. Select all entities belonging to the tool path and find the total length (perimeter) in this box.
The entities must not be connected.

To measure an area use the Info->Polygonal Area tool. Click multiple points on the perimeter of the tool path and find the Circumference and the enclosed Area printed in the Command line history.

**Comment by dxli** [comment]
@nikhilbhansali 

To get total length, just select entities of a contour, on the status bar there's an area showing selected:

number of entities selected
Total length

To get total area enclosed, you can use the "Hatch" feature. Select the contour, create hatch for it, and total area will be shown in command widget:
![screenshot from 2015-10-14 16-00-09](https://cloud.githubusercontent.com/assets/827425/10496011/b318102a-728c-11e5-8c48-65251ecd31e3.png)

**Comment by dxli** [comment]
@nikhilbhansali 

The total length and area features support: line, arc, and elliptical arc types.

**Comment by nikhilbhansali** [comment]
Thanks :)
