### ISSUE TITLE
CAD Toolbar isn't drawing correctly on a 4K monitor at larger window heights

### ISSUE THREAD

**Issue by hansomli** [LibreCAD/LibreCAD#595]
LibreCAD 2.0.4 with maximum window height on a 4K monitor:

![toolbar_2-0-4_bug](https://cloud.githubusercontent.com/assets/5760706/10861764/c3182784-7f49-11e5-9b93-32f1b72d6e3c.png)

LibreCad 2.0.8 with maximum window height on a 4K monitor:

![toolbar_2-0-8_bug](https://cloud.githubusercontent.com/assets/5760706/10861763/c314e1f0-7f49-11e5-931b-0886b6a43c72.png)

The issue goes away with window height this size and below:

![toolbar_2-0-8_ok](https://cloud.githubusercontent.com/assets/5760706/10861762/c311ab2a-7f49-11e5-99b3-cc7bc60408e1.png)

Reproduced on Ubuntu 14.04.3 LTS, 15.04, and 15.10 with librecad from universe and from the stable ppa.

**Comment by r-a-v-a-s** [comment]
Thanks for the screenshots; they are always helpful. :sunglasses: 

It is known that the cad toolbar has issues in general.
It's forced and overly complicated.
The QToolBar is designed for one column (or row).

I have created various other replacement widgets,
and I still have more ideas to explore.
http://forum.librecad.org/GUI-update-td5712246.html

**Comment by r-a-v-a-s** [comment]
Also note there is an icon size option now... :-]
https://github.com/LibreCAD/LibreCAD/issues/543

**Comment by dxli** [comment]
@r-a-v-a-s 

is the "icon size" option  icon itself large enough to be useful on HD?

**Comment by r-a-v-a-s** [comment]
It depends how large an icon looks at 150x150 on a 4k screen.
Otherwise we will need to convert to SVG (or make larger icons).
I noticed we have a folder with some SVG icons already.
https://github.com/LibreCAD/LibreCAD/tree/master/desktop/graphics_program_icons

**Comment by r-a-v-a-s** [comment]
There's really nothing we can do about this;
and the CAD toolbar has been replaced.
