### ISSUE TITLE
Show commands for each menu entry

### ISSUE THREAD

**Issue by Harvie** [LibreCAD/LibreCAD#603]
Hello,
i understood that one can draw line by typing "LI" instead of clicking on it in menu... Would be great if it was written in the main menu captions like "Line [L]" -> "Two points [LI]". As in tooltips at hover on icon tool menu on the left. Also whenever i click something it should write the commands to commandline, so i see how it's done and can learn the commands subliminaly during use of librecad.

These are really important when you are drawing something bigger where you need to enter lots of values.

**Comment by r-a-v-a-s** [comment]
This is one of the next things on my list.
Although I have found other solutions 
that keep both the titles and command line clean.
See https://github.com/LibreCAD/LibreCAD/issues/570
