### ISSUE TITLE
Deleting block causes current drawing to close

### ISSUE THREAD

**Issue by Rupicapra-rupicapra** [LibreCAD/LibreCAD#613]
Hello there,
When I want to delete a block from the block list, current drawing closes, and then I have an empty LibreCAD window.
Debug message does not show any information, and I can't bisect to find where this comes from because some commits brought compilation errors (solved later).
Thanks for any help,
Jerry

Version : master, updated and built today
OS : Linux Mint 17.2
Qt 4

**Comment by r-a-v-a-s** [comment]
I wasn't aware that a window was closed on block removal.
The code needed a small tweak because I eliminated the unnecessary QMainWindow
when I switched QC_MDIWindow to be a subclass of QMdiSubWindow.

**Comment by Rupicapra-rupicapra** [comment]
Your bugfix works great. Thanks !
