### ISSUE TITLE
Plugin "List Entities" crash

### ISSUE THREAD

**Issue by dxli** [LibreCAD/LibreCAD#616]
Affected version: ~~2.0 (expected in master branch, but not tested yet)~~ master's branch

steps to reproduce:

* start LC;
* Draw -> Line ->Rectangle;
* select first and and second corner to draw a rectangle;
* Info -> List Entities;
* when proposed to select entities, select the rectangle drawn;
* Click "Continue" of the selection toolbar.

Expected results:

* entities listed;

Actual results:

* LC crashes with dereferencing of nullptr

Reproducibility: 100%

**Comment by Rallaz** [comment]
Tested with LibreCad 2.0 +git 2015-10-19 & 2.0 +git 2015-11-26
Made the steps, actual result : 
Entity are listed without crash.
Maybe your LC found a incompatible liblist.so file?

**Comment by r-a-v-a-s** [comment]
See https://github.com/LibreCAD/LibreCAD/commit/e3771d16682c44608165563e6bfbd27bef10ad05

**Comment by dxli** [comment]
@Rallaz @r-a-v-a-s 

sorry, my bad. After rebuilding, 2.0 does not crash

master's branch still crashes for me, by the dtor of ActionGetSelect

**Comment by r-a-v-a-s** [comment]
https://github.com/LibreCAD/LibreCAD/issues/596

**Comment by r-a-v-a-s** [comment]
What steps in the master branch? There is no continue button.

**Comment by dxli** [comment]
@r-a-v-a-s 

Just press Enter instead of the "Continue" button

**Comment by r-a-v-a-s** [comment]
It works fine for me.
