### ISSUE TITLE
3D Printing support

### ISSUE THREAD

**Issue by iHateInventNames** [LibreCAD/LibreCAD#618]
features about to merge are slicing (Slicer, Cura) and sending (Printrun) to 3D printing device

**Comment by r-a-v-a-s** [comment]
Are you working on implementing this for LibreCAD?
How does 3D printing work with a 2D CAD application?

**Comment by iHateInventNames** [comment]
No, I didn't know this is 2d CAD. I was't aware of such kind of CADs. There is such plugin for FreeCAD already. I guess similarest code generation might be useful for LibreCAD is for engravers probably. Thank you for your reply and I am sorry for bothering you.
