### ISSUE TITLE
Status bar display error

### ISSUE THREAD

**Issue by nikonboy** [LibreCAD/LibreCAD#629]
![Uploading Screenshot (7).png…]()

Hello

The status bar at the bottom does not render properly on a surface pro 3, making the software unusable. Changing the font size does not help.

**Comment by nikonboy** [comment]
![screenshot 7](https://cloud.githubusercontent.com/assets/8439959/12152535/30cecb5a-b4ad-11e5-8783-312a429d98a0.png)

**Comment by r-a-v-a-s** [comment]
I've noticed that removing `statusBar()->setMinimumHeight(32);` allows for proper automatic sizing;
however, it makes the statusbar height dynamic, which is noticeable when a status tip is displayed. 

I'll be adding an option for the height soon.

**Comment by r-a-v-a-s** [comment]
You can find the statusbar height option in "Widget Options".
https://sourceforge.net/projects/librecad/files/Windows/NightlyBuilds/master/
