### ISSUE TITLE
Dimensioning insanity

### ISSUE THREAD

**Issue by patricktokeeffe** [LibreCAD/LibreCAD#635]
I draw a rectangle that is 20-3/16" by 25-7/16", then I add dimension lines to it. The ruler tool works --as you can see output in the command window-- but dimension lines get labeled as fractions of *something*. 

I've read the "Brief overview" and looked through relevant sections of the "User manual" for any answers without finding so much as a hint. Can anyone tell me what the hell is going on here?

![whatthefuckisgoingonhere](https://cloud.githubusercontent.com/assets/1348834/12599390/594d09e0-c446-11e5-85bd-5a2c452ec949.png)

**Comment by dxli** [comment]
@patricktokeeffe 

You can set the dimension format in "Drawing Preferences":

Edit -> Current Drawing Preferences -> Format
