### ISSUE TITLE
No keyboard shortcut for getting into command line

### ISSUE THREAD

**Issue by kfoltman** [LibreCAD/LibreCAD#645]
As far as I can remember, Ctrl+M could previously be used to select the command line entry widget. Now it doesn't seem to be working, and that makes it necessary to switch between keyboard and mouse more often.

**Comment by r-a-v-a-s** [comment]
Hi, I removed that recently, or didn't bother re-adding it when moving some things around.
I never have understood why it is needed. All typing automatically goes to the command line... does it not? What operating system are you using?

**Comment by r-a-v-a-s** [comment]
:bulb:  You need it when you are in the field of another widget...

I'll add it back.

**Comment by r-a-v-a-s** [comment]
I implemented it differently; let me know if it works as expected.

**Comment by kfoltman** [comment]
Thanks!

**Comment by kfoltman** [comment]
Yep, it works.
