### ISSUE TITLE
Filet, bevel creates new entities instead of modifying the old

### ISSUE THREAD

**Issue by vlachoudis** [LibreCAD/LibreCAD#651]
When you have two lines you create a filet, in the past the two lines were trimmed and a filet was introduced. Now the original lines remain untouched, new lines are created plus the filet, which
results in multiple similar entities overlapping

**Comment by vlachoudis** [comment]
The "Trim" option just deletes the original lines. And the undo doesn't work properly

**Comment by kfoltman** [comment]
There's a pending fix for the fillet function - see commit https://github.com/kfoltman/LibreCAD/commit/83b86ecdf1df05e3e8c0c82cf8f3c69326df29b4 in my branch (currently waiting for code review/merging).

**Comment by vlachoudis** [comment]
Ok, thanks I will wait then :)
