### ISSUE TITLE
'cut' mode SplinePoints (the ones with control points only) don't snap on start/end

### ISSUE THREAD

**Issue by kfoltman** [LibreCAD/LibreCAD#664]
1. Draw a spline using the 'through the points' option
2. Save to DXF
3. Close and load from DXF
4. Try to draw a 2-point line from start point of the SplinePoints to the end point of the SplinePoints using endpoint snap -> it doesn't snap to the endpoints

The bug seems to be in LC_SplinePoints::getStartPoint()/ LC_SplinePoints::getEndPoint() - they always check splinePoints instead of using getPoints() to pick the relevant array.

**Comment by r-a-v-a-s** [comment]
dxli is busy this week and you already understand the issue more than I do.
Please join the team and help us get ready for 2.1.0 :sunglasses:

**Comment by kfoltman** [comment]
Thanks - I've created a pull request just for extra safety :)

**Comment by r-a-v-a-s** [comment]
:+1: Feel free to label and self assign this issue before you close it.
