### ISSUE TITLE
New symbols for "unicode.lff"

### ISSUE THREAD

**Issue by Symbian9** [LibreCAD/LibreCAD#690]
There are few ukrainian symbols for "unicode.lff"
<code>[0404] Є
5,0;2,0;-0,2,A-0.41;0,7;2,9,A-0.41;5,9
3,5;0,5

[0406] І
0,0;0,9.

[0407] Ї
1.5,0;1.5,9.
0,11.5;0,12.
3.,11.5;3.,12.

[0454] є
4,0;1.5,0;-0,1.5,A-0.41;0,4.5;1.5,6,A-0.41;46
2.5,3;0,3

[0456] і
0,0;0,6.
0,8.5;0,9.

[0457] ї
1.5,0;1.5,6.
0,8.5;0,9.
3.,8.5;3.,9.

[0490] Ґ
0,0;0,9;5,9;5,10

[0491] ґ
0,0;0,6;4,6;4,7</code>
Some of them are similar to already presented symbols, so its possible paste next as alternative
<code>[0404] Є
5,0;2,0;-0,2,A-0.41;0,7;2,9,A-0.41;5,9
3,5;0,5

[0406] І
C0049

[0407] Ї
C00cf

[0454] є
4,0;1.5,0;-0,1.5,A-0.41;0,4.5;1.5,6,A-0.41;46
2.5,3;0,3

[0456] і
C0069

[0457] ї
C00ef

[0490] Ґ
0,0;0,9;5,9;5,10

[0491] ґ
0,0;0,6;4,6;4,7</code>
Add them to https://github.com/LibreCAD/LibreCAD/blob/master/librecad/support/fonts/unicode.lff

**Comment by dxli** [comment]
@Symbian9 

Thanks a lot!

Can you send in a pull request?

**Comment by Symbian9** [comment]
Cant make a pull, because I have only Symbian phone that can't fully work with github...

**Comment by Evil-Spirit** [comment]
There are may be a bug. Missed newlines.

**Comment by Symbian9** [comment]
> There are may be a bug. Missed newlines.

@Evil-Spirit, is it still an issue here?

**Comment by Symbian9** [comment]
@dxli @lordofbikes, Please, check comments by @Evil-Spirit on some possible issues with `є` and `Ї` characters in `unicode.lff`:

- https://github.com/LibreCAD/LibreCAD/commit/ca6f39feb916390596c7ed3a0cfd88e935cd4e74#commitcomment-17007934
- https://github.com/LibreCAD/LibreCAD/commit/ca6f39feb916390596c7ed3a0cfd88e935cd4e74#commitcomment-17007980
