### ISSUE TITLE
I cannot find any more the Points in the toolbar

### ISSUE THREAD

**Issue by vlachoudis** [LibreCAD/LibreCAD#699]
If I remember well I saw the "Points" as separate toolbar never understood why it is not in the "Categories". Now on the alpha version I cannot find it anymore neither in the "Categories" nor as a standalone toolbar. The only access is via the menu

**Comment by r-a-v-a-s** [comment]
What category would you put it in?

The 'Misc' toolbar was replaced with 'DefaultCustom', which won't appear for you without clearing your settings. Just use the new custom toolbar creator.

https://github.com/LibreCAD/ChangeLogs/blob/master/developers/r-a-v-a-s/2-1/2-1-0/toolbar_creator.md

**Comment by vlachoudis** [comment]
Thanks! by clearing the config it worked :)
