### ISSUE TITLE
the file menu width is determined by recent file path length

### ISSUE THREAD

**Issue by JPSimardMG2** [LibreCAD/LibreCAD#709]

**Comment by r-a-v-a-s** [comment]
That's not enough information. Add a screenshot if you can't explain it further.

**Comment by r-a-v-a-s** [comment]
Also, please include the version of LibreCAD, the version of Qt and your operating system.

**Comment by JPSimardMG2** [comment]
When i click on the menu bar for Fichier it covers the whole screen. Uninstalled and reinstalled issue persist.

![librecad fichier menu issue 1 of 2](https://cloud.githubusercontent.com/assets/19266714/15124655/1ad39654-15f7-11e6-9077-e9ba67bdb703.png)
![librecad fichier menu issue 2 of 2](https://cloud.githubusercontent.com/assets/19266714/15124656/1ae7d48e-15f7-11e6-9ef0-3a0ebb80d3e7.png)

**Comment by r-a-v-a-s** [comment]
It's because the file path is not truncated.
I have been thinking about putting the recent files in a sub-menu.

**Comment by JPSimardMG2** [comment]
LibreCAD-Installer-2.0.10.exe
QT 5.4.1
Win10

**Comment by r-a-v-a-s** [comment]
Thanks 😎  I'll work on it.

**Comment by JPSimardMG2** [comment]
No problem glad to help you out.
