### ISSUE TITLE
Trying to draw ELLIPSE with particular dims. But manual method only works straight lines & circles

### ISSUE THREAD

**Issue by sparxz** [LibreCAD/LibreCAD#720]
I am trying to draw an ELLIPSE with particular dimensions.
On Sketchup this can be put in manually, but on Librecad only for straight lines and circles(both also by command line).
I have searched for vids on Youtube and checked the LibreCad manuals
Am I missing something ?

Thanks

**Comment by sand1024** [comment]
can be closed as already addressed
