### ISSUE TITLE
Could not divide some circles on intersection

### ISSUE THREAD

**Issue by Equoda** [LibreCAD/LibreCAD#721]
Some circles couldn't be "divided" on intersection with the other one. It's some kind of random behavior.

**Steps to reproduce:**

1. Create new draft.
2. Create "Circle (radius 90)".
3. Create 4 "Circles (radius 10)" in quarters of 2. so that they have two intersections every.
4. Select "Snap intersection" and use "Divide" on 3. in intersection points with 2.

**Result:**

Some of intersection points just couldn't be selected with cursor to divide on them. This happens randomly and only on circles as I know, not with ellipses for example.

**Librecad info:**

Version: 2.1.0-beta
Tag: 2.1.0-beta-8-g9723828
Compiler: GNU GCC 4.8.4
Compiled on: May 16 2016
Qt Version: 4.8.6
Boost Version: 1.54.0

**Example draft:**

[dividing.dxf.zip](https://github.com/LibreCAD/LibreCAD/files/267533/dividing.dxf.zip)

**Comment by dxli** [comment]
fix in master and 2.0 branches.

further fixes would be part of #523 in my quadratic branch
