### ISSUE TITLE
2.1.0 fails to compile with Qt4

### ISSUE THREAD

**Issue by ravenexp** [LibreCAD/LibreCAD#741]
librecad/src/ui/forms/qg_trimamountoptions.ui

uses

http://doc.qt.io/qt-5/qwidget.html#toolTipDuration-prop

which is a Qt5 thing.

**Comment by r-a-v-a-s** [comment]
sigh... I knew there would be something.
You basically can't use Qt5's ui Designer without it silently breaking Qt4 compatibility.

I'll add a patch to the 2.1.0 branch... but the master branch is officially Qt5+

**Comment by r-a-v-a-s** [comment]
For anyone stuck with Qt4: 
in the repository's folder you can use `git checkout 2.1` and then build.
