### ISSUE TITLE
Layer list disappears when closing inactive tab

### ISSUE THREAD

**Issue by Equoda** [LibreCAD/LibreCAD#753]
List of layers in ```Layer List``` widget become empty when closing inactive tab.

Steps to reproduce:

1. Create a new draft
2. Select ```Drawings -> Tab mode```
3. Create a new draft (second tab should open)
4. Close **inactive** tab. This may be the first or the second one

Result: the list of layers (```Layer List```) become empty. If open new draft it come back again.

**Comment by r-a-v-a-s** [comment]
And if you try to add a layer it will crash.

**Comment by r-a-v-a-s** [comment]
I've added a patch. Tests seem to work as expected.
