### ISSUE TITLE
spacebar for accepting commands

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#764]
I'll work on a way to have spacebar accept commands (like Enter).

http://forum.librecad.org/Do-you-use-the-cal-command-td5713782.html

**Comment by r-a-v-a-s** [comment]
Space-bar for entering commands is now a reality! :sunglasses: 

The cal command now functions as a toggle:

1. cal [space-bar]
2. 2+2 [space-bar]
3. sqrt(5) [space-bar]
4. cal [space-bar]

xbutton1 has been removed as a cmd line trigger... we will see if anyone complains;
no one has ever commented about it; and I might add it as a custom menu activator.

**Comment by Cantar4** [comment]
LC 2.2.0-alpha-24 installed,
how to (provisionally :) devote the space-bar to Free Snap ?
