### ISSUE TITLE
copied objects are not hidden with other layer objects

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#774]
1. create a circle
2. copy and paste
3. toggle layer visibility

The original circle is hidden, but the copy is not.

**Comment by r-a-v-a-s** [comment]
It works for Move / Copy,
but not for Ctrl+C / Ctrl+V.

**Comment by Equoda** [comment]
OK, there is a question.

While catching this bug some weakly related changes in code have been made, like: ```for (...;...;...)``` -> ```for (auto ... : ...)``` or additional ```if (!ptr)``` checks. Nothing critical, I think. Should it be a part of different pull request?

**Comment by r-a-v-a-s** [comment]
You can include those changes.

**Comment by Cantar4** [comment]
it seems that v2.2.1 still suffers from the same problem :
Ctrl+C/V now correctly transfer propperties but objects pasted that way are not hidden 
with the layer like the "move-copied' or the 'layer to layer' transfered ones are.

**Comment by Equoda** [comment]
Pull request #777 merged

**Comment by r-a-v-a-s** [comment]
@Cantar4 
There were no changes associated with this in 2.1.1
A full change log was included https://github.com/LibreCAD/LibreCAD/releases/tag/2.1.1
