### ISSUE TITLE
Layer selection in "Layer List" vanishes sometimes

### ISSUE THREAD

**Issue by Equoda** [LibreCAD/LibreCAD#775]
Layer selection in "Layer List" vanishes sometimes.
The current layer highlighting in "Layer List" does not set to correspond to the same in ```graphic``` object in such case.

Steps to reproduce:

1. Create a new draft
2. Select line with a layer name in "Layer List" widget (it is has not selected on start, by the way)
3. Create  a new draft, change to it
4. Change to draft 1. back

Result: no lines in "Layer List" widget selected.

This behavior force user to select active layer every time before pasting something, for example.

LibreCAD info:

Version: 2.2.0-alpha-34-ga282b5b
Compiler: GNU GCC 4.9.2
Compiled on: Jun 23 2016
Qt Version: 5.3.2
Boost Version: 1.55.0

**Comment by r-a-v-a-s** [comment]
Does this work as expected now?
