### ISSUE TITLE
Faulty command window when it is detached

### ISSUE THREAD

**Issue by Zmuogs** [LibreCAD/LibreCAD#790]
If command window is in detached mode then command input field misbehaves:
 - begin line drawing process;
 - press space -> field "Command" in a "Cmd" window activates;
 - when I press numbers keys in numpad ("numbers" mode) then nothing appears in "Command" field;
 - I can enter numbers by pressing numbers keys above letters keys;
 - enter text 30,5 and then place cursor before comma;
 - press Del -> whole text disappears.

I using daily build:
 Version: 2.2.0-alpha
 Compiler: GNU GCC 5.3.1
 Compiled on: Jun 10 2016
 Qt Version: 5.5.1
 Boost Version: 1.58.0
 System: Ubuntu 16.04 LTS 

See also forum [thread] (http://forum.librecad.org/bug-faulty-command-window-when-it-is-detached-td5714053.html).

**Comment by r-a-v-a-s** [comment]
The good news is that I solved the problem...
the bad news is that the daily ppa isn't being updated anymore,
and I don't know why.

You can build from source https://github.com/LibreCAD/LibreCAD/wiki/Build-from-source

**Comment by Zmuogs** [comment]
Thank you!
