### ISSUE TITLE
favorite colors dockwidget

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#793]
This dockwidget will allow for users to maintain a list of favorite colors.
This will allow for quickly:
- changing the active pen color
- changing the color of all selected objects
- selecting all objects of a specific color

**Comment by r-a-v-a-s** [comment]
This is a first step... currently this widget doesn't communicate with other widgets.
I'll work on a way to select a favorite on layer creation.

Double-click a favorite color to apply it to the active pen.
Right-click a favorite to access other actions.

**Comment by Cantar4** [comment]
(alpha 86 at work) to organize my rainbaw, how can I erase and replace colors 
in the custom pot array  ?  
would it be possible to select / open a pot before pouring in (or washing out) a given color?

**Comment by r-a-v-a-s** [comment]
You can organize favorites by dragging and dropping (as of alpha-87).

Right-click -> Remove
I'll probably give the right-click actions hotkeys.

Regarding your last question: 
It's an interesting idea.. I'll think about it.


If you really need to add and remove colors that often,
I would probably implement it as the ability to save/load sets of colors.

**Comment by Cantar4** [comment]
(alpha 87 on test)
You are now offering a color selection pattern going through two added stages of selection : 
an alphabetic list carrying all available colors and a list of the current project favorites.

Would you raise your alphabetical list (quite a long lasting poetic reading  ;)  to the upper level 
of the palette construction(*), not leave it at the project list constitution level where it's 
a real burden to search for a color by its native english name.

* when I can take the time to carefully choose a color either into a few classic samples, 
or the rainbow/wheel or your alpha list.

PS: bug noticed : colors added to the alpha list and descriptor augmented here,
become black/white when selected in the project's list.

**Comment by r-a-v-a-s** [comment]
Custom names are not supported;
that field is editable so that you can 
type in an existing color name
and it will auto complete.

If you think this widget is useful 
then it was fortunate that I had a brief surge of inspiration.

I won't be contributing much until the tangent point detection is improved.
Work on that hopefully starts sometime next month.

If anyone wants to work on an issue I have self assigned,
just let me know...
