### ISSUE TITLE
crash on undo after ctrl+c / ctrl + v

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#794]
1. create a circle
2. copy and paste with ctrl+c / ctrl+v
3. undo twice

:bomb:  crash

Also worth noting is the fact that nothing seems to be undone.

**Comment by Cantar4** [comment]
to avoid this funest double undoing  it would be wise to show the landing cross **_and_** the copied entity **_as soon as_** typing ctrl+v.
The way it is now, showing the cross without its attached entity, lets you click and land the entity while it's not yet on the  target, hence the need for an undo (which does not work)
and a second one which doesn't work either (and crashes the app).
