### ISSUE TITLE
librecad cannot find any fonts  also cannot write any text or mtext, help me

### ISSUE THREAD

**Issue by qq525qq** [LibreCAD/LibreCAD#798]
librecad cannot find any fonts  also cannot write any text or mtext, help me

**Comment by Cantar4** [comment]
which computer OS, which LibreCAD version ?

**Comment by qq525qq** [comment]
librecad version  :2.2.0-alpha
computer OS : windows7 
compiler :GNU GCC 4.9.2

**Comment by Cantar4** [comment]
you should work with the latest stable version,
LibreCAD_2-1-1.dmg (24.5 MB) 
https://sourceforge.net/projects/librecad/files/latest/download?source=files

**Comment by qq525qq** [comment]
thanks, but where to down the  source of the  stable version  ?

**Comment by Cantar4** [comment]
For Windows:
https://sourceforge.net/projects/librecad/files/Windows/2.1.1/
