### ISSUE TITLE
librecad cannot find any fonts  for simplified Chinese？

### ISSUE THREAD

**Issue by qq525qq** [LibreCAD/LibreCAD#799]
librecad cannot find any fonts  for simplified Chinese？if exits , how to get it?

**Comment by Cantar4** [comment]
Your question is probably not well suited to deserve an issue,
you should have a better chance to get an answer by opening a New Topic 
in the 'LibreCad-user' section of the LibreCAD forum
http://librecad.org/cms/home/get-help/forum.html
