### ISSUE TITLE
Setting of unit precision isn't applied

### ISSUE THREAD

**Issue by mhensch** [LibreCAD/LibreCAD#812]
![librecad_bug](https://cloud.githubusercontent.com/assets/6704225/18342943/89422014-75b1-11e6-9b67-8634f7429b3a.jpg)
Hi,
my LibreCad uses 0.0000 as precision regardless of the settings in Options -> Current drawing preferences

Version: 2.1.1
Compiler: GNU GCC 4.9.1
Compiled on: Jun 25 2016
Qt Version: 5.4.1
Boost Version: 1.60.0
System: Windows 7

**Comment by r-a-v-a-s** [comment]
That controls the statusbar's and info tools' precision.

You want to change the 'Linear precision' option in the dimensions tab.

**Comment by mhensch** [comment]
Thanks.
