### ISSUE TITLE
Crash in plugin: Ubuntu 16.04/14.04

### ISSUE THREAD

**Issue by Xia-Weiwen** [LibreCAD/LibreCAD#816]
Hi, there.
If I use `Document_Interface::getEnt` and then `Plug_Entity::getData`, the program crashes quite often (almost every time).

Following these steps may cause crash:
1. Draw two lines.
2. Activate the Same Properties plugin.
3. Select one line by mouse left click.
4. Select the other line and press enter.
5. If the program doesn't crash, try 1-4 again.

When debugging, I found that when crash happens, `Document_Interface::getEnt` returns a pointer pointing to 0xc0, which is not a valid Plug_Entity pointer. The plugin called _Same Property_ uses such functions and it causes crash as well.
I've tested in the following conditions:
1. LibreCAD 2.1/master branch, Ubuntu 16.04.1/14.04.5 64bit, Qt5.2.1/Qt 5.3.2/Qt 5.5.1, boost 1.58/1.61, GCC 5.4
2. LibreCAD  2.1/master branch, Windows 7 64bit/32bit, Qt 5.6/Qt 5.7
3. LibreCAD 2.1 branch, Lubuntu 14.04
In the 2nd and 3rd conditions, crash doesn't happen. In the 1st condition, crash happens almost every time.
I've tried `git reset --hard HEAD` to go back to some early versions of LibreCAD (as early as June this year), crash also happens.

I guess it's about the version of libraries/gcc/boost or so.
I am not able to figure it out.
Please help solve this.

**Comment by Xia-Weiwen** [comment]
Now I'm seeing the same problem using master branch in Ubuntu 16.04.
I'm sure the 2.1 branch I tested is the newest version.

**Comment by r-a-v-a-s** [comment]
I couldn't reproduce it on OS X with clang.
It crashed on the second try on OpenSUSE / lxqt with gcc 6.2.1
Both computers have Qt 5.6.1

**Comment by r-a-v-a-s** [comment]
I seems like `getEnt()` returns a valid pointer,
and `Plug_Entity::entity` is the `0xc0`.
I don't know what that means and I couldn't find a solution.

**Comment by Xia-Weiwen** [comment]
I've seen the same thing.
And now on Windows 7 (64 bit) with Qt 5.6/5.7 (32bit MinGW), I see crash happen in the same way but only in debug mode.

**Comment by Xia-Weiwen** [comment]
Something new:
Activating **any** plugin causes crash if release mode selected.

Evironment:
+ OS: Windows 10 Home Edition
+ LibreCAD Version: 2.2.0-alpha (master branch)
+ Compiler： GNU GCC 5.3
+ Qt Version：5.7.0
+ Boost Version: 1.61.0

Crash position:
```
\librecad\src\main\qc_applicationwindow.cpp:459
```
Warning in log:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is LC_Align(0x28c3cbe8), parent's thread is QThread(0x28c3c3a8), current thread is QThread(0x263760e8)
QG_LayerWidget::update: nullptr lastLayer
```

**Comment by r-a-v-a-s** [comment]
That seems like a separate Windows 10 / Qt 5.7 issue.
I never encountered that on any system.

If you want to write plugins,
and want to make a significant contribution to LibreCAD,
I encourage you to consider:
https://github.com/LibreCAD/LibreCAD/issues/822

Continuing to patch the current system,
and allowing people to write plugins with it,
is like fostering a disease that becomes
harder and harder to cure.

**Comment by Xia-Weiwen** [comment]
Thanks.
I'll try.

**Comment by Xia-Weiwen** [comment]
I found something:
Adding ``` : public Plug_Entity``` to the end of ```/librecad/src/main/doc_plugin_interface.h : 50``` works.
I'll keeping studying this.

**Comment by fa201** [comment]
I could not reproduce the issue.
Version: 2.2.0-rc1-190-g51b21cc7
Compiler: GNU GCC 7.5.0
Compiled on: Mar 29 2020
Qt Version: 5.9.5
Boost Version: 1.65.1
System: Ubuntu 18.04.4 LTS

**Comment by mi-hol** [comment]
should this issue be closed?

**Comment by Xia-Weiwen** [comment]
Yes. I think so. It's been too long.
