### ISSUE TITLE
"Explode" messing with colors of rectangle

### ISSUE THREAD

**Issue by Zmuogs** [LibreCAD/LibreCAD#819]
Steps to reproduce:
- start a new drawing,
- create second layer,
- color of second layer change to Green,
- while second layer is "current" draw a Rectangle:![explode_before](https://cloud.githubusercontent.com/assets/20404470/18608576/f2454a50-7cf5-11e6-850b-c33f13459b21.png)
- activate command "Explode" and explode mentioned Rectangle: you will get lines with various colors:![explode_after](https://cloud.githubusercontent.com/assets/20404470/18608589/3bc639e6-7cf6-11e6-9ae7-b84dcb4198e6.png)

Version: 2.2.0-alpha
Compiler: GNU GCC 5.4.0
Compiled on: Sep 15 2016
Qt Version: 5.5.1
Boost Version: 1.58.0
System: Ubuntu 16.04.1 LTS

**Comment by lordofbikes** [comment]
I can't test it at the moment, but I think the problem isn't the color. My assumption is, that the white lines are created on layer 0, which default color is white.
If so, the problem is related to losing the layer information for the new generated entities.
Can you confirm this?

**Comment by Zmuogs** [comment]
I used "Modify" -> "Properties" on Lines: Layer stays same, Color changes:
![line_properties_01](https://cloud.githubusercontent.com/assets/20404470/18614400/91addc74-7d96-11e6-81c3-46f507f1f668.png)
![line_properties_02](https://cloud.githubusercontent.com/assets/20404470/18614401/91b07cfe-7d96-11e6-8e28-3ecc70b43d6a.png)

**Comment by Equoda** [comment]
Yes, I confirm this, but can't investigate now due to the debugger problems.
This may be related to #755 because a rectangle is a some kind of container, like a block.

**Comment by FelixNotTheCat** [comment]
@lordofbikes @r-a-v-a-s For RS2::EntityPolylines, RS_Modification::explode() (in rs_modification.cpp) resolves layers (resolveLayer = true;) but not colours (resolvePen = false;). resolvePen = true; then resolves colours of all entities in a (polylines) container. Pls say whether I can commit the change.
(PS the containers first entity gets its colour from the container as opposed to from the preceding entity in the loop.)
