### ISSUE TITLE
Issue hatching areas with nested shapes

### ISSUE THREAD

**Issue by kostic2000** [LibreCAD/LibreCAD#826]
When trying to hatch a shape that has another enclosed shape, in some cases the fill is incorrect. It seems that some sharp edges make a difference, but not 100% sure.
Attached is an example DXF, where the areas are letters of a particular font converted to curves (by doing Explode).

Original drawing:
![hatch_letters](https://cloud.githubusercontent.com/assets/5673464/19055797/af43e840-89bd-11e6-92f1-4e42ed788e22.PNG)

Select all curves of one letter at a time and do a solid hatch. Here is what I get:
![hatch_issue](https://cloud.githubusercontent.com/assets/5673464/19055706/44fc772c-89bd-11e6-8a00-4248d11d3a92.PNG)

And here what I expected to get:
![hatch_expected](https://cloud.githubusercontent.com/assets/5673464/19055715/53a8fd40-89bd-11e6-8682-dfe330a9ae18.PNG)

Source DXF supplied in the zip
[hatch_issue.zip](https://github.com/LibreCAD/LibreCAD/files/507276/hatch_issue.zip)

**Comment by r-a-v-a-s** [comment]
It's reproducible simply by creating a rectangle inside another rectangle.

**Comment by FelixNotTheCat** [comment]
optimizeContours() isn't evolved enough yet to cope with selected, intersecting entities. ravas, could you please assign me (-assuming that's the way to do it) and i try beef it up

**Comment by lordofbikes** [comment]
@FelixNotTheCat you're welcome to work on this, but assigning is prohibited to team members.
So I assigned myself to give you the chance to work on it.
The recommend way is to fork LibreCAD and work on your own fork. Then we can discuss solutions there and finally create a pull request that we can merge your solution.

If you hit any issues, don't hesitate to ask here. Thanks for your contribution.

**Comment by FelixNotTheCat** [comment]
@lordofbikes many thanks Armin -simply don't want to step on others' toes, or do redundant work. Pls see today's LibreCAD/ commit (i.e. rs_hatch.cpp and rs_entitycontainer.cpp). It's far from a complete (hatch) solution but addresses issues such as highlighted by kostic2000; your/LC team's critiscm/comments/feedback etc is much appreciated.
