### ISSUE TITLE
how do i find the fonts path in librecad 2.2 on ubuntu 16.04

### ISSUE THREAD

**Issue by marvinbrewer** [LibreCAD/LibreCAD#828]
how do i find the fonts path in librecad 2.2 on ubuntu 16.04
I'm real new and need a lot of help
Thanks

**Comment by r-a-v-a-s** [comment]
Please use the forum for questions. http://forum.librecad.org/

Fonts are usually bundled. In the source they are at:
https://github.com/LibreCAD/LibreCAD/tree/master/librecad/support/fonts

In the program you set the directory via Application Preferences -> Paths -> Fonts

**Comment by marvinbrewer** [comment]
the program is asking me where there installed
the text isn't showing up in the drawing 
i need to supply the path to the fonts
