### ISSUE TITLE
Problems in Windows 10 with LibrerCAD 2.3.1

### ISSUE THREAD

**Issue by JudyK45** [LibreCAD/LibreCAD#832]
First I could not get Mtext to show up after several hours of it working perfectly. Text did not work either - whatever I had been doing before is what it continued to do. Closing the file and then closing and reopening LibreCAD did not solve the problem. Then it would not save my work as a PDF - the resulting document was blank. This was a serviceable 2-D CAD up to now, although clunky.

Help?

**Comment by r-a-v-a-s** [comment]
http://wiki.librecad.org/index.php/FAQ
