### ISSUE TITLE
Plugin Plotequation not running through end_Value

### ISSUE THREAD

**Issue by kludikovsky** [LibreCAD/LibreCAD#838]
When using the Plot-Function plugin, the function is not completed until the endVal.
So if I write a function for the interval from 0 - 100 the function is only calculated from 0-99

This seem to be due to a little mistake 
at plot.cpp at line 72

`for(equationVariable = startVal; equationVariable < endVal; equationVariable += stepSize)//end value is not used!
`
which only runs until 
` equationVariable < endVal;`

Correcting this to 
` equationVariable <= endVal;`
should solve the issue.

**Comment by lordofbikes** [comment]
I have no idea what the author of the plugin supposed to achieve. This code is from the first commit and the comment behind the loop describes your observation.
As I have found no side effects and no additional explanation, I fixed it.

Thanks for finding and reporting this.
