### ISSUE TITLE
custom page size - incorrect unit handling

### ISSUE THREAD

**Issue by pacew** [LibreCAD/LibreCAD#864]
### Expected behavior
Using Options -> Paper -> Custom, the desired Paper Width and Height should stick to the supplied values, and should appear in the PDF file when exporting

### Observed behavior
If you set Units to Inches and Paper Size to Custom, and enter, say 10 and 20 for the width and height. Then close the Drawing Preferences dialog, then re-open it, the values have changed to .3937 and .7874.
(these values are 10/25.4 and 20/25.4 - they have been scaled as if the previous numbers were millimeters).  Each time you re-open the dialog, the values have been scaled down again by another factor of 25.4.

### Steps to reproduce or sample file
Launch librecad so it shows a blank new drawing.  
Select Options -> Current Drawing Preferences
Select Units tab
Units -> Inches
Select Paper tab
Paper Format -> Custom
Paper Width -> 10
Paper Height -> 20
click OK
re-open dialog with Options -> Current Drawing Preferences
observe that Paper Width is now .3937 and Paper Height is .7874
close and re-open the dialog and observe that the Paper Width and Height are even smaller.

Also, if you export a PDF file, then do something like view it with evince and examine the properties, the page size has been scaled down improperly.

### Operating System and LibreCAD version info
Ubuntu 16.04
LibreCAD compiled from git commit 3ab980c of 2017-01-10 but also observed in librecad 2.0.9 from standard Ubuntu repository

After experimenting this afternoon, I believe the attached patch file is on the right track to fix the problem, but I have never looked at librecad before and I don't know if there are other parts of the program that may need similar attention.  It does make the size parameters sticky, and they do flow through to the exported PDF.

Thanks for a great tool!

[custom-units-fix.txt](https://github.com/LibreCAD/LibreCAD/files/751738/custom-units-fix.txt)

**Comment by lordofbikes** [comment]
The fix contributed by @webmite works fine for me.
If there are any further issues, please feel free to reopen it.
