### ISSUE TITLE
Feature Request: retain right click menu shortcuts during a session & across sessions

### ISSUE THREAD

**Issue by andykmv** [LibreCAD/LibreCAD#867]
### Expected behavior
when i have used some tools and therefore populated the right click menu, retaining the content of the right click menu shortcuts (and some means of modifying &/or manually populating/deleting right click menu items) will save time by having these available without having to re-use the tools to create the right click menu shortcuts when i am trying to rapidly work with drawings, libraries and blocks and when i am rapidly opening/closing files in a session (to copy elements & create/use blocks/libraries etc).
### Observed behavior
when i open first-file.dxf in a session and use some tools (eg Move/Copy or Stretch) these are added to the right click shortcut menu. when i close this file and open different file, eg second-file.dxf, the right click shortcut menu in this file is empty.
when i open first-file.dxf in a session and use some tools (eg Move/Copy or Stretch) these are added to the right click shortcut menu. whilst this file is open, and i open second-file.dxf, the right click shortcut menu in this file is empty.
when i open first-file.dxf in a session and use some tools (eg Move/Copy or Stretch) these are added to the right click shortcut menu. when i close librecad (closing the first-file.dxf in the process) then re-open librecad with any file the right click shortcut menu is empty.
### Operating System and LibreCAD version info
Windows 7 Pro with librecad 2.1.3

**Comment by r-a-v-a-s** [comment]
Widgets -> Menu Creator

http://wiki.librecad.org/index.php/User_Interface
