### ISSUE TITLE
Can not open DXF file

### ISSUE THREAD

**Issue by NguyenTrongThinh** [LibreCAD/LibreCAD#873]
I use LibreCAD to draw some shape then save file to disk, then i restart LibreCAD and choose file -> open to open my old file but i see not thing on screen except point (0, 0).

### Expected behavior
Open old file created by LibreCAD with full content
### Observed behavior
Open file but file content did not show on screen
### Steps to reproduce or sample file
Open LibcreCAD select file->new then draw some thing. Save file to disk. select file->Close then open file. Select File -> Open browse to file that saved before.
### Operating System and LibreCAD version info

Windows 10 64bits
LibreCAD v 2,1,3

**Comment by r-a-v-a-s** [comment]
Your steps would produce a DXF (not DWG).

What happens if you use view -> auto-zoom (double-click the scroll wheel)?

**Comment by NguyenTrongThinh** [comment]
Sorry for wrong file extension. It is "dxf". I try "view -> auto zoom" but i still can not see anything on screen. 
FYI, I have 2 PC, one ASUS and the other is HP, The problem happens on my HP computer. LibreCAD works fine when I open file on my ASUS PC. All of them use Windows 10 x64, LibreCAD 2.1.3.

**Comment by r-a-v-a-s** [comment]
My guess would be it's a Qt / Windows 10 issue.
Did you download from sourceforge? Is it still using Qt 5.4? (help -> about)
Building with Qt 5.7 _might_ solve it, because a lot of Windows 10 compatibility was added
after Qt 5.4.

**Comment by NguyenTrongThinh** [comment]
Thank for your response! i will try to build LibreCAD from source using Qt 5.7.0 (MingW 5.3) then debug on my HP PC, if the problem does not happen, I will report for you and close this issue.

**Comment by NguyenTrongThinh** [comment]
I have built LibreCAD (branch Master) with Qt 5.7.0 (mingW32 5.3.0) and tested. The problem I report did not happen. So i think it is Qt issues, I closed this issue
