### ISSUE TITLE
Corner rounding / fillet  trimming 

### ISSUE THREAD

**Issue by Haecksler** [LibreCAD/LibreCAD#879]

**Comment by webmite** [comment]
using fillet this is the behaviour I observe....selecting the first entity  behaves fine...but selection of the 2nd affects which direction the arc will go to join the lines.  If the mouse is 'between' the lines forming the acute angle then the fillet will form correctly....If the mouse is 'outside' the lines forming the acute angle then the fillet will be malformed.

It should not matter which side of the entity you are on when you click the mouse...both cases should produce the first 'correct' action.  2nd behaviour should be blocked.
![screenshot from 2017-11-24 09-50-22](https://user-images.githubusercontent.com/7873791/33215690-97ca5440-d0fe-11e7-8d82-067b2368487f.png)
![screenshot from 2017-11-24 09-50-43](https://user-images.githubusercontent.com/7873791/33215696-a01440a2-d0fe-11e7-9998-53182b9485ea.png)
![screenshot from 2017-11-24 09-51-02](https://user-images.githubusercontent.com/7873791/33215700-a4fc2ab2-d0fe-11e7-98cf-c9290fb7670a.png)

**Comment by lordofbikes** [comment]
I'm not sure if there was an issue with fillet tool in the past and I can't find any fix in git log. 
Maybe it is related with the _Trim_ checkbox in the tool bar. The checkbox and the fillet Radius input appear on top of the drawing area, when the fillet tool is selected.
![grafik](https://user-images.githubusercontent.com/386273/33218410-0c910b64-d13d-11e7-83d6-e8e492063334.png)
When Trim is unchecked, the tool works as reported. Maybe it was unchecked by accident?

For latest release I can confirm that it works fine, thus I'll close this issue.

@webmite your observations are correct, but this is how the tool was designed. I don't see the 2nd fillet as malformed, it may be a desired option to draw the arc this way. I think there is no reason to restrict the tool as the preview shows the drafter what happens next.
