### ISSUE TITLE
Block insert from Library browser with wrong insert point

### ISSUE THREAD

**Issue by mayersre** [LibreCAD/LibreCAD#929]
### Expected behavior
Show the same behaviour as when inserting the block ; Insert it with insert point on cursor
### Observed behavior
The insert point is 5 grid down, 5 grid left from the insert point of the block
[Valve_01_dxf.txt](https://github.com/LibreCAD/LibreCAD/files/1501292/Valve_01_dxf.txt)
### Steps to reproduce or sample file
Rename the attached file to .dxf
<good> open it with Librecad, Insert point OK </good>
<bad> copy it to a library e.g. /usr/share/librecad/library/mylib/valve.dxf and insert it from there, then the insert point is incorrect. </bad> 
### Operating System and LibreCAD version info

Version: 2.2.0-alpha
Compiler: GNU GCC 5.4.0
Compiled on: May 31 2017
Qt Version: 5.5.1
Boost Version: 1.58.0
System: Ubuntu 16.04.3 LTS

**Comment by lordofbikes** [comment]
From Library Browser you don't insert blocks, you insert complete drawings.
For blocks you define a reference point, which is the left valve connector in your example. This is the insertion point, when you add a block from the block list.

For a whole drawing there is no attribute like reference point of blocks. Thus LibreCAD insert drawings from library browser with their origin, which is at X=0, Y=0.

The valve in your drawing is located at X=50, Y=50. This is the reason for the observed behavior.

If you want that library browser insertion works similar to block insertion, simply move the reference point of the valve block to the origin (red cross at X=0, Y=0) of your example drawing.
