### ISSUE TITLE
Fix behaviour of Add Layer dialog to auto number the next layer by default

### ISSUE THREAD

**Issue by webmite** [LibreCAD/LibreCAD#935]
### Expected behavior
I would like the Add Layer dialogue to provide  an 'auto numbering' mechanism of the layer selected at the time of the Add Layer dialogue is invoked.  It should support both a BaseLayerName with additional number suffix, or just a running number identifier on it's own. It should also allow unique BaseLayerNames with no number suffix. Currently this is not the observed behaviour.
### Observed behavior
Currently if you click on the '+' button in the LayerList widget and no layer is selected you get the 'Add Layer' dialogue to popup with the new Layername = 'noname' . If you click 'OK' that then 'noname' becomes the current selected Layer in the LayerList widget.  Clicking the '+' button again brings up the 'Add Layer' dialogue with new Layername = 'noname2'. If you again accept and repeat the above process the next 'Add Layer' dialogue has the new Layername = 'noname22'.

### Operating System and LibreCAD version info
I don't believe this to be OS specific.

**Comment by lordofbikes** [comment]
merged :+1:
