### ISSUE TITLE
First point of spline wrongly evaluating to origin

### ISSUE THREAD

**Issue by goatchurchprime** [LibreCAD/LibreCAD#940]
A regression with the SPLINE type happened between versions 2.0.10 and 2.0.11, possibly around the point when non-uniform knot support was added:  https://github.com/LibreCAD/LibreCAD/commit/765ee0e3cf8d6f690d8695a16bf2bbd6d521130d

In the attached example, the first point of some splines is set to the origin, making the error pretty easy to spot.

I've not got a good C++ support here, but by using dxfgrabber in python I've isolated the problem to the 9th entity (the 3rd spline) in the file (there is nothing suspicious with the input data):  [badsplines.dxf.zip](https://github.com/LibreCAD/LibreCAD/files/1594371/badsplines.dxf.zip)

```Python
import dxfgrabber
d = dxfgrabber.readfile("badsplines.dxf")
e = d.entities[8]
print(e.__dict__)
>>>
{'color': 256,
 'control_points': [(810.0461257391106, 1327.446908121264, 0.0),
  (632.7988042284506, 1345.404683869549, 0.0),
  (455.6024882136279, 1363.876789976457, 0.0),
  (276.6083791430377, 1382.541764458178, 0.0),
  (274.8121061541776, 1382.729075009911, 0.0),
  (273.0158329399821, 1382.91638558446, 0.0)],
 'degree': 3,
 'dxftype': 'SPLINE',
```

![image](https://user-images.githubusercontent.com/677254/34454159-1e7adcce-ed5d-11e7-8583-786b0805af9e.png)

**Comment by lordofbikes** [comment]
additional details in Sourceforge ticket [599](https://sourceforge.net/p/librecad/bugs/599/)
