### ISSUE TITLE
Leaving 'print preview' shows random drawing

### ISSUE THREAD

**Issue by mru00** [LibreCAD/LibreCAD#944]
### Expected behavior

When I enter & leave 'print preview', I end up where I left.

### Observed behavior

I have a saved drawing open.

![image](https://user-images.githubusercontent.com/581904/35197137-aa44111e-fedb-11e7-8091-c403b2fea3ab.png)

I enter 'print preview', looks good (shows my drawing). 
![image](https://user-images.githubusercontent.com/581904/35197144-ba975d28-fedb-11e7-9904-2422bdd0b6d3.png)

I leave 'print preview'. 
![image](https://user-images.githubusercontent.com/581904/35197151-ccc8545c-fedb-11e7-9b14-4dfabb573ecb.png)

Then, LibreCAD shows some unsaved version of my drawing.
The unsaved changes I did before are lost.

### Steps to reproduce or sample file

[lenkrad.zip](https://github.com/LibreCAD/LibreCAD/files/1649997/lenkrad.zip)

### Operating System and LibreCAD version info

![image](https://user-images.githubusercontent.com/581904/35197116-72df7ec0-fedb-11e7-9662-f2231e75154a.png)

On Windows 10 64bit. Installed from binary installer from website: https://sourceforge.net/projects/librecad/files/Windows/NightlyBuilds/2.0/LibreCAD-Installer-2.0.11-15-g90c1b83.exe/download

**Comment by lordofbikes** [comment]
This issue is further handled with #1207.
