### ISSUE TITLE
Colors(black and white) don't switch while exporting

### ISSUE THREAD

**Issue by philectro** [LibreCAD/LibreCAD#962]
### Expected behavior
While exporting from white on black work view, it should be automatically set to black on white while exporting.
### Observed behavior
The lines from the working view disappear while exporting to picture(white on white).
### Steps to reproduce or sample file
Creating something on black background, export with white background.
### Operating System and LibreCAD version info
All version tested on all OS tested,Ubuntu and Windows 10 CFU, 2.0.9, 2.1.3, 2.2 rc1

Note: sorry if this is not the right way to use the program, i don't report it for myself.

**Comment by shawncurry** [comment]
Confirmed.  But it seems much worse than described above.  I'm having serious problems with any newly created drawings. Older drawing seem fine.  2.2 rc1

- File --> New
- Draw a rectangle
- File --> Export --> PDF
- Open it

![outofrange](https://user-images.githubusercontent.com/50385855/58364560-5cd8b680-7e84-11e9-94a3-22fedafc5d59.png)

- Save the DXF - Close/Open LibreCAD - Open DXF - ExportPDF
- Same result!
- Use the examples from Issue #1056 "Files created in LibreCAD do not open in AutoCAD"
- Exported PDF is fine

**Comment by fa201** [comment]
In case it helps to hunt the bug, it works if you print the PDF instead of exporting it, at least with my Ubuntu.
