### ISSUE TITLE
The outside offset result of polyline isn't connected when the direction of polyline is counterclockwise.

### ISSUE THREAD

**Issue by shangke1988** [LibreCAD/LibreCAD#972]
### Observed behavior
The outside  offset result of polyline isn't connected when the direction of polyline is counterclockwise.

### Steps to reproduce or sample file
1. draw a counterclockwise polyline 
2. Modify-> Offset, click on the outside of polyline 

### Operating System and LibreCAD version info
Version: 2.2.0-rc1
Compiler: GNU GCC 4.9.1
Compiled on: Feb 16 2018
Qt Version: 5.4.1
Boost Version: 1.53.0
System: Windows 8.1

### Probable reason
line [605-613](https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/engine/rs_polyline.cpp#L600) in the file [librecad/src/lib/engine/rs_polyline.cpp](https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/lib/engine/rs_polyline.cpp)
```
    RS_VectorSolutions sol1;
    for(const RS_Vector& vp: sol0) {
        if(!RS_Math::isAngleBetween( intersections.at(i).angleTo(vp),
                                     pnew->entityAt(i)->getDirection2(),
                                     pnew->entityAt(i+1)->getDirection1(),
                                     false)) {
            sol1.push_back(vp);
        }
    }
```

I think this check is useless and deal the disconnected. 
At line 615, choosing the nearest point can deal with polyline and arc.
Is there some situation need this check?

**Comment by lordofbikes** [comment]
fixed with #973
