### ISSUE TITLE
How can I start to develop the LibreCAD?

### ISSUE THREAD

**Issue by xiaozhaolook** [LibreCAD/LibreCAD#999]
Hi, everyone
     I have some experience on C++ coding, and I want to make a 2D sketcher using C++ and Qt, I have searched open source code for help, QCAD and LibreCAD seems to be the most popular free code, but I didn't find enough resources for me to start the develop based LibreCAD, anyone can help me?

**Comment by lordofbikes** [comment]
You have to search more seriously. This is not a topic for code repository issues, your welcome to ask such questions at http://forum.librecad.org.

Our homepage https://librecad.org/ is linked in the README.
On the homepage you find more information, at least go to our wiki for more details.

Generally, start by forking/cloning the repo and set up the build environment to build LibreCAD from source. Then you can study and work on the code at your pleasure.
